### ISSUE TITLE
vdhs seems to flake on tsan

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#11286] opened 2020-05-21 15:04 UTC
Running a bunch of tsan tests for a change in the works, and after vhds test failed locally I checked on master
 bazel test --config=clang-tsan //test/...  --runs_per_test=3
fails pretty reliably for me, though
bazel test --config=clang-tsan //test/integration:vhds_integration_test   --runs_per_test=3
works, so I'd guess it's load related.

hot restart tests fails with runs_per_test=3 but that's a known bug with base-id with a fix in the works.

==================
WARNING: ThreadSanitizer: data race (pid=12)
  Write of size 8 at 0x7b140000f730 by thread T17:
    #0 free <null> (vhds_integration_test+0x282f3f4)
    #1 std::__1::_DeallocateCaller::__do_call(void*) <null> (vhds_integration_test+0x28e1718)
    #2 std::__1::_DeallocateCaller::__do_deallocate_handle_size(void*, unsigned long) <null> (vhds_integration_test+0x28e16e4)
    #3 std::__1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long) <null> (vhds_integration_test+0x28e1684)
    #4 std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) <null> (vhds_integration_test+0x28e1618)
    #5 std::__1::allocator<std::__1::__shared_ptr_emplace<std::__1::function<void (bool)>, std::__1::allocator<std::__1::function<void (bool)> > > >::deallocate(std::__1::__shared_ptr_emplace<std::__1::function<void (bool)>, std::__1::allocator<std::__1::function<void (bool)> > >*, unsigned long) <null> (vhds_integration_test+0x3879351)
    #6 std::__1::__shared_ptr_emplace<std::__1::function<void (bool)>, std::__1::allocator<std::__1::function<void (bool)> > >::__on_zero_shared_weak() <null> (vhds_integration_test+0x3878d70)
    #7 std::__1::weak_ptr<std::__1::function<void (bool)> >::~weak_ptr() <null> (vhds_integration_test+0x391cef2)
    #8 Envoy::Router::RdsRouteConfigProviderImpl::onConfigUpdate() <null> (vhds_integration_test+0x39c3cc1)
    #9 Envoy::Router::VhdsSubscription::onConfigUpdate(google::protobuf::RepeatedPtrField<envoy::service::discovery::v3::Resource> const&, google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (vhds_integration_test+0x39f68b4)
    #10 Envoy::Config::GrpcSubscriptionImpl::onConfigUpdate(google::protobuf::RepeatedPtrField<envoy::service::discovery::v3::Resource> const&, google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (vhds_integration_test+0x4ceb30f)

cc @dmitri-d

**Comment by dmitri-d** [comment] 2020-05-21 21:28
This is a duplicate of https://github.com/envoyproxy/envoy/issues/9784. Please also see comments in https://github.com/envoyproxy/envoy/pull/9828#issuecomment-594231950, https://github.com/envoyproxy/envoy/pull/9828#issuecomment-594231950 in particular.

**Comment by alyssawilk** [comment] 2020-05-26 12:38
Sorry for missing the dup.  I'll close this one off but if it has been causing CI failures for months we really should fix it.

**Closed** 2020-05-26 12:37 UTC
Labels: area/test flakes

**Comment by dmitri-d** [comment] 2020-05-26 18:32
> if it has been causing CI failures for months we really should fix it.

Agreed. I think it's a false-positive, but would be good if someone else took another look at it...
