### ISSUE TITLE
Envoy should poll cds server when no clusters are present

### ISSUE THREAD

**Issue by YourTechBud** [envoyproxy/envoy#9517] opened 2019-12-29 04:29 UTC
Currently, envoy sends back a 503 whenever no endpoints are present in the cluster config. To be clear, the cluster is defined, but there are no endpoints present in it.

It would be great if we could make envoy poll the cds server whenever its gets a request. It can buffer the request till the timeout has been reached or an upstream service is available (cds server updated the endpoints). 

This can be an opt in behaviour rather than the default by provided some field in the cluster config

**Comment by mattklein123** [comment] 2019-12-29 18:28
This is effectively a duplicate of https://github.com/envoyproxy/envoy/issues/2500 which is "on demand" xDS. Note that it is possible to implement this via extensions, but it's not available yet in OSS.

**Closed by mattklein123** 2019-12-29 18:28 UTC
