### ISSUE TITLE
O(log n) matching for HTTP routes - Feature Request

### ISSUE THREAD

**Issue by rnd4222** [envoyproxy/envoy#6823] opened 2019-05-06 18:12 UTC
For now, envoy uses linear probing of different routes for a virtual host, which takes linear time in worst case and could be a problem if virtual host contains lots of routes.
One use case is a function-level routing (something like Gloo does).
This request is to add tree-like matching for regexes/prefixes to obtain logarithmic runtime.
Also, something like [Intel Hyperscan](https://github.com/intel/hyperscan) could be used to match multiple regexes at once.

**Comment by mattklein123** [comment] 2019-05-06 19:52
This is a duplicate of https://github.com/envoyproxy/envoy/issues/6602 so let's track there. @rnd4222 can you update that issue if there is anything missing? Thank you.

**Closed by mattklein123** 2019-05-06 19:52 UTC
