### ISSUE TITLE
Build without running any tests

### ISSUE THREAD

**Issue by changqiguo** [envoyproxy/envoy#29604] opened 2023-09-13 17:01 UTC
*Title*: *Build envoy without running any tests*

*Description*:
>We would like to build envoy without running any tests, from the docs we could not figure out a way, could someone provide a way to achieve this. many thanks

**Comment by adisuissa** [comment] 2023-09-13 17:50
Do you mean build from source?
Envoy uses [Bazel](https://bazel.build/). Building a target can be done by: `bazel build //path/to/target:target_name`.
Building and running the tests can be done by: `bazel test //path/to/target:target_name`.

**Comment by changqiguo** [comment] 2023-09-13 17:53
> Do you mean build from source? Envoy uses [Bazel](https://bazel.build/). Building a target can be done by: `bazel build //path/to/target:target_name`. Building and running the tests can be done by: `bazel test //path/to/target:target_name`.

thank you very much for reply, we are building from source code,  as i understood bazel build will have the test executed. for example bazel --output_base=${WORKSPACE}/buildop build --define=boringssl=fips --repository_cache= --verbose_failures -c opt --config=clang //source/exe:envoy-static; this will execute tests.
How could we skip tests?

**Comment by adisuissa** [comment] 2023-09-13 18:04
Which tests are you referring to?

I think there's a single target (related to router) that when built is running tests, but other than that tests should not be built/executed.

**Comment by phlax** [comment] 2023-09-13 18:18
this is kinda a duplicate of https://github.com/envoyproxy/envoy/issues/28755 - at least in terms of what needs to be addressed

its pretty high on my radar

**Comment by moderation** [comment] 2023-09-16 19:32
I build without running test on Linux `aarch64` and `x86-64` and MacOS `aarch64`.

`bazel build -c opt //source/exe:envoy-static.stripped`

**Comment by phlax** [comment] 2023-09-16 19:40
i think we can close this since #29646 landed - that creates a tarball including contrib and debug which not everyone will want but works with the Docker build as it stands

im thinking we can add some thinner targets that do more like your suggestion and probs make the docker build work without debug bins etc

for now tho i think this issue has been addresesd

**Closed by phlax** 2023-09-16 19:40 UTC
Labels: question
