### ISSUE TITLE
configdump `include_eds` giving unexpected behavior for  `additional_addresses`

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#35100] opened 2024-07-08 19:52 UTC
Followup to https://github.com/envoyproxy/envoy/issues/34740.

What we send to envoy:
```
clusterName: outbound|80||echo-v6v4.default.svc.cluster.local
endpoints:
- lbEndpoints:
  - endpoint:
      additionalAddresses:
      - address:
          socketAddress:
            address: fd00:10:244::8
            portValue: 80
      address:
        socketAddress:
          address: 10.244.0.8
          portValue: 80
    healthStatus: HEALTHY
    loadBalancingWeight: 1
    metadata:
      filterMetadata:
        istio:
          workload: echo;default;echo;;Kubernetes
  loadBalancingWeight: 1
  locality: {}
'@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
clusterName: outbound|15010||istiod.istio-system.svc.cluster.local
endpoints:
- lbEndpoints:
  - endpoint:
      additionalAddresses:
      - address:
          socketAddress:
            address: fd00:10:244::e
            portValue: 15010
      address:
        socketAddress:
          address: 10.244.0.14
          portValue: 15010
    healthStatus: HEALTHY
    loadBalancingWeight: 1
    metadata:
      filterMetadata:
        istio:
          workload: istiod;istio-system;istiod;;Kubernetes
  loadBalancingWeight: 1
  locality: {}

```

What configdump shows
```yaml
- endpoint_config:
    '@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
    cluster_name: outbound|80||echo-v6v4.default.svc.cluster.local
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 10.244.0.8
              port_value: 80
          health_check_config: {}
        health_status: HEALTHY
        load_balancing_weight: 1
        metadata:
          filter_metadata:
            istio:
              workload: echo;default;echo;;Kubernetes
      load_balancing_weight: 1
      locality: {}
    policy:
      overprovisioning_factor: 140
- endpoint_config:
    '@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
    cluster_name: outbound|15010||istiod.istio-system.svc.cluster.local
    endpoints:
    - lb_endpoints:
      - endpoint:
          additional_addresses:
          - address:
              socket_address:
                address: 10.244.0.13
                port_value: 15010
          - address:
              socket_address:
                address: fd00:10:244::d
                port_value: 15010
          address:
            socket_address:
              address: 10.244.0.13
              port_value: 15010
          health_check_config: {}
        health_status: HEALTHY
        load_balancing_weight: 1
        metadata:
          filter_metadata:
            istio:
              workload: istiod;istio-system;istiod;;Kubernetes
      load_balancing_weight: 1
      locality: {}
    policy:
      overprovisioning_factor: 140
```

We see one is missing the endpoint, and one is duplicating them

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

**Comment by nezdolik** [comment] 2024-07-09 11:55
cc @jmarantz

**Comment by leosarra** [comment] 2024-07-09 13:50
The issue of the additional_addresses dump containing also the default address should be fixed by #35120 
The bug was caused by the fact that I erronously considered _addresses_list_ to be the list of additional addresses instead of a list containing _default_address+additional_addresses_.

I'm still looking into reproducing the other issue that was reported where there is a missing entry.

**Comment by leosarra** [comment] 2024-07-11 09:37
While trying to reproduce the issue I also realized that hosts from static clusters never had their addresses list set which led to incomplete additional_addresses in configdumps as well.
I have addressed that one as well as part of the PR.

The dump from my side looks fine now [istioctl_pc_endpoints.txt](https://github.com/user-attachments/files/16174415/istioctl_pc_endpoints.txt) (I used istioctl configdump viewer without the workaround that was applied to filter out the duplicated entries that were there before).
@howardjohn can you check that it looks good for you as well with https://github.com/envoyproxy/envoy/pull/35120 applied?

**Comment by howardjohn** [comment] 2024-07-11 11:46
nice!

**Comment by leosarra** [comment] 2024-07-22 09:16
@nezdolik can this issue be closed now that the PR is merged?
I don't the permissions to change the status of the issue on GitHub

**Closed** 2024-07-22 14:47 UTC
Labels: bug, area/admin
