### ISSUE TITLE
Envoy debug docker images not include correct binary

### ISSUE THREAD

**Issue by HackToday** [envoyproxy/envoy#28401] opened 2023-07-14 09:50 UTC
*Title*: *debug docker images not include correct binary as doc*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*: following https://www.envoyproxy.io/docs/envoy/latest/start/install#pre-built-envoy-docker-images
it have 
>> `envoyproxy/envoy:debug-<version> / envoyproxy/envoy:<variant>-debug-<version>[](https://www.envoyproxy.io/docs/envoy/latest/start/install#envoyproxy-envoy-debug-version-envoyproxy-envoy-variant-debug-version)
These images are built for each of the variants, but with an Envoy binary containing debug symbols.`

but with docker run with those image,

root@9ee4xxxxx:/# objdump -t /usr/local/bin/envoy 

/usr/local/bin/envoy:     file format elf64-x86-64

SYMBOL TABLE:
no symbols

**Comment by phlax** [comment] 2023-07-14 10:05
hi @HackToday this is a dupe of #28100 which has been fixed in `main` and on the branch itself

i am just working on a release now for the 1.26 branch, so it should hopefully be out later today and that will contain the fix (35b7604a27def047434f1dddf4ddf4a8877a7553)

**Comment by phlax** [comment] 2023-07-14 20:10
this should now be resolved in the latest 1.26 release

https://github.com/envoyproxy/envoy/releases/tag/v1.26.3

please open separate ticket/s if you are still hitting issues using the debug images, thanks

**Closed by phlax** 2023-07-14 20:10 UTC
Labels: bug, area/docker, area/release
