### ISSUE TITLE
debug assertion: `!is_draining_for_deletion_`

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#24573] opened 2022-12-16 00:58 UTC
*Title*: debug assertion: `!is_draining_for_deletion_` triggering

*Description*:
```
2022-12-14T20:57:33.046318Z	critical	envoy assert external/envoy/source/common/conn_pool/conn_pool_base.cc:110	assert failure: !is_draining_for_deletion_.	thread=32
2022-12-14T20:57:33.071746Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:104	Caught Aborted, suspect faulting address 0x53900000017	thread=32
2022-12-14T20:57:33.072081Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:91	Backtrace (use tools/stack_decode.py to get line numbers):	thread=32
2022-12-14T20:57:33.072258Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:92	Envoy version: f1664e6f8f06086d34bba6c04297df2ebbbcf7d1/1.25.0-dev/Clean/DEBUG/BoringSSL	thread=32
2022-12-14T20:57:34.143851Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#0: Envoy::SignalAction::sigHandler() [0x556ec53c422c]	thread=32
2022-12-14T20:57:34.144305Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:98	#1: [0x7f5cd2216520]	thread=32
ConnectionImpl 0x556ecc749f80, connecting_: 0, bind_error_: 0, state(): Open, read_buffer_limit_: 1048576
socket_: 
  ListenSocketImpl 0x556ece9f0780, transport_protocol_: 
  connection_info_provider_: 
    ConnectionInfoSetterImpl 0x556ecdbc1a18, remote_address_: 10.30.0.34:18080, direct_remote_address_: 10.30.0.34:18080, local_address_: 10.30.0.20:58452, server_name_: 
```

I am working on getting core dumps. For some reason this didn't trigger any, unclear why. 

It seems like it may be related to https://github.com/envoyproxy/envoy/issues/22583 given it is failing on ORIG_DST traffic

*Repro steps*:
Not clear yet, I don't yet have a minimal reproducer.

**Comment by kyessenov** [comment] 2022-12-16 05:03
I'm pretty sure it's a duplicate of #22583. The state transition invariant is somehow broken for a host, so it's triggering the assertions depending on where it happens.

**Closed** 2022-12-16 20:12 UTC
Labels: bug, triage
