### ISSUE TITLE
hot restart: child should wait sockets to be created when reuse_port is enabled

### ISSUE THREAD

**Issue by caitong93** [envoyproxy/envoy#14295] opened 2020-12-06 09:02 UTC
*hot restart: child should wait  when reuse_port is enabled*

*Description*:

In https://github.com/envoyproxy/envoy/blob/release/v1.16/source/server/server.cc#L569 , if reuse_port is enabled, `listener_manager_->startWorkers(*worker_guard_dog_)` does not wait actual sockets to be created.  it's possible when parent stops listeners, child listeners are not listening.

*Repro steps*:

See repro steps [here](https://github.com/caitong93/envoy-playground/tree/main/socket-intercepting#reproduce-httpsgithubcomenvoyproxyenvoyissues14295)

*Background*

We are doing Envoy + VCL integration by intercepting system calls(we know TransportSocket extension, but there are some internal reasons). For the first `socket()` call for each worker, it will try to connect to VCL and block for 50ms.
When testing hot restarting, we found traffic loss which was caused by the issue described above.

**Comment by dio** [comment] 2020-12-07 01:31
cc. @KBaichoo

**Comment by mattklein123** [comment] 2020-12-07 05:31
This is true, and I'm surprised no one has reported this before, but I guess reuse_port has not been commonly used with hot restart. We should not start parent drain until the workers are fully running. I will assign this to myself and try to take a look at some point unless anyone gets there first.

**Comment by KBaichoo** [comment] 2020-12-07 15:51
IIUC, this has been a latent bug for a while. The issue is that there's no synchronization between the sockets actually being created in the child and the parent draining traffic, so it's possible that the parent drains, but the children aren't ready **bad things** could happen to the traffic.

I don't think the change to `startWorkers()` that I made should really affect this, since it I just swapped out a which guarddog is passed to the call in pr #13015

**Closed** 2020-12-19 23:14 UTC
Labels: area/server, bug, help wanted
