### ISSUE TITLE
Inconsistent allowing environment variables in configs

### ISSUE THREAD

**Issue by johnpmayer** [envoyproxy/envoy#32057] opened 2024-01-25 22:07 UTC
Under what conditions are environment variables substituted in the config file (YAML specifically, I suppose)? Just the normal config passed via `envoy -c <file>.yaml`, without doing any external preparatory substitution, e.g. with a script using `envsubst`.

For example, I'm defining an OAuth2 http filter:

```
authorization_endpoint: ${AUTHORIZE_URL}
redirect_uri: ${CALLBACK_URL}
```

This seems to work fine for redirect_uri and many other places, but curiously (and seemingly arbitrarily) doesn't work fro authorization_endpoint. In the proto api, both are simply strings, with the same validator rules (minimum length).

I am able to use environment variables using the `${VAR}` syntax for redirect_uri, client_id, path matchers, auth scopes. It also works for the address of the endpoint when defining a cluster.

Searching around, this is purportedly not supported, but it appears to work empirically sometimes. If anything, this is difficult to reason about.

https://github.com/envoyproxy/envoy/issues/22152

**Comment by zuercher** [comment] 2024-01-26 23:50
There is no condition under which Envoy performs environment variable substitution in configs before parsing.

You can pass YAML-encoded proto via a command line argument (`--config-yaml`). This is subject to OS limits on command line length. Obviously, the shell will alter the value subject to shell substitution rules before Envoy sees the config. That argument, once parsed as an `envoy.config.bootstrap.v3.Bootstrap` is merged (e.g. using the protobuf library's MergeFrom utility) into whatever was previously loaded via `--config` (if anything). I believe this was intended to allow tweaking bootstrap-level values (node metadata, etc), but the merge operates recursively on the Bootstrap object and its nested messages.

I hacked together a config with an oauth filter in it and set the `redirect_uri` to `${CALLBACK_URL}`. As expected, after loading envoy with `--config`, I can see that the field's value is "${CALLBACK_URL}" via Envoy's `/config_dump` admin endpoint.

Formatters

The oauth filter does pass the `redirect_uri` to Envoy's log formatting code and that supports environment variable substitution. The format is different from the shell-style: `%ENVIRONMENT(CALLBACK_URL)%` (See the bottom of https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage.) AFAICT that filter only does this for redirect_url.

Generally speaking, any place where the %-formatters work (logs, header manipulation) can do an environment variable lookup using that syntax. I presume that formatter support for the oauth plugin predates the ability to lookup environment variables and exists so that the redirect URI can be based on request metadata.

Other

Besides the formatter code, I found some other uses of environment variables (specifically `getenv`) in Envoy:
* There is explicit support for looking up environment variables in the [data source object](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto.html#config-core-v3-datasource).
* Tracing supports picking up [custom tags](source/common/quic/platform/quiche_logging_impl.cc) from an environment variable, again by explicit config.
* `ENVOY_NGHTTP2_TRACE` and `ENVOY_QUICHE_VERBOSITY` enable additional logging for those libraries.
* The AWS extensions use a number of common `AWS_`-prefixed environment variables.
* The WASM `VmConfig` allows allow-listing environment variables that can be accessed by WASM extensions.
* There's a plugin for the [unified matcher api](https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#unified-matcher-api-proto) that allows environment variable lookup, by config.

**Comment by johnpmayer** [comment] 2024-01-26 23:54
Thanks for the clarification.

I resolved this in my setup with a launch script using envsubst, which
feels much more robust.

**Closed** 2024-01-30 06:04 UTC
Labels: question, area/configuration
