### ISSUE TITLE
clang-tidy error in post-submit: ambiguous argument 'HEAD^'

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#27024] opened 2023-04-27 13:51 UTC
In post-submit we see a clang-tidy error from time to time:
```
fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Running clang-tidy-diff against HEAD^ (HEAD^), current HEAD (36644db0842e2ffe6cfae85ab13401b63095f51b)
fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Clang-tidy failed.
```

Log link: https://dev.azure.com/cncf/envoy/_build/results?buildId=135368&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c&l=536

**Comment by adisuissa** [comment] 2023-04-27 13:51
cc @phlax

**Comment by phlax** [comment] 2023-04-27 13:51
this is release ci and basically a dupe of #27018

**Closed by phlax** 2023-04-27 13:51 UTC
Labels: area/build, area/ci
