### ISSUE TITLE
envoy --mode validate w/ ext-auth static config causes crash in v1.19.0

### ISSUE THREAD

**Issue by blevz** [envoyproxy/envoy#17640] opened 2021-08-09 17:11 UTC
*Title*: envoy --mode validate w/ ext-auth static config causes crash in v1.19.0

*Description*:
When validating a static config that contains ext-auth envoy crashes.  I would expect it to either produce a report about why the config is invalid or report that the config is valid.

*Repro steps*:
Using envoy v1.19.0 (this correctly prints a validation issue in v1.18.3)
curl https://github.com/envoyproxy/envoy/blob/main/examples/ext_authz/config/http-service.yaml > test.yaml && envoy -c test.yaml --mode validate

**Comment by ggreenway** [comment] 2021-08-09 18:33
Backtrace: 

```
[2021-08-09 18:32:22.261][61844][info][config] [source/server/configuration_impl.cc:97] loading 1 listener(s)
[2021-08-09 18:32:22.284][61844][critical][assert] [./source/server/config_validation/server.h:113] panic: not implemented
[2021-08-09 18:32:22.284][61844][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0xf194
[2021-08-09 18:32:22.284][61844][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2021-08-09 18:32:22.284][61844][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 68fe53a889416fd8570506232052b06f5a531541/1.19.0/Modified/DEBUG/BoringSSL
[2021-08-09 18:32:22.321][61844][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x558335e61c97]
[2021-08-09 18:32:22.321][61844][critical][backtrace] [./source/server/backtrace.h:96] #1: __restore_rt [0x7f2a8e0d1980]
[2021-08-09 18:32:22.357][61844][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::Server::ServerFactoryContextImpl::bootstrap() [0x558334d59ccb]
[2021-08-09 18:32:22.392][61844][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::Extensions::HttpFilters::ExtAuthz::ExtAuthzFilterConfig::createFilterFactoryFromProtoTyped() [0x558333751b8d]
[2021-08-09 18:32:22.427][61844][critical][backtrace] [./source/server/backtrace.h:96] #4: Envoy::Extensions::HttpFilters::Common::FactoryBase<>::createFilterFactoryFromProto() [0x55833375cad8]
[2021-08-09 18:32:22.463][61844][critical][backtrace] [./source/server/backtrace.h:96] #5: Envoy::Extensions::NetworkFilters::HttpConnectionManager::HttpConnectionManagerConfig::processFilter() [0x558335524c36]
[2021-08-09 18:32:22.499][61844][critical][backtrace] [./source/server/backtrace.h:96] #6: Envoy::Extensions::NetworkFilters::HttpConnectionManager::HttpConnectionManagerConfig::HttpConnectionManagerConfig() [0x5583355238ec]
[2021-08-09 18:32:22.535][61844][critical][backtrace] [./source/server/backtrace.h:96] #7: __gnu_cxx::new_allocator<>::construct<>() [0x558335541266]
[2021-08-09 18:32:22.578][61844][critical][backtrace] [./source/server/backtrace.h:96] #8: std::allocator_traits<>::construct<>() [0x55833553f74b]
[2021-08-09 18:32:22.620][61844][critical][backtrace] [./source/server/backtrace.h:96] #9: std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>() [0x55833553db79]
[2021-08-09 18:32:22.660][61844][critical][backtrace] [./source/server/backtrace.h:96] #10: std::__shared_count<>::__shared_count<>() [0x55833553ab9c]
[2021-08-09 18:32:22.699][61844][critical][backtrace] [./source/server/backtrace.h:96] #11: std::__shared_ptr<>::__shared_ptr<>() [0x558335538222]
[2021-08-09 18:32:22.739][61844][critical][backtrace] [./source/server/backtrace.h:96] #12: std::shared_ptr<>::shared_ptr<>() [0x55833553540b]
[2021-08-09 18:32:22.775][61844][critical][backtrace] [./source/server/backtrace.h:96] #13: std::allocate_shared<>() [0x558335532a7a]
[2021-08-09 18:32:22.811][61844][critical][backtrace] [./source/server/backtrace.h:96] #14: std::make_shared<>() [0x55833552eec6]
[2021-08-09 18:32:22.847][61844][critical][backtrace] [./source/server/backtrace.h:96] #15: Envoy::Extensions::NetworkFilters::HttpConnectionManager::Utility::createConfig() [0x558335520232]
[2021-08-09 18:32:22.882][61844][critical][backtrace] [./source/server/backtrace.h:96] #16: Envoy::Extensions::NetworkFilters::HttpConnectionManager::HttpConnectionManagerFilterConfigFactory::createFilterFactoryFromProtoTyped() [0x55833552064b]
[2021-08-09 18:32:22.917][61844][critical][backtrace] [./source/server/backtrace.h:96] #17: Envoy::Extensions::NetworkFilters::Common::FactoryBase<>::createFilterFactoryFromProto() [0x5583355453d5]
[2021-08-09 18:32:22.953][61844][critical][backtrace] [./source/server/backtrace.h:96] #18: Envoy::Server::ProdListenerComponentFactory::createNetworkFilterFactoryList_() [0x558335466034]
[2021-08-09 18:32:22.988][61844][critical][backtrace] [./source/server/backtrace.h:96] #19: Envoy::Server::ValidationInstance::createNetworkFilterFactoryList() [0x558334d5b79d]
[2021-08-09 18:32:23.023][61844][critical][backtrace] [./source/server/backtrace.h:96] #20: Envoy::Server::ListenerFilterChainFactoryBuilder::buildFilterChainInternal() [0x558335472b4b]
[2021-08-09 18:32:23.059][61844][critical][backtrace] [./source/server/backtrace.h:96] #21: Envoy::Server::ListenerFilterChainFactoryBuilder::buildFilterChain() [0x5583354726ee][2021-08-09 18:32:23.095][61844][critical][backtrace] [./source/server/backtrace.h:96] #22: Envoy::Server::FilterChainManagerImpl::addFilterChains() [0x55833549d5e3]
[2021-08-09 18:32:23.130][61844][critical][backtrace] [./source/server/backtrace.h:96] #23: Envoy::Server::ListenerImpl::buildFilterChains() [0x55833544f87b]
[2021-08-09 18:32:23.166][61844][critical][backtrace] [./source/server/backtrace.h:96] #24: Envoy::Server::ListenerImpl::ListenerImpl() [0x55833544d010]
[2021-08-09 18:32:23.202][61844][critical][backtrace] [./source/server/backtrace.h:96] #25: std::make_unique<>() [0x55833547cd68]
[2021-08-09 18:32:23.238][61844][critical][backtrace] [./source/server/backtrace.h:96] #26: Envoy::Server::ListenerManagerImpl::addOrUpdateListenerInternal() [0x55833546ba2e]
[2021-08-09 18:32:23.273][61844][critical][backtrace] [./source/server/backtrace.h:96] #27: Envoy::Server::ListenerManagerImpl::addOrUpdateListener() [0x55833546a853]
[2021-08-09 18:32:23.308][61844][critical][backtrace] [./source/server/backtrace.h:96] #28: Envoy::Server::Configuration::MainImpl::initialize() [0x55833550396b]
[2021-08-09 18:32:23.343][61844][critical][backtrace] [./source/server/backtrace.h:96] #29: Envoy::Server::ValidationInstance::initialize() [0x558334d577a7]
[2021-08-09 18:32:23.378][61844][critical][backtrace] [./source/server/backtrace.h:96] #30: Envoy::Server::ValidationInstance::ValidationInstance() [0x558334d56930]
[2021-08-09 18:32:23.413][61844][critical][backtrace] [./source/server/backtrace.h:96] #31: Envoy::Server::validateConfig() [0x558334d55e50]
[2021-08-09 18:32:23.447][61844][critical][backtrace] [./source/server/backtrace.h:96] #32: Envoy::MainCommonBase::run() [0x5583332d22c2]
[2021-08-09 18:32:23.482][61844][critical][backtrace] [./source/server/backtrace.h:96] #33: Envoy::MainCommon::run() [0x5583332d982a]
[2021-08-09 18:32:23.516][61844][critical][backtrace] [./source/server/backtrace.h:96] #34: Envoy::MainCommon::main() [0x5583332d3257]
[2021-08-09 18:32:23.550][61844][critical][backtrace] [./source/server/backtrace.h:96] #35: main [0x558333284c1a]
[2021-08-09 18:32:23.551][61844][critical][backtrace] [./source/server/backtrace.h:96] #36: __libc_start_main [0x7f2a8dcefbf7]
Aborted
```

**Comment by ggreenway** [comment] 2021-08-09 18:34
This was fixed in #17499 . We could consider backporting the fix.

**Comment by ggreenway** [comment] 2021-08-09 18:35
Closing, since the issue is fixed.

**Closed by ggreenway** 2021-08-09 18:35 UTC
Labels: bug

**Comment by blevz** [comment] 2021-08-09 19:15
Can we keep this open until a version post 1.19.0 is available that has fixed this regression?

**Comment by ggreenway** [comment] 2021-08-09 19:50
We generally close issues when they are fixed in `main`, not when a release with the fix is made. We don't have a good way to mark a release as fixing issues, so if we left it open it would probably never be properly closed.

**Comment by blevz** [comment] 2021-08-09 19:55
Gotcha, any advice on what to do in the interim.  We cannot upgrade to v1.19.0 because the regression breaks our integration tests (which --validate some of our generated configs).  Are we just stuck waiting for 1.20.0 or a backport to v1.19.1?

**Comment by ggreenway** [comment] 2021-08-09 20:04
We'll backport this. If/when there's a 1.19.1, this will be included.

**Comment by ggreenway** [comment] 2021-08-10 16:49
Backport PR: #17643
