### ISSUE TITLE
x-forwarded-proto gets overwritten when use_remote_address=true

### ISSUE THREAD

**Issue by 5long** [envoyproxy/envoy#4496] opened 2018-09-21 12:34 UTC
**Bug Template**

*Title*: *x-forwarded-proto gets overwritten when use_remote_address=true*

*Description*:
When Envoy is deployed behind a trusted edge load balancer (in my case, it's provided by cloud vendor Aliyun.com), and correspondingly set `xff_num_trusted_hops` greater than 0, it should forward header `x-forwarded-proto` from downstream to upstream without modification. Even with `use_remote_address` set to true.

*Repro steps*:

See: https://github.com/5long/envoy-forwarded-proto with a working Docker Stack config to reproduce it.

*Config*:
It's included in the git repo above.

**Comment by htuch** [comment] 2018-09-21 17:33
@mpuncel @mattklein123 can you folks take a look at this? I don't think this is a dupe of https://github.com/envoyproxy/envoy/issues/4383, but it seems another case of confusing XFF semantics.

**Comment by mattklein123** [comment] 2018-09-21 17:58
Yes this makes sense to me. cc @brian-pane also.

**Comment by Deepak275** [comment] 2019-02-07 05:32
I am also facing the same issue. Here is our scenario, we have a haproxy load-balancer, which does the  https offloading and append **X-FORWARDED-PROTO** *https*, and forward it to contour ingress which has envoy configured, it is setting up **X-FORWARDED-PROTO** *http*.  I get to know when i did the ngrep on the pod

**Comment by htuch** [comment] 2019-02-07 17:23
I think https://github.com/envoyproxy/envoy/issues/5836 is also related.

**Comment by Deepak275** [comment] 2019-02-10 12:15
here is to reporduce to [https://github.com/5long/envoy-forwarded-proto](envoy x-forwarded-proto header overwrite)

**Comment by Deepak275** [comment] 2019-02-10 12:18
Here is the link to reproduce the bug [X-forwarded-proto overwrite issue](https://github.com/5long/envoy-forwarded-proto)

**Comment by justinfiore** [comment] 2019-03-12 15:34
I am also experiencing this behavior when using Ambassador `0.51.1` with `use_remote_address=true`

**Closed** 2019-08-22 19:07 UTC
Labels: bug, help wanted
