### ISSUE TITLE
http2: Should all cluster members be considered healthy at all times?

### ISSUE THREAD

**Issue by tommyulfsparre** [envoyproxy/envoy#2884] opened 2018-03-23 13:30 UTC
Is there a reason why Envoy will select a connection for load balancing even if it can't establish a TCP connection to the upstream? 
(I know this behavior is documented in the cluster manger docs under health checks, but curious)

With a cluster definition using http2 (gRPC in our case):
```
   {
    "name": "out.grpc-server.default.svc.cluster.local|grpc",
    "service_name": "grpc-server.default.svc.cluster.local|grpc",
    "connect_timeout_ms": 1000,
    "type": "sds",
    "lb_type": "round_robin",
    "ssl_context": {
     "cert_chain_file": "/etc/certs/cert-chain.pem",
     "private_key_file": "/etc/certs/key.pem",
     "ca_cert_file": "/etc/certs/root-cert.pem",
     "verify_subject_alt_name": [
      "spiffe://cluster.local/ns/default/sa/default"
     ]
    },
    "features": "http2"
   },
```
and we add a "bad/non-existing" hosts as a cluster member we get errors when Envoy tries to send request over that connection.

**Comment by zuercher** [comment] 2018-03-23 17:16
Envoy assumes [eventually consistent service discovery](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/service_discovery#on-eventually-consistent-service-discovery), so in the absence of health checks, this is the expected behavior.

Even if you enable health checks, you probably want to consider adding a [retry policy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=retrypolicy#route-routeaction-retrypolicy) on connect-failure.

**Comment by tommyulfsparre** [comment] 2018-03-23 18:46
@zuercher Sure, but is it the right behaviour? It seems wasteful to send a request on connection Envoy could know isn't in a connected/ready state (even if it fail-fast). 

Using gRPC without Envoy and plugging in an eventually consistent resolver doesn't have this behaviour, right?

**Comment by tommyulfsparre** [comment] 2018-03-25 20:46
@mattklein123 Ack and yes, this was more a question if this “optimization” would be worth adding.
Wouldn’t a connection state change react faster, in some cases, than health checks and also not incur the added latency of retries? Not implying this should be use instead of health check but in conjunction as another signal.

This might not be trivial to add/Worth it so feel free to close this.

**Comment by mattklein123** [comment] 2018-03-26 16:37
@tommyulfsparre yes in a perfect world, we would potentially refactor things such that a connection is not actually bound to until we know it's connected. However, there are cases in which the kernel will say the a connection is "connected" and then immediately fail it, so I'm not sure that will even really work in all cases. 

I'm going to go ahead and close this for now, but we can definitely reopen if it looks like this is causing production problems and a targeted fix would be worthwhile.

**Closed by mattklein123** 2018-03-26 16:37 UTC
Labels: question
