### ISSUE TITLE
Buld fails on FreeBSD: please do not assume that it always builds from the git repository, tarballs should be ok too

### ISSUE THREAD

**Issue by yurivict** [envoyproxy/envoy#7370] opened 2019-06-22 23:10 UTC
```
===>  Building for envoyproxy-v1.10.0.493
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/usr/ports/www/envoyproxy/work/envoy-vv1.10.0-493-gd0cefa7f0/tools/bazel.rc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //source/exe:envoy-static (380 packages loaded, 18733 targets configured).
INFO: Found 1 target...
ERROR: Process exited with status 1: Process exited with status 1
fatal: not a git repository (or any of the parent directories): .git
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 71.695s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
*** Error code 1
```

**Comment by mattklein123** [comment] 2019-06-23 20:42
This is a duplicate of https://github.com/envoyproxy/envoy/issues/2181, let's track there.

**Closed by mattklein123** 2019-06-23 20:42 UTC
