### ISSUE TITLE
additional configuration for determining internal address

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#19844] opened 2022-02-07 09:42 UTC
*Title*: *additional configuration for determining internal address*

*Description*:
Currently Envoy determines whether the address is an internal address or not based on RFC 1918. However in some of our use cases we need [RFC 6598](https://datatracker.ietf.org/doc/html/rfc6598). It would also be useful to allow internal subnets to be configurable.

The feature request is to enhance [Internal Address Config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-internaladdressconfig) and add those two parameters.

**Comment by ramaraochavali** [comment] 2022-02-07 09:42
@snowp @mattklein123 WDYT?

**Comment by mattklein123** [comment] 2022-02-07 15:59
Sure makes sense to me.

**Comment by ggreenway** [comment] 2022-02-14 22:58
I think it would make the most sense to allow configuring a list of CIDRs to be considered internal, and if unset, defaults to the current behavior of RFC 1918.

Related to (or maybe a dupe of) #2590.

**Closed** 2022-04-04 17:54 UTC
Labels: help wanted, area/configuration
