### ISSUE TITLE
StatsThreadLocalStoreTestNoFixture.MemoryWithoutTlsFakeSymbolTable flaky?

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#8282] opened 2019-09-18 15:23 UTC
Josh, could you take a look?  I don't think this failure is related to the PR it failed on ( https://github.com/envoyproxy/envoy/pull/8281)  so I think it's a random flake.

https://circleci.com/gh/envoyproxy/envoy/278531?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

[ RUN      ] StatsThreadLocalStoreTestNoFixture.MemoryWithoutTlsFakeSymbolTable
test/common/stats/thread_local_store_test.cc:898: Failure
Expected equality of these values:
  memory_test.consumedBytes()
    Which is: 15268288
  15268336
Stack trace:
  0x528d66: Envoy::Stats::StatsThreadLocalStoreTestNoFixture_MemoryWithoutTlsFakeSymbolTable_Test::TestBody()
  0xa94ea4: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0xa94dcc: testing::Test::Run()
  0xa95e1f: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] StatsThreadLocalStoreTestNoFixture.MemoryWithoutTlsFakeSymbolTable (787 ms)

**Comment by zuercher** [comment] 2019-09-18 20:17
Saw this on a docs-only PR as well (#8285).

**Comment by jmarantz** [comment] 2019-09-18 20:22
It had been stable I think since June.  I'd love to know what possible sources of non-determinism there might be that could affect this fairly narrow test.

I'm imagining it might be something else recent that got checked in.

**Comment by jmarantz** [comment] 2019-09-18 20:24
and in fact the unexpected behavior is that it consumed 336-288 = 48 *fewer* bytes than the golden value.

**Comment by jmarantz** [comment] 2019-09-18 21:03
I have a theory; there are actually real threads happening in this test, although they have nothing to do with the test.

TestRunner::RunTests() instantiates ProcessWide which runs grpc_init() which ultimately calls pthread_create(). In fact it create 3 threads. I suspect there's some allocation going on in there in parallel to the test body, adding some (rare) flakiness.

**Comment by jmarantz** [comment] 2019-09-19 01:31
Possible cause: https://github.com/envoyproxy/envoy/pull/8196 -- maybe that new version of gRPC made threads active in the background, which is obviously harmful to memory tests.

**Comment by jmarantz** [comment] 2019-09-19 01:45
Running
```
bazel test --cache_test_results=no --compilation_mode=opt \
  --test_env=ENVOY_MEMORY_TEST_EXACT=true \ 
  --cache_test_results=no //test/common/stats:thread_local_store_test \
  --runs_per_test=100
```
fails 7/100 times. If I comment out the calls to `grpc_init()` and `grpc_shutdown()` in `source/exe/process_wide.cc`, I see 0 failures.

**Comment by jmarantz** [comment] 2019-09-19 01:50
@htuch WDYT about calling grpc_init/grpc_shutdown from the ctor/dtor of GoogleAsyncRequestImpl ?

That would keep it more constrained and avoid having it run threads over the top of unrelated tests?

**Closed** 2019-09-23 18:50 UTC
Labels: test flakes
