### ISSUE TITLE
multiplexed_integration_test flaky

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#18889] opened 2021-11-03 20:16 UTC
IpVersions/Http2IntegrationTest.InvalidTrailers/IPv4_Http2Downstream_HttpUpstream is very flaky 

[ RUN      ] IpVersions/Http2IntegrationTest.InvalidTrailers/IPv4_Http2Downstream_HttpUpstream
[2021-11-03 19:41:13.549][14][critical][assert] [test/integration/autonomous_upstream.cc:35] assert failure: complete(). Details: Found that end_stream is not true
[2021-11-03 19:41:13.549][14][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x50e8d0000000e
[2021-11-03 19:41:13.549][14][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2021-11-03 19:41:13.549][14][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.21.0-dev/test/DEBUG/BoringSSL
[2021-11-03 19:41:13.620][14][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x4ca5469]
[2021-11-03 19:41:13.620][14][critical][backtrace] [./source/server/backtrace.h:96] #1: __restore_rt [0x7fc236e038e0]
[2021-11-03 19:41:13.687][14][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::AutonomousStream::~AutonomousStream() [0x29d1793]
[2021-11-03 19:41:13.740][14][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::AutonomousStream::~AutonomousStream() [0x29d180c]
[2021-11-03 19:41:13.791][14][critical][backtrace] [./source/server/backtrace.h:96] #4: std::default_delete<>::operator()() [0x290ac1f]
[2021-11-03 19:41:13.874][14][critical][backtrace] [./source/server/backtrace.h:96] #5: std::unique_ptr<>::~unique_ptr() [0x2825e0d]
[2021-11-03 19:41:13.933][14][critical][backtrace] [./source/server/backtrace.h:96] #6: std::_Destroy<>() [0x2910655]
[2021-11-03 19:41:13.994][14][critical][backtrace] [./source/server/backtrace.h:96] #7: std::_Destroy_aux<>::__destroy<>() [0x291061f]
[2021-11-03 19:41:14.051][14][critical][backtrace] [./source/server/backtrace.h:96] #8: std::_Destroy<>() [0x29105dd]
[2021-11-03 19:41:14.116][14][critical][backtrace] [./source/server/backtrace.h:96] #9: std::_Destroy<>() [0x2910541]
[2021-11-03 19:41:14.187][14][critical][backtrace] [./source/server/backtrace.h:96] #10: std::vector<>::~vector() [0x28285bb]
[2021-11-03 19:41:14.256][14][critical][backtrace] [./source/server/backtrace.h:96] #11: Envoy::AutonomousHttpConnection::~AutonomousHttpConnection() [0x29dc427]
[2021-11-03 19:41:14.340][14][critical][backtrace] [./source/server/backtrace.h:96] #12: Envoy::AutonomousHttpConnection::~AutonomousHttpConnection() [0x29d6763]
[2021-11-03 19:41:14.436][14][critical][backtrace] [./source/server/backtrace.h:96] #13: Envoy::AutonomousHttpConnection::~AutonomousHttpConnection() [0x29d679c]
[2021-11-03 19:41:14.514][14][critical][backtrace] [./source/server/backtrace.h:96] #14: std::default_delete<>::operator()() [0x29de86f]
[2021-11-03 19:41:14.569][14][critical][backtrace] [./source/server/backtrace.h:96] #15: std::unique_ptr<>::~unique_ptr() [0x29d504d]
[2021-11-03 19:41:14.660][14][critical][backtrace] [./source/server/backtrace.h:96] #16: std::_Destroy<>() [0x29dcd35]
[2021-11-03 19:41:14.726][14][critical][backtrace] [./source/server/backtrace.h:96] #17: std::_Destroy_aux<>::__destroy<>() [0x29dccff]
[2021-11-03 19:41:14.785][14][critical][backtrace] [./source/server/backtrace.h:96] #18: std::_Destroy<>() [0x29dccbd]
[2021-11-03 19:41:14.851][14][critical][backtrace] [./source/server/backtrace.h:96] #19: std::_Destroy<>() [0x29dcc21]
[2021-11-03 19:41:14.920][14][critical][backtrace] [./source/server/backtrace.h:96] #20: std::vector<>::_M_erase_at_end() [0x29dd822]
[2021-11-03 19:41:14.983][14][critical][backtrace] [./source/server/backtrace.h:96] #21: std::vector<>::clear() [0x29d4bcb]
[2021-11-03 19:41:15.043][14][critical][backtrace] [./source/server/backtrace.h:96] #22: Envoy::AutonomousUpstream::~AutonomousUpstream() [0x29d301c]
[2021-11-03 19:41:15.118][14][critical][backtrace] [./source/server/backtrace.h:96] #23: Envoy::AutonomousUpstream::~AutonomousUpstream() [0x29d318c]
[2021-11-03 19:41:15.192][14][critical][backtrace] [./source/server/backtrace.h:96] #24: std::default_delete<>::operator()() [0x28a20af]
[2021-11-03 19:41:15.260][14][critical][backtrace] [./source/server/backtrace.h:96] #25: std::unique_ptr<>::~unique_ptr() [0x28a103d]
[2021-11-03 19:41:15.330][14][critical][backtrace] [./source/server/backtrace.h:96] #26: std::_Destroy<>() [0x2958d75]
[2021-11-03 19:41:15.402][14][critical][backtrace] [./source/server/backtrace.h:96] #27: std::_Destroy_aux<>::__destroy<>() [0x2958d3f]
[2021-11-03 19:41:15.473][14][critical][backtrace] [./source/server/backtrace.h:96] #28: std::_Destroy<>() [0x2958cfd]
[2021-11-03 19:41:15.543][14][critical][backtrace] [./source/server/backtrace.h:96] #29: std::_Destroy<>() [0x2958c71]
[2021-11-03 19:41:15.612][14][critical][backtrace] [./source/server/backtrace.h:96] #30: std::vector<>::~vector() [0x295879b]
[2021-11-03 19:41:15.674][14][critical][backtrace] [./source/server/backtrace.h:96] #31: Envoy::BaseIntegrationTest::~BaseIntegrationTest() [0x2952a39]
[2021-11-03 19:41:15.740][14][critical][backtrace] [./source/server/backtrace.h:96] #32: Envoy::HttpIntegrationTest::~HttpIntegrationTest() [0x29243e1]

Repro:
$ bazel test test/integration:multiplexed_integration_test --test_filter="*InvalidTrailers/IPv4_Http2Downstream_HttpUpstream" --runs_per_test=100

This also fails under coverage CI.

**Comment by ggreenway** [comment] 2021-11-03 21:03
I think this is a duplicate of #18881. Please re-open if this is incorrect.

**Closed by ggreenway** 2021-11-03 21:03 UTC
Labels: bug, triage
