### ISSUE TITLE
Requests and HealthCheck Metrics by Endpoint

### ISSUE THREAD

**Issue by marcosmariano** [envoyproxy/envoy#30432] opened 2023-10-23 17:49 UTC
*Title*: *Requests and HealthCheck Metrics by Endpoint (host)*

*Description*:
Nowadays I'm having the following problem, I'm applying the Cell Based Architecture using Envoy. 
So the Shards are the Clusters and the Cells of each shard are the Endpoints.

Now I need to metric the cell requests and health checks, so I need metrics by Envoy endpoints.

Do you have any predictions on when we will have this feature?

[optional *Relevant Links*:]
>[Cell-Based Architecture.](https://nordicapis.com/what-is-cell-based-architecture/#:~:text=Cell%2Dbased%20architecture%20is%20built,separate%20entities%20from%20other%20cells.)

**Comment by ggreenway** [comment] 2023-10-23 18:34
This is a duplicate of #21685

**Closed by ggreenway** 2023-10-23 18:34 UTC
Labels: triage
