### ISSUE TITLE
envoy grpc_transcoder cannot call POST method

### ISSUE THREAD

**Issue by syukur91** [envoyproxy/envoy#1590] opened 2017-09-04 05:04 UTC
So, I created the proto file which can send request with POST method using google.api.http option like below

```
syntax = "proto3";

package soapv004;
import "annotations.proto";

service Soapv004 {
    rpc CurrencyCall (CurrencyRequest) returns (CurrencyResponse) {
        option (google.api.http) = {
            post: "/soapv004/v1/CurrencyCall"
            body: "*"
        };
    }
}

message CurrencyRequest {
     string from_currency = 1;
     string to_currency = 2;
}

message CurrencyResponse {
     double conversion_rate_result = 1;
}

```
and I created descriptor file for this proto as well, and envoy can load everything just fine. But when I call it it has no response and the log said 404. But route is fine I think

```
{
    "virtual_hosts": [
        {
            "domains": [
                "*"
            ],
            "routes": [
                {
                    "timeout_ms": 0,
                    "prefix": "/soapv004/v1/CurrencyCall",
                    "headers": [
                        {
                            "name": "content-type",
                            "value": "application/grpc"
                        }
                    ],
                    "cluster": "grpc1"
                }
            ],
            "name": "grpc_service"
        }
    ]
}
```
and here's envoy access log
```
[2017-09-04T04:54:20.929Z] "POST /soapv004.Soapv004/CurrencyCall HTTP/1.1" 404 NR 0 0 0 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" "338ee060-ac40-40e0-8e69-33d15754ed49" "localhost" "-"
```
Is it any additional configuration to allow POST method? Because GET method have no problem so far.

Thank's in advance

**Comment by mattklein123** [comment] 2017-09-04 17:33
@lizan ^

**Comment by lizan** [comment] 2017-09-04 19:18
@syukur91 the route config is the cause, you should always specify a gRPC prefix for routes, not HTTP binding.

Changing the prefix in envoy config to `/soapv004.Soapv004/CurrencyCall` should work.

**Comment by mattklein123** [comment] 2017-09-04 21:23
@lizan can we add some more specific docs/examples to https://lyft.github.io/envoy/docs/configuration/http_filters/grpc_json_transcoder_filter.html ?

**Comment by syukur91** [comment] 2017-09-05 01:02
@lizan so the http binding in google option is useless and can't be used anymore? I think the http binding in google option would be human readable. And I saw in this document https://grpc.io/blog/coreos that you can specify url for http binding

**Comment by lizan** [comment] 2017-09-05 01:37
@syukur91 the http binding in google option does work, but the routing happens after the filter convert the path according to the http binding, so the prefix in your route config should be gRPC one, not before the conversion.

@mattklein123 sure.

**Comment by syukur91** [comment] 2017-09-05 04:05
@lizan It works when I set in my local, but when I try in my remote machine and using TLS and have specific domain in each route it doesn't works.

**Comment by lizan** [comment] 2017-09-05 07:41
@syukur91 Can you elaborate your usecase on your remote machine, including a full config? If you want to share it to me privately, find me on gitter.

**Comment by mattklein123** [comment] 2017-10-24 00:12
Closing this out for now. Please reopen if there are further questions.

**Closed by mattklein123** 2017-10-24 00:12 UTC
Labels: question
