### ISSUE TITLE
Generate document for proto service

### ISSUE THREAD

**Issue by silentdai** [envoyproxy/envoy#7030] opened 2019-05-21 22:35 UTC
*Description*:
> proto file contains both `message` and `service`. Currently only the comment associated with `message` or `field` in the `message` is generated.

- example of service and message
```
$ egrep -B 2 "^message|^service" api/envoy/api/v2/cds.proto |head -10

// Return list of all clusters this proxy will load balance to.
service ClusterDiscoveryService {
--
// Configuration for a single upstream cluster.
// [#comment:next free field: 39]
message Cluster {
--
// An extensible structure containing the address Envoy should bind to when
// establishing upstream connections.
```

- message doc

```
$ grep "An extensible" generated/ -rn
generated/rst/api-v2/api/v2/cds.proto.rst:1072:An extensible structure containing the address Envoy should bind to when
generated/docs/api-v2/api/v2/cds.proto.html:985:<p>An extensible structure containing the address Envoy should bind to when
generated/docs/_sources/api-v2/api/v2/cds.proto.rst.txt:1072:An extensible structure containing the address Envoy should bind to when
Binary file generated/docs/.doctrees/api-v2/api/v2/cds.proto.doctree matches
```
- service doc: none
```
$ grep "Return list of all clusters" generated/ -rn

```

**Comment by mattklein123** [comment] 2019-05-22 02:26
Thanks for tracking this down @silentdai. This is a duplicate of https://github.com/envoyproxy/envoy/issues/3091 so let's track there.

**Closed by mattklein123** 2019-05-22 02:26 UTC
