### ISSUE TITLE
Using Envoy to handle the static file or resources 

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#36954] opened 2024-11-02 13:29 UTC
*Description*:

Using Envoy to handle the static file or resources just like Nginx **without routing to any upstream service**.

Is this already supported by Envoy by some configuration ? Or i should add a new http filter to intercept the request and return static resources ?

**Comment by phlax** [comment] 2024-11-04 13:04
@wufanqqfsc this is a conversation that has gone on a long time

im gonna close this as a duplicate of https://github.com/envoyproxy/envoy/issues/378

Envoy does have some mechanisms for serving static content - eg by using direct responses (see eg https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/single-page-app).  I think you may also be able to hack the http caching system to effectively serve files. As it stands tho Envoy is not really usable as a file server, as great as that would be

**Closed by phlax** 2024-11-04 13:04 UTC
Labels: triage
