### ISSUE TITLE
logging: data race bug because spdlog formatters are not thread-safe

### ISSUE THREAD

**Issue by aschran** [envoyproxy/envoy#4977] opened 2018-11-06 21:38 UTC
logging: thread-safety bug in spdlog

*Description*:
spdlog's `pattern_formatter` is used in Envoy to format log output. This class is not thread-safe due to its use of cached precomputed values that are not protected by a mutex or thread-local. For example, see `last_log_secs_` and `cached_tm_` here:
https://github.com/gabime/spdlog/blob/v1.2.1/include/spdlog/details/pattern_formatter.h#L559

We need to either fix this upstream in spdlog or fork `pattern_formatter` into Envoy to make it thread-safe.

I opened this issue in spdlog as well, here:
https://github.com/gabime/spdlog/issues/897

**Comment by aschran** [comment] 2018-11-06 21:39
@htuch @qiannawang

**Comment by gabime** [comment] 2018-11-06 23:51
This is by design and certianly not athread safety bug. see https://github.com/gabime/spdlog/issues/897 for details.

**Comment by aschran** [comment] 2018-11-06 23:52
Yes, sorry for the title. It was not clear to us before that spdlog formatters are (by design) not thread-safe.

**Comment by aschran** [comment] 2018-11-06 23:55
Since gabime is not amenable to making `pattern_formatter` thread-safe in spdlog (see the linked issue), 
some other options for us to fix this:
- add a lock around all accesses to `DelegatingLogSink::formatter_`
- fork the spdlog `pattern_formatter` into Envoy and make it thread-safe using thread locals
- implement our own, much smaller thread-safe formatter that just hard codes our pattern and don't allow other patterns
- other ideas welcome

Thoughts? Hoping for some guidance before I begin implementing one of these.

**Comment by htuch** [comment] 2018-11-07 00:04
I think just lock around `DelegatingLogSink::formatter_`. @mattklein123 @jmarantz WDYT?

**Comment by gabime** [comment] 2018-11-07 00:08
Why not  just make the sink thread safe? The recommended way in spdlog is to inherit from ```spdlog::base_sink<std::mutex>``` which will make the sink thread safe for you.
See the docs (https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink)

**Comment by mattklein123** [comment] 2018-11-07 01:48
> Why not just make the sink thread safe? The recommended way in spdlog is to inherit from spdlog::base_sink<std::mutex> which will make the sink thread safe for you.
See the docs (https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink)

TBH I don't remember the history here. I think we used to derive from basic_sink with our own lockable class to wrap the shared process mutex, but then I think that all changed when we moved to the delegatedSink stuff. I agree it would be better if we could have spdlog do lock management. @jmarantz thoughts on how to do this with the delegatedSink stuff?

**Comment by jmarantz** [comment] 2018-11-07 02:13
It wasn't my intention to drop thread-safety when I added DelegatedSink. In any case I'll take a look. @gabime I probably should've consulted you as DelegatedSink was, in the first place, probably not what you envisioned about how people should extend spdlog; you might have some suggestions about how that could've been done more cleanly.

In the meantime, @aschran , is there a way to repro this problem?  E.g. can you write a test that gets a tsan warning given the current state? I'd like to see something broken before I fix it if possible.

**Comment by jmarantz** [comment] 2018-11-07 02:18
Also @gabime -- was the cached precomputed values a relatively new addition to spdlog? I'm wondering why I haven't seen this thread safety issue before.

**Comment by aschran** [comment] 2018-11-07 02:19
@jmarantz we have a repro of TSAN errors on this code with some internal Google tests. @htuch said he was going to work on repro-ing in the Envoy tests.

**Comment by jmarantz** [comment] 2018-11-07 02:35
BTW there's already a lock, we just are not taking it in DelegatingLogSink::log(). We were taking protecting only StderrSinkDelegate (due to mutliple threads accessing std::cerr) and not the other SinkDelegates with the lock.

Maybe it would be sufficient, though to protect just the call to formatter_->format(), in addition to cerr?

**Comment by aschran** [comment] 2018-11-07 02:42
I think that that would be sufficient to fix this race, yes. (Just protecting the call to format.)

**Comment by jmarantz** [comment] 2018-11-07 03:58
Yeah -- locking around the formatter appears to solve problem, per #4982. @gabime locking around the sink is too broad IMO; would prefer not to lock around I/O when not needed.

It seems like putting formatter in thread-local storage would offer better performance, but I can imagine that if we get into contention-trouble in spdlog we'd (a) probably be logging too much and (b) we should be able to see it in admin /contention now.

**Comment by qiannawang** [comment] 2018-11-07 07:09
@jmarantz is admin/contention a new feature just added in Envoy? I have not seen the interface from its admin/ page. Will be nice to have this feature.

**Comment by gabime** [comment] 2018-11-07 09:03
> was the cached precomputed values a relatively new addition to spdlog ?

@jmarantz It was added about 5 months ago

> locking around the sink is too broad IMO; would prefer not to lock around I/O when not needed

@jmarantz Please note that sinks have 4 methods that must be protected from concurrent access (log(..), flush(..), set_pattern(..), set_formatter(..)), so if you don't use ```base_sink<std::mutex>``` you must take care of them as well.

A quick glance on the code reveals for example that  [DelegatedLogSink::set_pattern](https://github.com/envoyproxy/envoy/blob/f71a883b557a18cc418d4103b2f07a6780fc6576/source/common/common/logger.h#L153) is clearly not thread safe, and that ```DelegatedLogSink::flush``` relies on the underlying  ```sink_->flush()``` to be thread safe.

**Comment by jmarantz** [comment] 2018-11-07 13:20
@gabime that makes sense; I think we probably hadn't upgraded spdlog versions since then.

#4982 protects set_pattern by protecting set_formatter. log() and flush() are protected in our wrapper for std::cerr, and don't need to be for our file-based loggers.

It may be better to have the formatter be thread-local, which wouldn't harm single-threaded performance. But it's worth it IMO to see whether #4982 adds contention in any real scenario, and mutexing it is obviously simpler.

@qiannawang admin '/contention' support was merged yesterday in https://github.com/envoyproxy/envoy/pull/4750 though you need to turn it on with a command-line flag.

**Closed** 2018-11-07 17:49 UTC
Labels: bug

**Comment by jmarantz** [comment] 2018-11-07 22:41
@gabime great catch. PR coming. Thanks.

**Comment by jmarantz** [comment] 2018-11-07 23:01
@gabime https://github.com/envoyproxy/envoy/pull/4993

**Comment by gabime** [comment] 2018-11-08 10:28
@jmarantz btw2 is to consider using sodlog's async loggers. If used with single backing thread (the default), no locking is needed at all, and throughput would be stable even if some sink fails or delays (e.g. disk becomes slow). I think it might be important for a process like Envoy.
If the log queue becomes full, It can configured to drop oldest messages or block (see the [docs](https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging))
