### ISSUE TITLE
Segfault with envoy.lua plugin on OSX

### ISSUE THREAD

**Issue by robertpanzer** [envoyproxy/envoy#6373] opened 2019-03-25 17:11 UTC
*Title*: Running Envoy built with `-c opt` on OSX segfaults for me with the most simple Lua scripts

*Description*:
Envoy crashes with a SegFault on the first request.
The message I see looks like this:
```
bazel-bin/source/exe/envoy-static -c test-envoy.yaml                             
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:205] initializing epoch 0 (hot restart version=disabled)                     
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:207] statically linked extensions:                                           
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:209]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log      
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:212]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envo
y.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.filters.http
.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.l
ua,envoy.rate_limit,envoy.router,envoy.squash                                                                                                         
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:215]   filters.listener: envoy.listener.original_dst,envoy.listener.original_
src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector                                                                                        
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:218]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envo
y.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thr
ift_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy                                           
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:220]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hy
strix,envoy.statsd                                                                                                                                    
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:222]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.
zipkin                                                                                                                                                
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:225]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.trans
port_sockets.tap,raw_buffer,tls                                                                                                                       
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:228]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transpo
rt_sockets.tap,raw_buffer,tls                                                                                                                         
[2019-03-25 17:51:45.866][15267691][info][main] [source/server/server.cc:234] buffer implementation: old (libevent)                                   
[2019-03-25 17:51:45.870][15267691][warning][misc] [source/common/protobuf/utility.cc:173] Using deprecated option 'envoy.api.v2.Cluster.hosts' from f
ile cds.proto. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for detail
s.                                                                                                                                                    
[2019-03-25 17:51:45.871][15267691][info][main] [source/server/server.cc:281] admin address: 0.0.0.0:8001                                             
[2019-03-25 17:51:45.872][15267691][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)                                 
[2019-03-25 17:51:45.872][15267691][info][config] [source/server/configuration_impl.cc:56] loading 1 cluster(s)                                       
[2019-03-25 17:51:45.873][15267691][info][upstream] [source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized           
[2019-03-25 17:51:45.873][15267691][info][config] [source/server/configuration_impl.cc:60] loading 1 listener(s)                                     
[2019-03-25 17:51:45.876][15267691][info][config] [source/server/configuration_impl.cc:85] loading tracing configuration                             
[2019-03-25 17:51:45.876][15267691][info][config] [source/server/configuration_impl.cc:105] loading stats sink configuration                         
[2019-03-25 17:51:45.876][15267691][info][main] [source/server/server.cc:458] all clusters initialized. initializing init manager                    
[2019-03-25 17:51:45.876][15267691][info][config] [source/server/listener_manager_impl.cc:1008] all dependencies initialized. starting workers       
[2019-03-25 17:51:45.877][15267691][info][main] [source/server/server.cc:484] starting main dispatch loop                                            
[2019-03-25 17:51:56.089][15267707][critical][backtrace] [bazel-out/darwin-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:8$] Caught Segmentation fault: 11, suspect faulting address 0x0
[2019-03-25 17:51:56.089][15267707][critical][backtrace] [bazel-out/darwin-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:6$] Backtrace (use tools/stack_decode.py to get line numbers):
[1]    54176 segmentation fault  bazel-bin/source/exe/envoy-static -c
```

*Repro steps*:
Build Envoy on OSX like this:
```
bazel build //source/exe:envoy-static.stripped -c opt 
```

Then create the config below and start envoy with `bazel-bin/source/exe/envoy-static.stripped -c test-envoy.yaml`.

After that send a request with `curl localhost:8888`.

Envoy crashes for me on the first request.

I attached a debugger from Xcode and it seems to crash `StreamHandleWrapper::create` if I see that correctly:
```
envoy-static`Envoy::Extensions::Filters::Common::Lua::BaseLuaObject<Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper>::create<Envoy::Extensions::Filters::Common::Lua::Coroutine&, Envoy::Http::HeaderMap&, bool&, Envoy::Extensions::HttpFilters::Lua::Filter&, Envoy::Extensions::HttpFilters::Lua::FilterCallbacks&>:
    0x10a114770 <+0>:   pushq  %rbp
    0x10a114771 <+1>:   movq   %rsp, %rbp
    0x10a114774 <+4>:   pushq  %r15
    0x10a114776 <+6>:   pushq  %r14
    0x10a114778 <+8>:   pushq  %r13
    0x10a11477a <+10>:  pushq  %r12
    0x10a11477c <+12>:  pushq  %rbx
    0x10a11477d <+13>:  subq   $0x58, %rsp
    0x10a114781 <+17>:  movq   %r9, -0x48(%rbp)
    0x10a114785 <+21>:  movq   %r8, -0x40(%rbp)
    0x10a114789 <+25>:  movq   %rcx, %r14
    0x10a11478c <+28>:  movq   %rdx, -0x38(%rbp)
    0x10a114790 <+32>:  movq   %rsi, %r13
    0x10a114793 <+35>:  movq   %rdi, %rbx
    0x10a114796 <+38>:  movl   $0x120, %esi              ; imm = 0x120 
    0x10a11479b <+43>:  callq  0x10a135660               ; lua_newuserdata
    0x10a1147a0 <+48>:  movq   %rax, -0x30(%rbp)
    0x10a1147a4 <+52>:  leaq   0xb0c315(%rip), %rdx      ; typeinfo name for Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper
    0x10a1147ab <+59>:  movl   $0xffffd8f0, %esi         ; imm = 0xFFFFD8F0 
    0x10a1147b0 <+64>:  movq   %rbx, %rdi
    0x10a1147b3 <+67>:  callq  0x10a1358f0               ; lua_getfield
    0x10a1147b8 <+72>:  movl   $0xfffffffe, %esi         ; imm = 0xFFFFFFFE 
    0x10a1147bd <+77>:  movq   %rbx, %rdi
    0x10a1147c0 <+80>:  callq  0x10a136ad0               ; lua_setmetatable
    0x10a1147c5 <+85>:  movq   0xdceb8c(%rip), %r12      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1147cc <+92>:  movb   (%r12), %al
    0x10a1147d0 <+96>:  testb  %al, %al
    0x10a1147d2 <+98>:  je     0x10a114986               ; <+534>
    0x10a1147d8 <+104>: movq   0xdd6e29(%rip), %r15      ; (void *)0x000000010af8f310: Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1147df <+111>: movq   (%r15), %rax
    0x10a1147e2 <+114>: movl   0x38(%rax), %eax
    0x10a1147e5 <+117>: testl  %eax, %eax
    0x10a1147e7 <+119>: jg     0x10a114849               ; <+217>
    0x10a1147e9 <+121>: movb   (%r12), %al
    0x10a1147ed <+125>: testb  %al, %al
    0x10a1147ef <+127>: je     0x10a1149bf               ; <+591>
    0x10a1147f5 <+133>: leaq   0xb0c2c4(%rip), %rax      ; typeinfo name for Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper
    0x10a1147fc <+140>: movq   %rax, -0x50(%rbp)
    0x10a114800 <+144>: leaq   0xd143d1(%rip), %rax      ; ""
    0x10a114807 <+151>: movq   %rax, -0x68(%rbp)
    0x10a11480b <+155>: movq   (%r15), %rdi
    0x10a11480e <+158>: movl   $0x0, -0x60(%rbp)
    0x10a114815 <+165>: movq   %rax, -0x58(%rbp)
    0x10a114819 <+169>: movq   -0x58(%rbp), %rax
    0x10a11481d <+173>: movq   %rax, 0x10(%rsp)
    0x10a114822 <+178>: movq   -0x68(%rbp), %rax
    0x10a114826 <+182>: movq   -0x60(%rbp), %rcx
    0x10a11482a <+186>: movq   %rcx, 0x8(%rsp)
    0x10a11482f <+191>: movq   %rax, (%rsp)
    0x10a114833 <+195>: leaq   0xd0fab6(%rip), %rdx      ; "[bazel-out/darwin-opt/bin/source/extensions/filters/common/lua/_virtual_includes/lua_lib/extensions/filters/common/lua/lua.h:100] creating {} at {}"
    0x10a11483a <+202>: leaq   -0x50(%rbp), %rcx
    0x10a11483e <+206>: leaq   -0x30(%rbp), %r8
    0x10a114842 <+210>: xorl   %esi, %esi
    0x10a114844 <+212>: callq  0x10a110270               ; void spdlog::logger::log<char const*, void*>(spdlog::source_loc, spdlog::level::level_enum, char const*, char const* const&, void* const&)
    0x10a114849 <+217>: movq   -0x30(%rbp), %rax
    0x10a11484d <+221>: movb   (%r14), %cl
    0x10a114850 <+224>: movb   $0x0, 0x8(%rax)
    0x10a114854 <+228>: leaq   0xde6e15(%rip), %rdx      ; vtable for Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper + 16
    0x10a11485b <+235>: movq   %rdx, (%rax)
    0x10a11485e <+238>: leaq   0xde6e4b(%rip), %rdx      ; vtable for Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper + 80
    0x10a114865 <+245>: movq   %rdx, 0x10(%rax)
    0x10a114869 <+249>: movq   %r13, 0x18(%rax)
    0x10a11486d <+253>: movq   -0x38(%rbp), %rdx
    0x10a114871 <+257>: movq   %rdx, 0x20(%rax)
    0x10a114875 <+261>: movb   %cl, 0x28(%rax)
    0x10a114878 <+264>: movw   $0x0, 0x29(%rax)
    0x10a11487e <+270>: movb   $0x0, 0x2b(%rax)
    0x10a114882 <+274>: movq   -0x40(%rbp), %rcx
    0x10a114886 <+278>: movq   %rcx, 0x30(%rax)
    0x10a11488a <+282>: movq   -0x48(%rbp), %rcx
    0x10a11488e <+286>: movq   %rcx, 0x38(%rax)
    0x10a114892 <+290>: xorps  %xmm0, %xmm0
->  0x10a114895 <+293>: movaps %xmm0, 0x40(%rax)
    0x10a114899 <+297>: movq   $0x0, 0x50(%rax)
    0x10a1148a1 <+305>: movl   $0xfffffffe, 0x58(%rax)   ; imm = 0xFFFFFFFE 
    0x10a1148a8 <+312>: movq   $0x0, 0x68(%rax)
    0x10a1148b0 <+320>: movq   $0x0, 0x60(%rax)
    0x10a1148b8 <+328>: movl   $0xfffffffe, 0x70(%rax)   ; imm = 0xFFFFFFFE 
    0x10a1148bf <+335>: movq   $0x0, 0x80(%rax)
    0x10a1148ca <+346>: movq   $0x0, 0x78(%rax)
    0x10a1148d2 <+354>: movl   $0xfffffffe, 0x88(%rax)   ; imm = 0xFFFFFFFE 
    0x10a1148dc <+364>: movq   $0x0, 0x98(%rax)
    0x10a1148e7 <+375>: movq   $0x0, 0x90(%rax)
    0x10a1148f2 <+386>: movl   $0xfffffffe, 0xa0(%rax)   ; imm = 0xFFFFFFFE 
    0x10a1148fc <+396>: movq   $0x0, 0xb0(%rax)
    0x10a114907 <+407>: movq   $0x0, 0xa8(%rax)
    0x10a114912 <+418>: movl   $0xfffffffe, 0xb8(%rax)   ; imm = 0xFFFFFFFE 
    0x10a11491c <+428>: movq   $0x0, 0xc8(%rax)
    0x10a114927 <+439>: movq   $0x0, 0xc0(%rax)
    0x10a114932 <+450>: movl   $0xfffffffe, 0xd0(%rax)   ; imm = 0xFFFFFFFE 
    0x10a11493c <+460>: movl   $0x0, 0xd8(%rax)
    0x10a114946 <+470>: leaq   0xde743b(%rip), %rcx      ; vtable for std::__1::__function::__func<Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper::StreamHandleWrapper(Envoy::Extensions::Filters::Common::Lua::Coroutine&, Envoy::Http::HeaderMap&, bool, Envoy::Extensions::HttpFilters::Lua::Filter&, Envoy::Extensions::HttpFilters::Lua::FilterCallbacks&)::$_0, std::__1::allocator<Envoy::Extensions::HttpFilters::Lua::StreamHandleWrapper::StreamHandleWrapper(Envoy::Extensions::Filters::Common::Lua::Coroutine&, Envoy::Http::HeaderMap&, bool, Envoy::Extensions::HttpFilters::Lua::Filter&, Envoy::Extensions::HttpFilters::Lua::FilterCallbacks&)::$_0>, void ()> + 16
    0x10a11494d <+477>: movq   %rcx, 0xe0(%rax)
    0x10a114954 <+484>: movq   %rax, 0xe8(%rax)
    0x10a11495b <+491>: leaq   0xe0(%rax), %rcx
    0x10a114962 <+498>: movq   %rcx, 0x100(%rax)
    0x10a114969 <+505>: movq   $0x0, 0x110(%rax)
    0x10a114974 <+516>: movq   %rbx, %rdx
    0x10a114977 <+519>: addq   $0x58, %rsp
    0x10a11497b <+523>: popq   %rbx
    0x10a11497c <+524>: popq   %r12
    0x10a11497e <+526>: popq   %r13
    0x10a114980 <+528>: popq   %r14
    0x10a114982 <+530>: popq   %r15
    0x10a114984 <+532>: popq   %rbp
    0x10a114985 <+533>: retq   
    0x10a114986 <+534>: movq   0xdce9cb(%rip), %rdi      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a11498d <+541>: callq  0x10ac0b774               ; symbol stub for: __cxa_guard_acquire
    0x10a114992 <+546>: testl  %eax, %eax
    0x10a114994 <+548>: je     0x10a1147d8               ; <+104>
    0x10a11499a <+554>: movl   $0x10, %edi
    0x10a11499f <+559>: callq  0x10abb1210               ; Envoy::Logger::Registry::getLog(Envoy::Logger::Id)
    0x10a1149a4 <+564>: movq   0xdd6c5d(%rip), %rcx      ; (void *)0x000000010af8f310: Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1149ab <+571>: movq   %rax, (%rcx)
    0x10a1149ae <+574>: movq   0xdce9a3(%rip), %rdi      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1149b5 <+581>: callq  0x10ac0b77a               ; symbol stub for: __cxa_guard_release
    0x10a1149ba <+586>: jmp    0x10a1147d8               ; <+104>
    0x10a1149bf <+591>: movq   0xdce992(%rip), %rdi      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1149c6 <+598>: callq  0x10ac0b774               ; symbol stub for: __cxa_guard_acquire
    0x10a1149cb <+603>: testl  %eax, %eax
    0x10a1149cd <+605>: je     0x10a1147f5               ; <+133>
    0x10a1149d3 <+611>: movl   $0x10, %edi
    0x10a1149d8 <+616>: callq  0x10abb1210               ; Envoy::Logger::Registry::getLog(Envoy::Logger::Id)
    0x10a1149dd <+621>: movq   %rax, (%r15)
    0x10a1149e0 <+624>: movq   0xdce971(%rip), %rdi      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1149e7 <+631>: callq  0x10ac0b77a               ; symbol stub for: __cxa_guard_release
    0x10a1149ec <+636>: jmp    0x10a1147f5               ; <+133>
    0x10a1149f1 <+641>: jmp    0x10a1149f3               ; <+643>
    0x10a1149f3 <+643>: movq   %rax, %rbx
    0x10a1149f6 <+646>: movq   0xdce95b(%rip), %rdi      ; (void *)0x000000010af8f318: guard variable for Envoy::Logger::Loggable<(Envoy::Logger::Id)16>::__log_do_not_use_read_comment()::instance
    0x10a1149fd <+653>: callq  0x10ac0b76e               ; symbol stub for: __cxa_guard_abort
    0x10a114a02 <+658>: movq   %rbx, %rdi
    0x10a114a05 <+661>: callq  0x10ac0b1e6               ; symbol stub for: _Unwind_Resume
    0x10a114a0a <+666>: ud2    
    0x10a114a0c <+668>: nopl   (%rax)
```
The line with the arrow at the beginning shows where EXC_BAD_ACCESS occurs.

*Config*:
```yaml
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8888
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route: 
                  cluster: web_service
          http_filters:
          - name: envoy.lua
            config:
              inline_code: |
                function envoy_on_request(request_handle)
                    print("XXXX")
                end
                function envoy_on_response(response_handle)
                    print("XXXX")
                end
          - name: envoy.router
            config: {}
  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: strict_dns # static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8001
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

*Logs*:
>Include the access logs and the Envoy logs.
See the logs above, there's no access logs because it just fails on the first request.

**Comment by robertpanzer** [comment] 2019-03-25 17:23
For reference I currently have 80ff3651fc7e21bf1153be6f499136412146a105.

**Comment by robertpanzer** [comment] 2019-03-25 17:27
Side note: My original problem was that I wanted to access functions from the internal BoringSSL like `CBS_init`, that I can access on an older local build of Envoy that I build with `-c dbg --strip=never`, but I could not access from within an Envoy in the envoyproxy/envoy docker image. 
I would be very happy as well if I could learn something about this as well :)

**Comment by robertpanzer** [comment] 2019-03-25 18:23
The same test does not crash when building without `-c opt`.
After building with `bazel build //source/exe:envoy-static` the same test succeeds.

**Comment by lizan** [comment] 2019-03-25 18:47
I believe it is a dupe of https://github.com/envoyproxy/envoy/issues/5551, @dio any progress on the fix?

**Comment by mattklein123** [comment] 2019-03-27 15:51
Agree this is a dup, let's track in the linked issue?

**Closed by mattklein123** 2019-03-27 15:51 UTC
Labels: bug, help wanted
