### ISSUE TITLE
flake in BindToPortUpdate

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#19744] opened 2022-01-31 19:43 UTC
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/100324/logs/219

2022-01-31T04:47:06.1174335Z test/integration/listener_lds_integration_test.cc:631: Failure
2022-01-31T04:47:06.1174787Z Expected equality of these values:
2022-01-31T04:47:06.1175628Z   TestUtility::findCounter(test_server_->statStore(), absl::StrCat("listener.", target_listener_prefix_, ".worker_0.downstream_cx_total")) ->value()
2022-01-31T04:47:06.1176377Z     Which is: 11
2022-01-31T04:47:06.1176836Z   repeats
2022-01-31T04:47:06.1177361Z     Which is: 10
2022-01-31T04:47:06.1177715Z Stack trace:
2022-01-31T04:47:06.1178180Z   0x2893527: Envoy::(anonymous namespace)::RebalancerTest::verifyBalance()
2022-01-31T04:47:06.1178771Z   0x2892788: Envoy::(anonymous namespace)::RebalancerTest_BindToPortUpdate_Test::TestBody()
2022-01-31T04:47:06.1179730Z   0x8cceee8: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
2022-01-31T04:47:06.1180295Z   0x8cb2591: testing::internal::HandleExceptionsInMethodIfSupported<>()
2022-01-31T04:47:06.1180972Z   0x8c957c8: testing::Test::Run()
2022-01-31T04:47:06.1181416Z   0x8c9667b: testing::TestInfo::Run()
2022-01-31T04:47:06.1181843Z ... Google Test internal frames ...

**Comment by lambdai** [comment] 2022-02-11 00:54
This test case is fails 1/683 in the last 14 days. I cannot reproduce either. Can we close this?

**Closed** 2022-02-11 15:24 UTC
Labels: bug, area/test flakes
