### ISSUE TITLE
Multiple tests fail to build on Windows CI

### ISSUE THREAD

**Issue by RenjieTang** [envoyproxy/envoy#17409] opened 2021-07-19 20:34 UTC
This issue can be seen on https://github.com/envoyproxy/envoy/pull/17222 [CI run](https://dev.azure.com/cncf/envoy/_build/results?buildId=82739&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53).
It seems that multiple existing tests are comparing `uint64_t` with `optional<uint64_t>` and Windows CI fails to build them.

Not sure why the Windows CI isn't broken in general. Maybe they only run tests that are affected by the PR?

**Comment by RenjieTang** [comment] 2021-07-19 20:37
@wrowe @davinci26

**Comment by davinci26** [comment] 2021-07-21 13:49
That's really weird because the same test passes on main branch. I verified this locally. 

Somehow this is caused by your changes but I am not sure how.

If you want to get unblocked, I would add a call to .value() to explicitly get the value of the optional.

If you don't want to add this then I can do it by eow.

@wrowe knows way more than I do in terms of compilers and c++ standard so he might have an explanation.

**Comment by wrowe** [comment] 2021-07-21 14:30
I had trouble getting clarity on the offending lines of code, but my last encounter discovered comparisons to nullopt_t, while the method has_value seems more standard.

**Comment by wrowe** [comment] 2021-07-21 14:32
It seems some make very specific assumptions about the optional<> implementation that don't carry to the msvc cl compiler. It may go deeper than that, since I was able to reproduce under clang-cl compiler sharing the msvc stdc++ library. https://en.cppreference.com/w/cpp/utility/optional spells out portable usage of optional<>

**Comment by RenjieTang** [comment] 2021-07-21 17:43
I'd love to unblock myself and fix those issues by adding `.value()`. But unfortunately I don't have a Windows local environment to efficiently dig out all the problematic code. :(

**Comment by davinci26** [comment] 2021-07-21 17:51
Let's be a bit optimistic and see if fixing config_impl_test.cc actually unblocks you. 

There are two cases there so maybe fixing this would unblock you.

I am ooo till Friday, so this is the earlier I could push a pr is then.

**Comment by RenjieTang** [comment] 2021-07-22 17:17
I got lucky here and only needed to fix 2 test files to pass CI.
I'm no longer blocked. Feel free to close this issue if you folks think no further action is needed.

**Comment by davinci26** [comment] 2021-07-23 23:51
Closing since everything compiles on main. Although I suspect this will surface again.

**Closed by davinci26** 2021-07-23 23:51 UTC
Labels: area/windows, bug
