### ISSUE TITLE
quiche: quiche h2 unit tests failure

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#21187] opened 2022-05-06 20:41 UTC
Some h2 unit tests from QUICHE were added to quiche.BUILD, but they are not tested in CI. And some actually failed if ran manually, i.e. @com_github_google_quiche//:http2_adapter_nghttp2_session_test
repro: $ bazel test @com_github_google_quiche//...

To tell CIs to run those tests, the target should be added to   https://github.com/envoyproxy/envoy/blob/main/bazel/external/quiche.BUILD#L55

**Comment by birenroy** [comment] 2022-05-16 20:41
Since this issue was filed, it looks like the HTTP/2 tests have started passing. I'll go ahead and add the targets to CI.

**Comment by birenroy** [comment] 2022-05-16 20:46
Confirmed that these tests were fixed with upstream QUICHE changes.

**Closed** 2022-05-31 17:31 UTC
Labels: bug
