### ISSUE TITLE
Envoy doesn't send http2 GOAWAY when drain connection for grpc upstream cluster

### ISSUE THREAD

**Issue by zhiyong-gayang** [envoyproxy/envoy#22825] opened 2022-08-24 09:28 UTC
When LDS is updated, according to [public doc]https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining), envoy should drain the existing connections, and for http2 connection, send GOAWAY signal, so client can handle it properly.
This behavior is confirmed when upstream is a http server.
In our case, the upstream cluster is a GRPC server, and grpc client use bidirectional stream to send/rev data with grpc server, when LDS is updated, envoy start to drain the connection, client doesn't receive GOAWAY signal and after the drain duration, client failed with RST_STREAM.

Just want to confirm is this expected for is there anything need to confirm for grpc?

This is the client side trace log
![image](https://user-images.githubusercontent.com/15938424/186381613-b54e8dfd-8879-4c50-ac80-8bc79b386fa0.png)

Confirmed the same with tcpdump, there is no GOSWAY until server reset the connection.
![image](https://user-images.githubusercontent.com/15938424/186381987-51a6bb00-ec1b-442c-83de-46499b741daf.png)

Sample client side code:
![image](https://user-images.githubusercontent.com/15938424/186382824-6fd26acd-5a2c-417e-b7e9-cee9a591ec43.png)

**Comment by mattklein123** [comment] 2022-08-29 15:49
I believe this is a duplicate of https://github.com/envoyproxy/envoy/issues/14350. Work to fix this has been started, but I don't think it was ever finished. See https://github.com/envoyproxy/envoy/pull/16201 which I think would fix this. cc @murray-stripe.

**Closed by mattklein123** 2022-08-29 15:49 UTC
Labels: triage
