### ISSUE TITLE
crashed when click config_dump

### ISSUE THREAD

**Issue by shuoli84** [envoyproxy/envoy#3329] opened 2018-05-09 03:55 UTC
**Issue Template**

*Title*: *Envoy crashed when click config_dump from admin page*

*Description*:
> I started envoy with xds server, after it bootstrapped, then clicked config_dump on admin page, it generates following stack trace.

*Version*:
envoy  version: 08712e93b07695f53d192a2601cfa2ccc7a20f33/1.7.0-dev/Modified/DEBUG

* Config *:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9902 }

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      cluster_names: [xds_cluster]

  lds_config:
    api_config_source:
      api_type: GRPC
      cluster_names: [xds_cluster]


static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [
      { socket_address: { address: 10.1.62.43, port_value: 8083 }}
    ]
```

* Stack trace *
[2018-05-09 11:50:07.205][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] Caught Segmentation fault: 11, suspect faulting address 0x0
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:87] Backtrace obj<envoy> thr<0>:
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:99] thr<0> obj<envoy                               0x000000010ba08026 _ZN5Envoy6Router30RouteConfigProviderManagerImpl29getStaticRouteConfigProvidersEv>
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #0 0x10ba08026:
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:99] thr<0> obj<envoy>
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #1 0x10ba0b906: Envoy::Router::RouteConfigProviderManagerImpl::dumpRouteConfigs() + 1222
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #2 0x10ba1ba0e: Envoy::Router::RouteConfigProviderManagerImpl::RouteConfigProviderManagerImpl(Envoy::Server::Admin&)::$_3::operator()() const + 30
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #3 0x10ba1b9e3: std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> > >::__call<Envoy::Router::RouteConfigProviderManagerImpl::RouteConfigProviderManagerImpl(Envoy::Server::Admin&)::$_3&>(std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, Envoy::Router::RouteConfigProviderManagerImpl::RouteConfigProviderManagerImpl(Envoy::Server::Admin&)::$_3&&&) + 51
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #4 0x10ba1b89f: std::__1::__function::__func<Envoy::Router::RouteConfigProviderManagerImpl::RouteConfigProviderManagerImpl(Envoy::Server::Admin&)::$_3, std::__1::allocator<Envoy::Router::RouteConfigProviderManagerImpl::RouteConfigProviderManagerImpl(Envoy::Server::Admin&)::$_3>, std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> > ()>::operator()() + 47
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #5 0x10be88bf9: std::__1::function<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> > ()>::operator()() const + 137
[2018-05-09 11:50:07.228][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #6 0x10be885e2: Envoy::Server::AdminImpl::handlerConfigDump(absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&) const + 898
[2018-05-09 11:50:07.229][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #7 0x10bec2df7: Envoy::Server::AdminImpl::AdminImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::Instance&, std::__1::unique_ptr<Envoy::Stats::Scope, std::__1::default_delete<Envoy::Stats::Scope> >&&)::$_4::operator()(absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&) const + 71
[2018-05-09 11:50:07.229][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #8 0x10bec2da2: std::__1::__invoke_void_return_wrapper<Envoy::Http::Code>::__call<Envoy::Server::AdminImpl::AdminImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::Instance&, std::__1::unique_ptr<Envoy::Stats::Scope, std::__1::default_delete<Envoy::Stats::Scope> >&&)::$_4&, absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&>(Envoy::Http::Code, Envoy::Server::AdminImpl::AdminImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::Instance&, std::__1::unique_ptr<Envoy::Stats::Scope, std::__1::default_delete<Envoy::Stats::Scope> >&&)::$_4&&&, absl::string_view&&, Envoy::Http::HeaderMap&&&, Envoy::Buffer::Instance&&&) + 178
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #9 0x10bec2c38: std::__1::__function::__func<Envoy::Server::AdminImpl::AdminImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::Instance&, std::__1::unique_ptr<Envoy::Stats::Scope, std::__1::default_delete<Envoy::Stats::Scope> >&&)::$_4, std::__1::allocator<Envoy::Server::AdminImpl::AdminImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::Instance&, std::__1::unique_ptr<Envoy::Stats::Scope, std::__1::default_delete<Envoy::Stats::Scope> >&&)::$_4>, Envoy::Http::Code (absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&)>::operator()(absl::string_view&&, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&) + 88
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #10 0x10bea2774: std::__1::function<Envoy::Http::Code (absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&)>::operator()(absl::string_view, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&) const + 196
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #11 0x10be9cffa: Envoy::Server::AdminImpl::runCallback(absl::string_view, Envoy::Http::HeaderMap const&, Envoy::Http::HeaderMap&, Envoy::Buffer::Instance&) + 1066
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #12 0x10be82f55: Envoy::Server::AdminFilter::onComplete() + 1013
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #13 0x10be82b49: Envoy::Server::AdminFilter::decodeHeaders(Envoy::Http::HeaderMap&, bool) + 57
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #14 0x10bf05959: Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(Envoy::Http::ConnectionManagerImpl::ActiveStreamDecoderFilter*, Envoy::Http::HeaderMap&, bool) + 1657
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #15 0x10bf02eaa: Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::__1::unique_ptr<Envoy::Http::HeaderMap, std::__1::default_delete<Envoy::Http::HeaderMap> >&&, bool) + 11130
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #16 0x10bf062fa: non-virtual thunk to Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::__1::unique_ptr<Envoy::Http::HeaderMap, std::__1::default_delete<Envoy::Http::HeaderMap> >&&, bool) + 58
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #17 0x10bfdd282: Envoy::Http::Http1::ServerConnectionImpl::onMessageComplete() + 418
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #18 0x10bfdd418: non-virtual thunk to Envoy::Http::Http1::ServerConnectionImpl::onMessageComplete() + 24
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #19 0x10bfe1270: Envoy::Http::Http1::ConnectionImpl::$_7::operator()(http_parser*) const + 32
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #20 0x10bfe1247: Envoy::Http::Http1::ConnectionImpl::$_7::__invoke(http_parser*) + 23
[2018-05-09 11:50:07.236][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #21 0x10bfeea43: http_parser_execute + 19235
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #22 0x10bfda775: Envoy::Http::Http1::ConnectionImpl::dispatchSlice(char const*, unsigned long) + 101
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #23 0x10bfda635: Envoy::Http::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&) + 501
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #24 0x10bfdaad6: virtual thunk to Envoy::Http::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&) + 38
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #25 0x10befa0fb: Envoy::Http::ConnectionManagerImpl::onData(Envoy::Buffer::Instance&, bool) + 1355
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #26 0x10b9c6638: Envoy::Network::FilterManagerImpl::onContinueReading(Envoy::Network::FilterManagerImpl::ActiveReadFilter*) + 1496
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #27 0x10b9c6801: Envoy::Network::FilterManagerImpl::onRead() + 177
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #28 0x10b9b516f: Envoy::Network::ConnectionImpl::onRead(unsigned long long) + 239
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #29 0x10b9b81a5: Envoy::Network::ConnectionImpl::onReadReady() + 405
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #30 0x10b9b7fc5: Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) + 789
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #31 0x10b9bef5d: Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, bool)::$_2::operator()(unsigned int) const + 29
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #32 0x10b9bef2e: _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN5Envoy7Network14ConnectionImplC1ERNS3_5Event10DispatcherEONS_10unique_ptrINS4_16ConnectionSocketENS_14default_deleteISA_EEEEONS9_INS4_15TransportSocketENSB_ISF_EEEEbE3$_2jEEEvDpOT_ + 78
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #33 0x10b9bee28: std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, bool)::$_2, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, bool)::$_2>, void (unsigned int)>::operator()(unsigned int&&) + 56
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #34 0x10b99d457: std::__1::function<void (unsigned int)>::operator()(unsigned int) const + 151
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #35 0x10b99d3ac: Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::operator()(int, short, void*) const + 236
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #36 0x10b99d2b7: Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::__invoke(int, short, void*) + 55
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #37 0x10c39d1da: event_process_active_single_queue + 1450
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #38 0x10c399dad: event_base_loop + 1741
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #39 0x10b9956a1: Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) + 97
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #40 0x10b8d64ed: Envoy::Server::InstanceImpl::run() + 813
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #41 0x10b1e8326: Envoy::MainCommonBase::run() + 150
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<0> #42 0x10b1b7a1b: Envoy::MainCommon::run() + 27
[2018-05-09 11:50:07.237][1843493][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:110] end backtrace thread 0

**Comment by mattklein123** [comment] 2018-05-09 04:27
This was fixed by https://github.com/envoyproxy/envoy/pull/3199 and is a duplicate of https://github.com/envoyproxy/envoy/issues/3141

**Closed by mattklein123** 2018-05-09 04:27 UTC
