### ISSUE TITLE
Use `Stdout` and `Stderr` in canonical proto urls for logging

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15708] opened 2021-03-26 15:56 UTC
### description

we recently added protos for logging that use the names `Stderror` and `Stdoutput` - these are derived from the unix names which are actually `stderr` and `stdout`

i think if we dont change these we are going to confuse/annoy people who will not be familiar with this name, and make it harder to remember

if down the road (eg after documenting #15652 ) we decide to change to the common names its going to be much harder to change than addressing the issue now

**Comment by phlax** [comment] 2021-03-26 15:57
cc @davinci26 @mattklein123

**Comment by mattklein123** [comment] 2021-03-26 16:12
I believe this was done on purpose for some reason but I can't remember. @phlax? I would be fine renaming if we do it quickly since it just landed.

**Comment by davinci26** [comment] 2021-03-26 16:21
The reason that I did is that stdout and stderr are defined with (`#define`) in Windows so when the url is translated to a C++ namespace it causes collisions.

**Comment by phlax** [comment] 2021-03-26 16:24
would it be possible to just change the canonical names?

grepping i see its in paths, filenames and files so theres quite a bit of change

mho is that we should change now and avoid regret

**Comment by davinci26** [comment] 2021-03-26 16:37
would envoy.extensions.access_loggers.**stdoutput**.v3.**StdoutAccessLog** work? 

The reason I did not went for this approach is that there are two different names for stdout in the same type. The problem is envoy.extensions.access_loggers.**stdoutput**.v3.StdoutputAccessLog is translated into `envoy::extensions::access_loggers::stdoutput::v3::StdoutputAccessLog` and there is a namespace collision when it changes to stdout.

**Comment by phlax** [comment] 2021-03-26 16:39
> would envoy.extensions.access_loggers.stdoutput.v3.StdoutAccessLog work?

i think that is more confusing tbh

is there no way to workaround the ns clash  ?

**Comment by davinci26** [comment] 2021-03-26 17:01
> is there no way to workaround the ns clash ?

I have tried undefing it but this breaks fmt.

Another alternative would be to use envoy.extensions.access_loggers.standardstreams.v3.StdoutAccessLog

**Comment by phlax** [comment] 2021-03-26 17:10
what about `envoy.extensions.access_loggers.access.v3.StdoutAccessLog`

not sure if this would then clash with stderr - but perhaps they could be merged in that way - which i think would also be easier to remember

**Comment by phlax** [comment] 2021-03-26 17:11
iiuc this would have the same problem/solution as using standardstreams

**Comment by davinci26** [comment] 2021-03-26 17:12
> not sure if this would then clash with stderr 

Not sure on top of my head. I will have to validate it myself

**Comment by phlax** [comment] 2021-03-26 17:13
im just looking at the dir  - perhaps just `stream` would be closer to `file` which is the closest comparison i think

**Comment by davinci26** [comment] 2021-03-26 17:25
I think there will be clash but a way around it is to have two types in the same proto under the the stream package

**Comment by phlax** [comment] 2021-03-26 17:30
```
envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
```
and
```
envoy.extensions.access_loggers.stream.v3.StderrAccessLog 
```
wfm if its possible to do it that way 

@mattklein123 - any thoughts on this ?

**Comment by phlax** [comment] 2021-03-26 17:32
tbh i would even leave off the final AccessLog if that was possible - shorter the better i think - and it dupes

**Comment by phlax** [comment] 2021-03-26 17:33
hmm - maybe that would be inconsistent with others

**Comment by mattklein123** [comment] 2021-03-26 19:00
I don't have a strong opinion. Whatever you both agree to is fine but we need to change it ASAP if we are going to change it.

**Comment by davinci26** [comment] 2021-03-26 19:02
I am working on this now, I will try to get at it today.

**Closed** 2021-03-29 16:27 UTC
Labels: area/access_log
