### ISSUE TITLE
Flow control buffer limits

### ISSUE THREAD

**Issue by praneetpushpal** [envoyproxy/envoy#30778] opened 2023-11-08 12:48 UTC
Need a clarification with flow control.

We are using envoy proxy and we have some upstream which are actually slow, sometimes taking **upto 22 seconds**:

[2023-10-23T08:37:01.659Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 529 7 4006 4006 "-" "grpc-go/1.56.2" "77cab6b6-0638-430e-b59a-4c3b3029b3b5" "localhost:8887" "172.16.95.212:8080"
[2023-10-23T08:37:02.273Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 685 7 3392 3392 "-" "grpc-go/1.56.2" "f5042724-1468-41a8-b6d5-75a5af0370b7" "localhost:8887" "172.16.95.212:8080"
[2023-10-23T08:36:42.770Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 498 7 **22895 22895** "-" "grpc-go/1.56.2" "5ae72910-3b33-4957-969d-731710bc3206" "localhost:8887" "172.16.95.212:8080"

In such a case envoy is buffering, resulting in out of memory.

In order to protect envoy we wanted to bring in flow control. The doubt is if we configure initial_stream_window_size and per_connection_buffer_limit_bytes to be less than the size of request, will envoy reject such requests?

For example: if I configure initial_stream_window_size as 1 MB and my request is 2 MB will envoy reject such requests?

Basically I dont want envoy to buffer, it should just forward the request to upstream without rejecting requests. Please give your valuable suggestions

**Comment by htuch** [comment] 2023-11-14 05:39
Seems a dupe of https://github.com/envoyproxy/envoy/issues/30779

**Closed by htuch** 2023-11-14 05:39 UTC
Labels: triage
