### ISSUE TITLE
Envoy crashes with "assert failure: !response_headers_."

### ISSUE THREAD

**Issue by bartebor** [envoyproxy/envoy#6557] opened 2019-04-11 09:50 UTC
*Title*: Envoy crashes ocasionally while making a http health check

*Description*:
Envoy crashes once in a few hours. Server is configured dynamically via xDS with ~300 virtual hosts, some of them have http health checks. There was no traffic to Envoy; only http checks were issued periodically.

Git version: cfc514546bc0284536893cca5fa43d7128edcd35

*Repro steps*:
I do not have a way of reproducing crashes. I hope stack trace will be sufficient to pinpoint this problem.

Http health check example:
```
health_checks {
  timeout {
    seconds: 1
  }
  interval {
    seconds: 10
  }
  unhealthy_threshold {
    value: 3
  }
  healthy_threshold {
    value: 1
  }
  http_health_check {
    path: "/"
    expected_statuses {
      start: 200
      end: 300
    }
  }
}

```

*Call Stack*:
```
[2019-04-10 20:24:33.755][10928][critical][assert] [source/common/upstream/health_checker_impl.cc:166] assert failure: !response_headers_.
[2019-04-10 20:24:33.758][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Aborted, suspect faulting address 0x3e800002ab0
[2019-04-10 20:24:33.758][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-04-10 20:24:33.797][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: Envoy::SignalAction::sigHandler() [0x5614cc9eec60]
[2019-04-10 20:24:33.797][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: __restore_rt [0x7f201082e730]
[2019-04-10 20:24:33.806][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: Envoy::Http::StreamDecoderWrapper::decodeHeaders() [0x5614cc3619fd]
[2019-04-10 20:24:33.816][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Http::Http1::ClientConnectionImpl::onHeadersComplete() [0x5614cc4ace53]
[2019-04-10 20:24:33.825][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Http::Http1::ConnectionImpl::onHeadersCompleteBase() [0x5614cc4aab5a]
[2019-04-10 20:24:33.835][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: Envoy::Http::Http1::ConnectionImpl::{lambda()#5}::operator()() [0x5614cc4a9610]
[2019-04-10 20:24:33.844][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Http::Http1::ConnectionImpl::{lambda()#5}::_FUN() [0x5614cc4a962f]
[2019-04-10 20:24:33.853][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: http_parser_execute [0x5614cc7608ca]
[2019-04-10 20:24:33.862][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0x5614cc4aa5df]
[2019-04-10 20:24:33.871][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: Envoy::Http::Http1::ConnectionImpl::dispatch() [0x5614cc4aa47f]
[2019-04-10 20:24:33.880][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: Envoy::Http::CodecClient::onData() [0x5614cc3f1ca6]
[2019-04-10 20:24:33.889][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x5614cc3f272c]
[2019-04-10 20:24:33.898][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: Envoy::Network::FilterManagerImpl::onContinueReading() [0x5614cc1440ed]
[2019-04-10 20:24:33.908][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: Envoy::Network::FilterManagerImpl::onRead() [0x5614cc144204]
[2019-04-10 20:24:33.917][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: Envoy::Network::ConnectionImpl::onRead() [0x5614cc13b16e]
[2019-04-10 20:24:33.925][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: Envoy::Network::ConnectionImpl::onReadReady() [0x5614cc13c935]
[2019-04-10 20:24:33.934][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::Network::ConnectionImpl::onFileEvent() [0x5614cc13c6d3]
[2019-04-10 20:24:33.943][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: Envoy::Network::ConnectionImpl::ConnectionImpl()::{lambda()#3}::operator()() [0x5614cc138eb9]
[2019-04-10 20:24:33.953][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #18: std::_Function_handler<>::_M_invoke() [0x5614cc13e7cf]
[2019-04-10 20:24:33.962][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #19: std::function<>::operator()() [0x5614cc132f38]
[2019-04-10 20:24:33.971][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #20: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::operator()() [0x5614cc132b94]
[2019-04-10 20:24:33.980][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #21: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::_FUN() [0x5614cc132c12]
[2019-04-10 20:24:33.989][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #22: event_process_active_single_queue.isra.33 [0x5614cc73d963]
[2019-04-10 20:24:33.998][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #23: event_base_loop [0x5614cc73eb8f]
[2019-04-10 20:24:34.008][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #24: Envoy::Event::LibeventScheduler::run() [0x5614cc150c79]
[2019-04-10 20:24:34.017][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #25: Envoy::Event::DispatcherImpl::run() [0x5614cc12e19e]
[2019-04-10 20:24:34.026][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #26: Envoy::Server::InstanceImpl::run() [0x5614cc07e199]
[2019-04-10 20:24:34.035][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #27: Envoy::MainCommonBase::run() [0x5614cb9a05ca]
[2019-04-10 20:24:34.043][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #28: Envoy::MainCommon::run() [0x5614cb9873b6]
[2019-04-10 20:24:34.052][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #29: main [0x5614cb985cc4]
[2019-04-10 20:24:34.052][10928][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #30: [0x7f20104fc09b]
```

I have also other stack trace from older version of Envoy, but with debug logs enabled:
```
[2019-04-10 11:00:43.978][28897][debug][connection] [source/common/network/connection_impl.cc:644] [C2913] connecting to 10.32.204.142:8080
[2019-04-10 11:00:43.978][28897][debug][connection] [source/common/network/connection_impl.cc:653] [C2913] connection in progress
[2019-04-10 11:00:43.978][28897][debug][connection] [source/common/network/connection_impl.cc:517] [C2913] connected
[2019-04-10 11:00:43.978][28897][debug][client] [source/common/http/codec_client.cc:64] [C2913] connected
[2019-04-10 11:00:43.990][28897][critical][assert] [source/common/upstream/health_checker_impl.cc:166] assert failure: !response_headers_.
[2019-04-10 11:00:43.994][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Aborted, suspect faulting address 0x3e8000070e1
[2019-04-10 11:00:43.994][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-04-10 11:00:44.025][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: Envoy::SignalAction::sigHandler() [0x561faba52e06]
[2019-04-10 11:00:44.025][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: __restore_rt [0x7faee2343730]
[2019-04-10 11:00:44.034][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: Envoy::Http::StreamDecoderWrapper::decodeHeaders() [0x561fab3c365d]
[2019-04-10 11:00:44.043][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Http::Http1::ClientConnectionImpl::onHeadersComplete() [0x561fab511967]
[2019-04-10 11:00:44.052][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Http::Http1::ConnectionImpl::onHeadersCompleteBase() [0x561fab50f66e]
[2019-04-10 11:00:44.061][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: Envoy::Http::Http1::ConnectionImpl::{lambda()#5}::operator()() [0x561fab50e202]
[2019-04-10 11:00:44.070][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Http::Http1::ConnectionImpl::{lambda()#5}::_FUN() [0x561fab50e221]
[2019-04-10 11:00:44.079][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: http_parser_execute [0x561fab7c54da]
[2019-04-10 11:00:44.088][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0x561fab50f1d1]
[2019-04-10 11:00:44.096][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: Envoy::Http::Http1::ConnectionImpl::dispatch() [0x561fab50f071]
[2019-04-10 11:00:44.106][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: Envoy::Http::CodecClient::onData() [0x561fab45a1b6]
[2019-04-10 11:00:44.114][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x561fab45ac3c]
[2019-04-10 11:00:44.123][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: Envoy::Network::FilterManagerImpl::onContinueReading() [0x561fab1a64bd]
[2019-04-10 11:00:44.132][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: Envoy::Network::FilterManagerImpl::onRead() [0x561fab1a65d4]
[2019-04-10 11:00:44.141][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: Envoy::Network::ConnectionImpl::onRead() [0x561fab19d53e]
[2019-04-10 11:00:44.150][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: Envoy::Network::ConnectionImpl::onReadReady() [0x561fab19ed05]
[2019-04-10 11:00:44.159][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::Network::ConnectionImpl::onFileEvent() [0x561fab19eaa3]
[2019-04-10 11:00:44.168][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: Envoy::Network::ConnectionImpl::ConnectionImpl()::{lambda()#3}::operator()() [0x561fab19b289]
[2019-04-10 11:00:44.177][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #18: std::_Function_handler<>::_M_invoke() [0x561fab1a0b9f]
[2019-04-10 11:00:44.186][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #19: std::function<>::operator()() [0x561fab19532a]
[2019-04-10 11:00:44.195][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #20: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::operator()() [0x561fab194f86]
[2019-04-10 11:00:44.204][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #21: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::_FUN() [0x561fab195004]
[2019-04-10 11:00:44.213][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #22: event_process_active_single_queue.isra.33 [0x561fab7a2573]
[2019-04-10 11:00:44.222][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #23: event_base_loop [0x561fab7a379f]
[2019-04-10 11:00:44.231][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #24: Envoy::Event::LibeventScheduler::run() [0x561fab1b317d]
[2019-04-10 11:00:44.240][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #25: Envoy::Event::DispatcherImpl::run() [0x561fab190590]
[2019-04-10 11:00:44.249][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #26: Envoy::Server::InstanceImpl::run() [0x561fab0df567]
[2019-04-10 11:00:44.258][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #27: Envoy::MainCommonBase::run() [0x561faaa2418a]
[2019-04-10 11:00:44.267][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #28: Envoy::MainCommon::run() [0x561faaa0af76]
[2019-04-10 11:00:44.275][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #29: main [0x561faaa09884]
[2019-04-10 11:00:44.275][28897][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #30: [0x7faee201109b]
```

**Comment by snowp** [comment] 2019-04-11 14:32
From a brief look at the code it seems to be happening because the health checker keep track of the response headers for the duration of the entire response (including headers), but it's seeing another set of headers before the first response completes.

One thought based on your settings: maybe the health checks are timing out after the headers have been received but before the response completes? Skimming through the code I don't see us cleaning up the headers in the timeout case

**Comment by derekargueta** [comment] 2019-05-07 23:23
this seems closely related to (or possibly a dupe of) #3877

**Comment by bartebor** [comment] 2019-06-11 06:47
@derekargueta I think you are right. I have never encountered a crash using official image. Custom release builds work fine too. Only my development builds ocasionally fail. We can probably close this issue, although I do not feel comfortable with fastbuild creating differently behaving/broken executables.

**Comment by mattklein123** [comment] 2019-06-11 14:53
I know what the issue is. I will fix this. (It is actually harmless but it should be fixed so the assert doesn't fire.)

**Closed** 2019-07-23 02:58 UTC
Labels: bug, help wanted
