### ISSUE TITLE
Implement original-src-cluster to bind on the original downstream source IP address

### ISSUE THREAD

**Issue by rlenglet** [envoyproxy/envoy#3481] opened 2018-05-24 17:22 UTC
Implement an `original-src-cluster` feature to bind each upstream connection to the original source address of its associated downstream connection. This will be similar and symmetric to `original-dst-cluster`, which sets the destination address of an upstream connection to that of the associated downstream connection.

This is needed in Istio sidecars in order for applications to see the original source IP addresses. Currently, whenever Envoy opens an upstream connection in an Istio sidecar, it doesn't bind to any specific IP address. In the case of an inbound connection, the upstream connection will have 127.0.0.1 as the destination IP address, so the TCP/IP stack chooses to bind the connection to 127.0.0.1, so the source IP address of the upstream connection will always have 127.0.0.1 as the source IP address.

**Comment by PiotrSikora** [comment] 2018-05-25 02:47
Duplicate of https://github.com/envoyproxy/envoy/issues/2659.

**Comment by mattklein123** [comment] 2018-05-25 15:56
OK closing in favor of the other issue.

**Closed by mattklein123** 2018-05-25 15:56 UTC
Labels: duplicate
