### ISSUE TITLE
Default tag extractors don't work with tags that contain "."s

### ISSUE THREAD

**Issue by eziskind** [envoyproxy/envoy#6622] opened 2019-04-17 17:05 UTC
The [default tag extractors](https://github.com/envoyproxy/envoy/blob/a87a09d1b469942c206d07f4654983db26f1ecc2/source/common/config/well_known_names.cc#L6) treat "." in the stat name specially, as a divider for splitting out tags. Often the tags come from config names which can be arbitrary strings and contain "." which will break these regexes. We should either sanitize such strings before incorporating them into stats names, disallow names with "."s or make the the regexes work even when the names have a ".".

**Comment by htuch** [comment] 2019-04-17 17:28
I think this is a legitimate concern. Arguably, tag extractors have now outlived their original intent and we should deprecate from the API and move to something that is inherently efficient and better suited to this, i.e. structured stats format.

**Comment by fcfort** [comment] 2019-05-17 17:58
Is this issue a dupe of #4357?

**Comment by eziskind** [comment] 2019-05-17 18:22
> Is this issue a dupe of #4357?

yes - please mark as a duplicate.

**Comment by eziskind** [comment] 2019-05-17 18:28
Duplicate of #4357

**Closed** 2019-05-17 21:22 UTC
Labels: help wanted, tech debt
