### ISSUE TITLE
IpVersionsClientType/ExtensionDiscoveryIntegrationTest.BasicWithoutWarming flake

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#12326] opened 2020-07-28 14:17 UTC
@kyessenov can you check this out?
full log here:
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/46303/logs/137

2020-07-28T11:50:42.4207405Z test/integration/extension_discovery_integration_test.cc:282: Failure
2020-07-28T11:50:42.4208094Z Expected equality of these values:
2020-07-28T11:50:42.4208500Z   "200"
2020-07-28T11:50:42.4208823Z     Which is: 0x26b469
2020-07-28T11:50:42.4209518Z   response->headers().getStatusValue()
2020-07-28T11:50:42.4209940Z     Which is: "403"
2020-07-28T11:50:42.4210278Z Stack trace:
2020-07-28T11:50:42.4210649Z   0x1fe2253: (unknown)
2020-07-28T11:50:42.4211041Z   0x61a8a36: (unknown)
2020-07-28T11:50:42.4211410Z   0x61944d1: (unknown)
2020-07-28T11:50:42.4211798Z   0x617eb62: (unknown)
2020-07-28T11:50:42.4212161Z   0x617f668: (unknown)
2020-07-28T11:50:42.4212552Z ... Google Test internal frames ...

Also https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/46257/logs/39

**Comment by kyessenov** [comment] 2020-07-28 16:00
Thanks for the report. Is this happening often? I could get it <1/1000 rate sometimes. I think it's because of a delay between xDS accepted and active, but can look further.

**Comment by alyssawilk** [comment] 2020-07-28 16:12
Yeah, test flakes are often 1:1000 locally when they're more like 1:50 on CI.   I saw those two plus maybe one more on CI overnight, which is enough we'll probably want to disable the test if you don't think you can get a fix in soon (since flakes tend to get worse at peak).  thanks for taking a look!

**Comment by kyessenov** [comment] 2020-07-28 17:45
I can confirm this is because of the delay between config_reload metric and `tls_->runOnAllThreads`. It looks similar to `workers_started` issue. Is it OK to create another metric and and an atomic int to count TLS updates?

**Comment by mattklein123** [comment] 2020-07-28 17:52
@kyessenov optimally the metric would have some operational value, but if we need it for synchronizing tests it's probably fine. The other option would be to make a metric specific to the extension system for when the atomic update is actually applied on each worker (vs. generically for all TLS updates). I mildly prefer this as it's more explicit.

**Comment by kyessenov** [comment] 2020-07-28 17:54
I would prefer `config_reload` to mean config applied (potentially partially). There're already xDS stats for ACKing (acceptance but not applied). Let me see how to fix this. I imagine this is a generic problem, but it just surfaced in this test.

**Comment by mattklein123** [comment] 2020-07-28 18:00
> I would prefer config_reload to mean config applied (potentially partially). There're already xDS stats for ACKing (acceptance but not applied). Let me see how to fix this. I imagine this is a generic problem, but it just surfaced in this test.

Yes agreed it's likely a generic problem that we are now hitting as we add more features like this. I think a per-worker TLS update stat is probably fine to solve these types of issues, my concern is there are other TLS updates happening and it might be flaky. I wonder if add a test hook for TLS updates is the way to go here, possibly also with naming each TLS slot. This would potentially allow you to wait for updates to TLS slots in tests?

**Comment by kyessenov** [comment] 2020-07-28 18:03
I was thinking of passing a shared decrementing counter and a stat scope. Then each update will decrement and update the stat on 0. This is exactly how it's done for workers_started. Is there an issue with this approach? I think the lifetimes work out since TLS is owned by the provider which outlives the subscription with the stats scope.

**Comment by mattklein123** [comment] 2020-07-28 18:37
> I was thinking of passing a shared decrementing counter and a stat scope. Then each update will decrement and update the stat on 0. This is exactly how it's done for workers_started. Is there an issue with this approach? I think the lifetimes work out since TLS is owned by the provider which outlives the subscription with the stats scope.

I'm not exactly sure what we are talking about. Like a stat specific to this problem? Or a general one? At a high level this sounds fine so if you want to do a PR we can discuss there.

**Comment by kyessenov** [comment] 2020-07-28 19:52
https://github.com/kyessenov/envoy/pull/new/deflake_ecds_integ_test
Still seeing a flake once every 2000 test runs. So it's not sufficient :(

**Comment by alyssawilk** [comment] 2020-07-28 19:55
Is it an improvement? Incremental change is still good :-)

**Comment by kyessenov** [comment] 2020-07-28 19:57
I am beginning to doubt it's even possible to fully deflake it. I'll try another trick, and see if it helps.

**Comment by mattklein123** [comment] 2020-07-28 20:03
@kyessenov it must be possible to deflake it, the question is how. Can you potentially chat with @alyssawilk to better understand the problem and brainstorm solutions?

**Comment by kyessenov** [comment] 2020-07-28 20:08
I found a flaw -- it appears there are actually two workers in the integration tests (master is counted?). Trying to see if that helps.

**Comment by kyessenov** [comment] 2020-07-30 15:47
Can we close this now? I could not get any more flakes after the last fix.

**Closed** 2020-07-30 16:05 UTC
Labels: area/test flakes, help wanted
