### ISSUE TITLE
Non uniform connection distribution to Envoy worker threads

### ISSUE THREAD

**Issue by ahmedelbazsc** [envoyproxy/envoy#7831] opened 2019-08-05 20:50 UTC
*Title*: *Enhancing workload distribution to worker threads*

*Description*:
We have a gRPC client server setup which uses Envoy as a sidecar proxy for egress and ingress calls as follows:
gRPC client -> client Envoy -> Server Envoy -> gRPC server
With Envoy used on the egress path, we observed degraded (and inconsistent) client throughout which appears related to the connection distribution of gRPC client over Envoy worker threads.

Connection Pooling:
To increase throughput we attempted pooling connections from the client to the local Envoy sidecar which demonstrated throughput improvements, but results were inconsistent across different runs. We saw maximum throughout when all Envoy worker threads are handling incoming connections but it appears there are no guarantees on how incoming connections are distributed to workers.

To confirm this, we attempted to regularly refresh connections in the pool, as opposed to keeping long persistent connections, which shows consistent best results with all threads utilized.

SO_REUSEPORT:
It is undesirable however to continuously refresh gRPC connections as opposed to leverage request multiplexing over stable connections. So an alternative we attempted was to configure the listener socket options to use SO_REUSEPORT as follows. 

```
{
   "name": "listener-name",
   "address": { . . . },
   "filter_chains": [ . . .],
   "socket_options": [{
      "description": "SO_REUSEPORT",
      "level": 1,
      "name": 15,
      "int_value": 1
   }]
}
```

With this option we expect better connection distribution over worker threads, but we did not see any measurable change in behavior. 
Is SO_REUSEPORT option not set properly above, or not honored in Envoy ? Any recommendations to mitigate this issue ?

Environment details:
Envoy version: 1.9.1
Image: alpine:3.10.0
We use default Envoy concurrency configuration. Instance has 8 Core CPU

**Comment by mattklein123** [comment] 2019-08-06 15:34
This is a duplicate of https://github.com/envoyproxy/envoy/issues/4602. Shall we track there?

**Comment by ahmedelbazsc** [comment] 2019-08-06 15:45
Thanks @mattklein123 . The connection accept distribution over worker threads seems covered by the other issue. For SO_REUSEPORT, is the setting provided above expected to be honored by the listener ?

**Comment by mattklein123** [comment] 2019-08-06 15:47
That config should enable SO_REUSEPORT, but it's unclear to me how that would help connection distribution. The kernel will still decide how to allocate connections to workers in a potentially non-optimal way.

**Comment by ahmedelbazsc** [comment] 2019-08-06 20:28
Some references suggest this option provides better connection distribution across all threads listening on the socket, so this was the motivation for trying this option. Thanks for confirming the config correctness

**Comment by mattklein123** [comment] 2019-09-01 03:12
Closing as tracking this in https://github.com/envoyproxy/envoy/issues/4602

**Closed by mattklein123** 2019-09-01 03:12 UTC
Labels: duplicate
