### ISSUE TITLE
Envoy can shield specified log content？

### ISSUE THREAD

**Issue by txlong2012slug** [envoyproxy/envoy#28233] opened 2023-07-05 01:52 UTC
*Title*: *Envoy can shield specified log content？*

*Description*:
Envoy logs all headers which some keys are sensitive. How can I shield specified sensitive header and do not print logs?

For example, how to shield 'x-forwarded-client-cert' in the following figure？

![image](https://github.com/envoyproxy/envoy/assets/10905731/a62491ba-a43a-46e8-bb04-76530cafaa7c)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment] 2023-07-05 18:03
Sanitization in the application logs is not supported - I think you can simply not set the log level to "debug" or "trace". Per-request info is only printed at those levels.

**Comment by kyessenov** [comment] 2023-07-05 18:04
Duplicate of https://github.com/envoyproxy/envoy/issues/27820

**Closed by kyessenov** 2023-07-05 18:04 UTC
Labels: enhancement
