### ISSUE TITLE
Build fails on MacOS with Clang 9 due to _POSIX_C_SOURCE in boringssl test

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#1789] opened 2017-09-30 01:00 UTC
The top of boringssl/blob/master/crypto/bio/bio_test.cc contains this define:

```c++
#if !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 201410L
#endif
```

... which breaks the Clang 9 C++ standard library:

```
$ cat hello.cc
#if !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 201410L
#endif
#include <ostream>
int main() { return 0; }


$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin


$ clang++ hello.cc
In file included from hello.cc:5:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/mutex:189:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__mutex_base:17:
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:156:1: error: unknown type name
      'mach_port_t'
mach_port_t __libcpp_thread_get_port();
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:300:1: error: unknown type name
      'mach_port_t'
mach_port_t __libcpp_thread_get_port() {
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:301:12: error: use of undeclared
      identifier 'pthread_mach_thread_np'
    return pthread_mach_thread_np(pthread_self());
           ^
3 errors generated.
```

We'll want to patch boringssl until they've shipped a fix, then upgrade the Envoy boringssl dependency pin.

**Comment by mattklein123** [comment] 2017-09-30 01:52
See https://github.com/envoyproxy/envoy/pull/1785

**Comment by mattklein123** [comment] 2017-09-30 20:49
Fixed by https://github.com/envoyproxy/envoy/pull/1785

**Closed by mattklein123** 2017-09-30 20:49 UTC
Labels: bug

**Comment by davidben** [comment] 2017-10-02 19:13
This is a bug in Apple's headers, not BoringSSL. The fix is this change here:
https://github.com/llvm-mirror/libcxx/commit/bcc92d75df0274b9593ebd097fcae60494e3bffc

I'm unable to reproduce it myself in Xcode. It appears they've instead hacked their pthread.h to add a `defined(__cplusplus)` to the long list of conditions where they provide `mach_port_t`. But the standalone command-line tools you're using I guess is missing this hack.

Good news is I think we no longer need the `_POSIX_C_SOURCE` bits in any of the C++ files (still need to double-check this though), so that should work around their bug. Failing that we can define `_DARWIN_C_SOURCE`.

Feature macros are the worst. :-)

**Comment by davidben** [comment] 2017-10-03 02:29
This should work around it:
https://boringssl.googlesource.com/boringssl/+/63a0797ff247f13870b649c3f6239d80be202752

Hope that helps!
