### ISSUE TITLE
Leak when reading from SSL sockets

### ISSUE THREAD

**Issue by julia-stripe** [envoyproxy/envoy#6617] opened 2019-04-17 14:27 UTC
**Envoy version**: v1.9.1

We're seeing an issue where Envoy sometimes leaks tens of gigabytes of memory. I still don't have a great understanding of why this is happening, but here's what we know so far.

Here's the output of pprof on a heap profile: https://gist.github.com/julia-stripe/04cee10b2185d81f1b84ad493920a9b3 which I think is saying that the memory is being allocated on [this line](https://github.com/envoyproxy/envoy/blame/53781eb42fdfce56ec3b187dc551344ab4f4a86f/source/extensions/transport_sockets/tls/ssl_socket.cc#L86).

Some other observations:

[Here are some logs from the heap profiler](https://gist.github.com/julia-stripe/37311c46088ab00a45143f6d3395292e). It looks like the pattern is that it allocates ~8GB of memory, frees some memory, and then does the same thing again. There are a lot of periods where it's allocating about 1GB/s.

tcmalloc doesn't seem to be doing a great job of releasing freed memory back to the OS though: this example of what's reported by the stats endpoint is pretty typical (16MB allocated, 17GB heap). 

```
$ curl localhost:9901/stats | grep memory
server.memory_allocated: 16697176
server.memory_heap_size: 17301504000
```

A few more relevant statistics that make this confusing:

* [output](https://gist.github.com/julia-stripe/176fcd4251af6237416d92b7e60a0ad6) of `curl localhost:9901/stats | grep bytes` (less than 100GB of data)
* [output](https://gist.github.com/julia-stripe/925b377e9dfc9d9b899ece3156fe5ec1) of `curl localhost:9901/stats | grep cx_total` (only ~2000 connections)

**Comment by htuch** [comment] 2019-04-17 15:27
Thanks for the detailed report. Do you have a heap profile as a flame graph by any chance? I think that could be a useful insight into the call stack at allocation time.

CC @brian-pane (who knows a lot about Envoy's buffer management) and @PiotrSikora (SSL subsystem expert).

**Comment by julia-stripe** [comment] 2019-04-17 15:36
Here's a flamegraph.
<img width="1334" alt="Screen Shot 2019-04-17 at 8 36 10 AM" src="https://user-images.githubusercontent.com/23065472/56301054-e231b400-60eb-11e9-8ced-658b28e0202a.png">

**Comment by mattklein123** [comment] 2019-04-17 16:08
Assuming allocated drops back down, it's unlikely there is a leak. The issue here is likely that tcmalloc is notoriously bad about releasing memory back to the OS. IIRC there are some options to make it do that, but I've never gotten it to work very well. I think @dnoe might know more about this.

The issue is more likely that there is a huge influx of traffic and Envoy memory/connection count grows very high before dropping down. You might want to look into enabling the overflow manager to prevent this type of unbounded growth on incoming connections: https://www.envoyproxy.io/docs/envoy/latest/configuration/overload_manager/overload_manager.

**Comment by julia-stripe** [comment] 2019-04-17 16:33
The thing that's very confusing to me is that there *doesn't* seem to be a lot of traffic on the boxes suffering from this -- dstat reports at most ~50MB/s of sent/recv'd and there are only ~2000 connections total, but memory is still sometimes growing at 1GB/s.

One hypothesis I have is that -- there are millions of `ssl read returns: 1` lines logged (from [here](https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/ssl_socket.cc#L89)) when I turn on trace logging.

This makes me think that for some reason (??) Envoy is reading 1 byte at a time and allocating 16kb every time that happens. So even though not a lot of data is being transferred, Envoy is allocating a 16kb buffer for every byte read, which adds up.

**Comment by mattklein123** [comment] 2019-04-17 17:21
@julia-stripe thanks for the extra info. If you feel like reading some code, take a look at https://github.com/libevent/libevent/blob/1f4f8769c4e78b14e6aa21d8300f432f67def8df/buffer.c#L690 and see how that behaves. From my quick read, we expand the buffer to make sure that we have 16K of space available, so I'm pretty sure that we would have at most 16K (or whatever the slice allocation size is rounded up) of extra space per connection sitting around.

**Comment by julia-stripe** [comment] 2019-04-18 15:00
Here's a self-contained reproduction of this issue we put together. If you run `run.sh`, you should see Envoy quickly allocating something like 20GB of memory. It uses a fairly pathological backend service (`main.go`). https://gist.github.com/julia-stripe/a9024d845e4b566f7aa06282e232a026 

A hypothesis we have is that is that the Go backend is somehow racing Envoy's logic that closes the connection, so that Envoy ends up keeping a connection open that should normally be closed and then keeps reading bytes from that connection and allocating memory.

**Comment by mattklein123** [comment] 2019-04-18 16:03
@julia-stripe Envoy will accept an unbounded amount of connections and allocate an unbounded amount of memory unless you configure the overload manager. It looks like that's what your example is doing?

**Comment by julia-stripe** [comment] 2019-04-18 17:24
@mattklein123 I [updated main.go](https://gist.github.com/julia-stripe/a9024d845e4b566f7aa06282e232a026) to log the number of bytes sent by the misbehaving server. The server reports that it sent 4194305 bytes, but Envoy's statistics say `server.memory_allocated: 13607850192`, and `listener.0.0.0.0_8190.downstream_cx_total: 19088`. Is there another source of memory I'm missing here (other than connections / bytes sent by the server) that would explain where the 13GB of memory being allocated is coming from?

**Comment by mattklein123** [comment] 2019-04-18 17:32
@julia-stripe sorry not sure. I would get a heap profile / dump of the Envoy when it has 13GB allocated. You can configure the tcmalloc heap profiler to dump when every 1GB is allocated for example. What I still suspect is happening here is that connections are being created faster than they are being cleaned up, but I'm not completely sure.

**Comment by julia-stripe** [comment] 2019-04-18 20:02
> What I still suspect is happening here is that connections are being created faster than they are being cleaned up, but I'm not completely sure.

I can reproduce this by making about 15 connections to Envoy which send a total of 4MB, so it's definitely not the number of connections

**Comment by brian-pane** [comment] 2019-04-18 20:20
Is this reproducible with both the original and the new Envoy buffer implementations? (I think the original implementation is still the default, and the new one can be enabled at Envoy startup by adding the command-line parameters `--use-libevent-buffers 0`).

**Comment by julia-stripe** [comment] 2019-04-18 20:41
It's with the original buffer implementation, I haven't tested with the new implementation.

**Comment by mattklein123** [comment] 2019-04-18 21:47
@julia-stripe sorry I did not read your Go code in detail enough, I think I understand the full scenario now. OK, here are some things to investigate if you are willing:
1) Can you please run your test with master to rule out any fixed issue?
2) What flow control settings are you using? Are you using HTTP/1 or HTTP/2 between downstream and upstream? Can you look at flow control stats to see if flow control is kicking on?
3) Per @brian-pane it might be worth it to quickly try with the new buffer implementation, it's possible there is an issue with libevent where we keep reserving more data and not reusing the existing reservations, that would need to be looked into.
4) Can you confirm that once a connection is opened it stays open? Who is closing the connection?

**Comment by PiotrSikora** [comment] 2019-04-18 21:59
5. Could you verify that this is only happening for SSL sockets and not for plaintext?

Thanks!

**Comment by julia-stripe** [comment] 2019-04-18 22:26
here are answers to #2, #4, and #5 -- I've been having some trouble getting master compiled but once I figure that out I'll answer #1 and #3.

5. It's only happening for SSL sockets, I tested the same program / request pattern on plaintext (with many many more requests) and couldn't get Envoy's heap to more than about 5MB.
4. Some of the connections stay open and some are closed by Envoy. I'm not sure why some connections are closed yet and some aren't (maybe there's a race somewhere?). From observation, I believe that the connections that stay open are the ones that are causing the large increases in memory.
2. From Envoy's perspective it's just a TCP socket (the example of this we have internally is a CONNECT proxy). `per_connection_buffer_limit_bytes` just has the default value, I'm not sure what other flow control settings we should be using.

here are the flow control stats: 

```
cluster.service1.upstream_flow_control_backed_up_total: 0
cluster.service1.upstream_flow_control_drained_total: 0
cluster.service1.upstream_flow_control_paused_reading_total: 1
cluster.service1.upstream_flow_control_resumed_reading_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
tcp.ingress_http.downstream_flow_control_paused_reading_total: 0
tcp.ingress_http.downstream_flow_control_resumed_reading_total: 0
```

**Comment by mattklein123** [comment] 2019-04-19 00:14
@julia-stripe I will poke around a bit more tomorrow. Can you provide your full config or some approximation of it so we are all on the same page in terms of settings, filters, etc.? Thank you.

**Comment by julia-stripe** [comment] 2019-04-19 02:55
@mattklein123 I linked to it earlier up -- https://gist.github.com/julia-stripe/a9024d845e4b566f7aa06282e232a026

**Comment by julia-stripe** [comment] 2019-04-19 13:48
I think the issue is in this loop: https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/ssl_socket.cc#L81-L93. Here's what the code looks like it's doing to me:

1. Every time Envoy reads more data from `SSL_read`, it reserves another 16k buffer
2. It always reads the data from `SSL_read` into the beginning of the buffer, so even if only 1 byte is read it takes up the whole 16k buffer

I believe there are 2 things contributing to this issue:

a. `SslSocket::doRead` is assuming that every read from `SSL_read` will be relatively big, and so it doesn't attempt to put data from more than one read into each 16k slice, it just gives every read its own slice
b. the size of `read_buffer` isn't being kept in check by any flow control (I can't see any buffer size controls in `SslSocket::doRead`) so there's nothing preventing `read_buffer` from growing in size an unlimited amount

some archaelogy makes it look like the SSL buffer handling code in Envoy is inspired by the [bufferevent_openssl implementation](https://github.com/libevent/libevent/blob/16d8564a2cd2ec665b577f39eea6583d4b651e92/bufferevent_openssl.c#L607-L615) which looks like it has the same behaviour.

If this is right, I don't believe the new/old buffer implementation would make a difference. It also seems like it should be possible to use this to DoS Envoy as a client, though I haven't been able to get a PoC of that working yet.

**Comment by mattklein123** [comment] 2019-04-19 15:57
I think the issue here is more nuanced. From my read, the plain text code does exactly the same thing. See `RawBufferSocket::doRead(Buffer::Instance& buffer)` and `OwnedImpl::read(Network::IoHandle& io_handle, uint64_t max_length)`. Also, my understanding of the `reserve` code is that it does not allocate a fresh 16KiB each time, it just makes sure there is 16KiB space available. If this is not the case it's definitely a bug, but given that the plain text code appears to be the same and you don't see any issue there, it's unclear what is happening. 

So either there is a more subtle difference between the two paths, or read disable/flow control is not working for some reason in this path, or some other more subtle reason. Unfortunately I'm not going to have much more time to look at this today but cc @PiotrSikora @lizan who might be able to look a bit more (cc @alyssawilk also who is on vacation).

**Comment by lizan** [comment] 2019-04-19 19:23
I did quick test on @julia-stripe's gist on my local box, with envoy commit 3a8128a8189a65c2f156eaea5bcb14ac50166ed9.

I can confirm it goes to:
```
server.memory_allocated: 4100408
server.memory_heap_size: 8990490624
```

very quickly, but in the middle of stats queries I do also see 
```
server.memory_allocated: 4496481176
server.memory_heap_size: 8990490624
```
as well, and it seems allocated memory does spike.

**Comment by lizan** [comment] 2019-04-19 19:27
This dos happen for new buffer implementation as well, still exists when I added `--use-libevent-buffer 0` to envoy args

**Comment by lizan** [comment] 2019-04-20 00:05
I think @julia-stripe https://github.com/envoyproxy/envoy/issues/6617#issuecomment-484901279 is mostly correct, though we don't fully reserve 16k buffer, it reserve almost half of them (since we reserve in two slices), when SSL_read read bytes into a slice, we shrink the slice len_, and it wastes up to 16k memory. Posted #6662 try to fix this.

The part I'm not sure is that `SSL_read` returns millions of 1 (means it only read 1 bytes) in same event, which is unexpected, any idea why this is the case? @PiotrSikora.

**Comment by mattklein123** [comment] 2019-04-20 01:42
Hmm, I need to look into this more. @lizan AFAICT the raw transport socket does exactly the same thing. Also, the buffer code should not always waste the memory, it should give you 16K across 2 slices, even if that starts 1 byte after the previous read.

**Comment by mattklein123** [comment] 2019-04-20 01:49
Oh, I think I know the difference. The plain text socket is using `readv()` is being smarter about this. The buffer code must not be doing what I'm talking about, which is to be intelligent about a split reservation, though I'm quite surprised by this. @brian-pane how does the new buffer code handle this? I think @lizan's fix sounds reasonable if the buffer code is not doing what we think it should be doing.

**Comment by brian-pane** [comment] 2019-04-20 01:52
The new buffer code reuses the available space at the end of the previous buffer, if I remember correctly. But with both the old and new buffer implementations, space might end up being wasted if the caller `reserve`s two iovecs and only `commits` the first of them.

**Comment by mattklein123** [comment] 2019-04-20 01:53
@brian-pane why would it be wasted vs. being used next time? That must be what is happening here. This seems broken for the plain text case also.

**Comment by brian-pane** [comment] 2019-04-20 01:59
The semantics are ill-defined if you reserve 2 iovecs, commit just the first of them, and then do another reservation. The buffer implementation doesn’t know whether the caller might subsequently commit the 2nd iovec from the first reservation, so it might be erring on the side of caution and allocating a new buffer. I’ll check the code when I get home, to find out for sure.

**Comment by brian-pane** [comment] 2019-04-20 02:43
Confirmed: neither the old nor the new buffer implementation reuses the buffer space if you reserve two iovecs and only commit the first of them. Here's a test case that expects reuse and fails for both impls: https://github.com/brian-pane/envoy/commit/49603c9196c350ebc10971e240476dfd00eae177

This test case probably can't be committed in its current form, because it's checking for semantics that aren't actually defined in the buffer API. But it definitely shows that reserving multiple iovecs and not committing them all will yield excessive memory usage. It's not quite a memory leak, because all the memory does get freed when the buffer object is destroyed. But during the lifetime of the buffer object, the memory utilization in a pathological test case can approach 8,000 times the number of bytes actually read from the socket.

**Comment by mattklein123** [comment] 2019-04-20 03:01
@brian-pane ugh thanks a ton for looking into this. WDYT about changing the behavior of the new implementation to allow reuse? IMO that's the way it should work (and thought it work). I think this is actually an issue in the plain text socket as well, but the kernel does a better job of collapsing the small writes into a single larger read.

**Comment by brian-pane** [comment] 2019-04-20 03:08
Sounds good to me. I'll post a PR shortly.

**Comment by brian-pane** [comment] 2019-04-20 05:01
There may be an additional problem. I just remembered that, because of how libevent allocates slices internally, its 16KB slice size will have room for quite a bit more than 16KB. That makes my prior test case invalid.  In commit #[6663](https://github.com/envoyproxy/envoy/pull/6663), I added a new, valid version of the test ... and the old libevent-based buffer implementation passes the test.

That PR is still useful, because it makes the new buffer impl more robust. But I'll need to dig further to figure out the failure mode with the old buffer impl, since it's not one of the scenarios that the PR tests for.

**Comment by lizan** [comment] 2019-04-20 08:44
@mattklein123 @brian-pane yeah that's right, here is while I debug this issue to see where the problem is starting:

Format: ssl read returns: <rc> <slice.mem_> <slice.len_(before shrinking>

```
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff1 16399
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff2 16398
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff3 16397
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff4 16396
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff5 16395
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff6 16394
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff7 16393
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff8 16392
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ff9 16391
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ffa 16390
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ffb 16389
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ffc 16388
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ffd 16387
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1ffe 16386
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d1fff 16385
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 1
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d2000 16384
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d2001 16383
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cc430 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cc431 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d6030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28d6031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cc830 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cc831 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28da030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28da031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28ccc30 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28ccc31 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28de030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28de031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd030 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd031 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28e2030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28e2031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd430 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd431 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28e6030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28e6031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd830 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cd831 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28ea030 16336
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28ea031 16335
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cdc30 976
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C59] ssl reserved slices: 2
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28cdc31 975
[2019-04-19 23:02:30.010][29967][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:90] [C59] ssl read returns: 1 0x28ee030 16336
```

From where the reservation return 2 slices and ssl socket only commits 1 bytes, the address changes significantly, which also confirms https://github.com/envoyproxy/envoy/issues/6617#issuecomment-485052520

**Comment by brian-pane** [comment] 2019-04-20 16:02
Thanks @lizan. I just ran @julia-stripe's test case with some extra diagnostic logging added to Envoy and found that, independent of whether the buffer is using its internal space efficiently, a bigger problem is that `SslSocket::doRead(Buffer::Instance& read_buffer)` keeps reading into the buffer and never consumes any of the data that's been read. The buffer length increases endlessly.

I started the Go server and Envoy with the configs from https://gist.github.com/julia-stripe/a9024d845e4b566f7aa06282e232a026 and sent a single HTTP request to Envoy:
```
curl localhost:8190 2>/dev/null > /dev/null
```
The Go server sent its HTTP response with `Content-Length: 5` and, as designed, sent an infinitely long response body.

Within the `while (keep_reading) { ... }` loop in `ssl_socket.cc`, I logged the length of the buffer before each read. The results look like this:
```
buffer 0x3274ea8 len 0
buffer 0x3274ea8 len 38
buffer 0x3274ea8 len 39
buffer 0x3274ea8 len 40
[... lots of lines skipped ...]
buffer 0x3274ea8 len 400883
buffer 0x3274ea8 len 400885
buffer 0x3274ea8 len 400887
[... this continues forever ...]
```

That all happens in _one_ call to `SslSocket::doRead(Buffer::Instance& read_buffer)`.

The only things that will break out of that `while (keep_reading)` loop are:
* EAGAIN or an error when reading the socket (which won't happen when the upstream is sending data as fast as this Go server is).
* Or `callbacks_->shouldDrainReadBuffer()`.

**Comment by brian-pane** [comment] 2019-04-20 16:20
It looks like `callbacks_->shouldDrainReadBuffer()` eventually breaks out of that read loop in `ssl_socket.cc` ... after the buffer accumulates 1MB of data.

Then the SSL socket read callback gets called again (which makes sense, because there's still data arriving from upstream). It gets the same buffer, which has been drained, and it starts reading and buffering its next megabyte of data.
```
buffer 0xe590ea8 len 1048575
doRead 0xe590ea8  <-- new invocation of the SSL socket read callback
buffer 0xe590ea8 len 0
buffer 0xe590ea8 len 1
```

**Comment by brian-pane** [comment] 2019-04-20 16:40
Here's the source of the 1MB buffering limit: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L553

I propose that the default should be something like 16KB, which will be safer for people running edge proxies with hundreds of thousands of concurrent connections.

**Comment by mattklein123** [comment] 2019-04-20 17:20
I think we need to step back here. What the default size of the flow control limit is, is IMO orthogonal to the actual problem here which is apparently a huge amount of wasted space when we read a single byte into the buffer. Can we figure out why the reservation code is not doing that efficiently so that we would only be allocating at most an extra 16KiB of buffer space in this pathological case?

I'm not sure that changing the default max buffer size is something we should do without more thinking but we can discuss that in the other PR.

**Comment by brian-pane** [comment] 2019-04-20 17:31
I'm no longer sure that the buffer reservation code itself is doing anything wrong (other than what [PR6663](https://github.com/envoyproxy/envoy/pull/6663) fixes). Looking at how the SSL socket code is using the reservation, it's easy for it to produce large block of unused memory in the middle of a buffer.

`SslSocket::doRead(Buffer::Instance& read_buffer)` reserves two slices and does a separate socket read into each of them. If the first read returns one byte and the second read returns anything more than zero, we're going to end up with a lot of unusable space at the end of the first slice.

So I think there separate problems:
1. The commit logic in the new buffer impl (PR 6663)
2. The logic in `SslSocket::doRead` misuses buffer slices in a way that can lead to internal fragmentation.
3. The default buffer limits (PR 6665).

**Comment by brian-pane** [comment] 2019-04-20 17:43
I just wrote a patch for issue 2 (internal fragmentation due to the way `SslSocket::doRead` uses the slices). I'll post a PR once the tests complete.

**Comment by mattklein123** [comment] 2019-04-20 20:23
Yup OK I see the issue now, thanks for explaining it clearly.

**Closed** 2019-05-16 23:22 UTC
Labels: bug

**Comment by prune998** [comment] 2019-11-05 19:59
My issue seem to be closely related to this one. Maybe we should re-open here ?

**Comment by mattklein123** [comment] 2019-11-05 20:04
@prune998 please debug in the other issue you opened. There is not enough information to know what is going on. We won't be reopening this issue unless we determine it is not fixed.
