### ISSUE TITLE
envoyproxy/envoy:v1.23.0 docker image broken on aarch64

### ISSUE THREAD

**Issue by markmartirosian** [envoyproxy/envoy#22721] opened 2022-08-16 12:34 UTC
*Description*:

This is duplicate of https://github.com/envoyproxy/envoy/issues/22261, missed it on first look.

The `envoyproxy/envoy:v1.23.0` fails to start with `/docker-entrypoint.sh: 29: exec: su-exec: Exec format error`. The `envoyproxy/envoy:v1.22.0` works as expected.

*Repro steps*:

```
[root@i-0fca45895a9b81442 ec2-user]# docker run -it envoyproxy/envoy:v1.23.0
Unable to find image 'envoyproxy/envoy:v1.23.0' locally
v1.23.0: Pulling from envoyproxy/envoy
8376114ff9b3: Pull complete
bc45fc51b638: Pull complete
ef89a4cf0efa: Pull complete
bd4430a287b9: Pull complete
3e54b87113ea: Pull complete
b6eec207dd6c: Pull complete
adb2b2bea0ee: Pull complete
49506b69cdb6: Pull complete
Digest: sha256:b8dde8b3f8adc0fb9fb581ed566399a67398f83588cf26d0604e1c9c9fd3b557
Status: Downloaded newer image for envoyproxy/envoy:v1.23.0
/docker-entrypoint.sh: 29: exec: su-exec: Exec format error
```

```
[root@i-0fca45895a9b81442 ec2-user]# docker run -it envoyproxy/envoy:v1.22.0
Unable to find image 'envoyproxy/envoy:v1.22.0' locally
v1.22.0: Pulling from envoyproxy/envoy
d35feac4abe8: Pull complete
f18e9d859af6: Pull complete
039c0eedb2e7: Pull complete
d472b5907dbd: Pull complete
3f7d6d6f4fcf: Pull complete
877b93bbcadd: Pull complete
835f55682df1: Pull complete
6aba25efd78c: Pull complete
Digest: sha256:478044b54936608dd3115c89ea9fe5be670f1e78d4436927c096b4bc06eeedeb
Status: Downloaded newer image for envoyproxy/envoy:v1.22.0
[2022-08-16 12:23:45.734][1][info][main] [source/server/server.cc:390] initializing epoch 0 (base id=0, hot restart version=11.120)
```

*References*

https://github.com/tetratelabs/archive-envoy/issues/43
https://github.com/envoyproxy/envoy/issues/22261

**Comment by phlax** [comment] 2022-08-16 13:13
closing this as duplicate of #22261 

this should be resolved in the coming days

**Closed by phlax** 2022-08-16 13:13 UTC
Labels: bug, triage
