### ISSUE TITLE
Increase (and/or make configurable) the maximum size of a direct response

### ISSUE THREAD

**Issue by petedmarsh** [envoyproxy/envoy#14720] opened 2021-01-15 11:56 UTC
*Title*: Increase (and/or make configurable) the maximum size of a direct response

*Description*:

I'd like to have a direct response which is more then 4KiB in size, I completely understand the desire to be conservative with the size of direct responses (and the niceness of 4KiB aligning with common block/buffer sizes) but I have a use case where a slightly larger maximum size would be useful for me.

I propose either/both:

1. Increasing maximum direct response size to say 16KiB (an arbitrary number, way more than I need)
2. Making the maximum direct response size configurable (perhaps keeping the default as 4KiB)

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#:~:text=If%20a%20response%20body%20is,footprint%20from%20growing%20too%20large.

**Comment by htuch** [comment] 2021-01-15 13:57
This is a dupe of https://github.com/envoyproxy/envoy/issues/13422.

**Closed by htuch** 2021-01-15 13:57 UTC
Labels: enhancement, triage
