### ISSUE TITLE
Metrics are not emitted for track_cluster_stats.request_response_sizes

### ISSUE THREAD

**Issue by ovesh** [envoyproxy/envoy#16906] opened 2021-06-09 17:36 UTC
*Description*:
Using the latest stable build (1.18) we enabled `track_cluster_stats.request_response_sizes` on our clusters via CDS and confirmed that they are enabled by looking at /config_dump. I expected to see metrics being emitted (e.g `upstream_rs_body_size`), but instead seeing `No recorded values` for all the clusters under /stats. Requests are going through these clusters as usual, as evidenced by other metrics (e.g `upstream_rq_time`).

I expect to see values for `upstream_rs_body_size`, either in /stats or via the configured stats sink. 

*Repro steps*:
Add this to a cluster config via your CDS config source:
```
      "track_cluster_stats": {
       "request_response_sizes": true
      }
```

*Admin and Stats Output*:

I selected stats and config for a grpc cluster, but we are seeing the exact same issue for http as well.

/stats (partial):
```
cluster.grpc-mesh-reference-service.internal.upstream_rq_time: P0(1.0,1.0) P25(2.0208333333333335,2.038200806156101) P50(4.016666666666667,4.00328392909038) P75(5.045833333333333,5.0186422792824485) P90(5.098333333333334,6.000304568527919) P95(7.0475,7.06730627306273) P99(7.0895,13.607179487179495) P99.5(7.09475,16.157777777777785) P99.9(7.09895,22.938285714285616) P100(7.1,210.0)
cluster.grpc-mesh-reference-service.update_duration: No recorded values
cluster.grpc-mesh-reference-service.upstream_cx_connect_ms: P0(nan,1.0) P25(nan,1.025) P50(nan,1.05) P75(nan,1.075) P90(nan,1.09) P95(nan,1.095) P99(nan,1.099) P99.5(nan,1.0995) P99.9(nan,1.0999) P100(nan,1.1)
cluster.grpc-mesh-reference-service.upstream_cx_length_ms: No recorded values
cluster.grpc-mesh-reference-service.upstream_rq_body_size: No recorded values
cluster.grpc-mesh-reference-service.upstream_rq_headers_size: No recorded values
cluster.grpc-mesh-reference-service.upstream_rq_time: P0(1.0,1.0) P25(2.0208333333333335,2.038200806156101) P50(4.016666666666667,4.00328392909038) P75(5.045833333333333,5.0186422792824485) P90(5.098333333333334,6.000304568527919) P95(7.0475,7.06730627306273) P99(7.0895,13.607179487179495) P99.5(7.09475,16.157777777777785) P99.9(7.09895,22.938285714285616) P100(7.1,210.0)
cluster.grpc-mesh-reference-service.upstream_rs_body_size: No recorded values
cluster.grpc-mesh-reference-service.upstream_rs_headers_size: No recorded values
```
/server_info (partial ; the whole thing is over 1000 lines):
```
{
 "version": "98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "disabled",
 "command_line_options": {
  "base_id": "0",
  "use_dynamic_base_id": false,
  "base_id_path": "",
  "concurrency": 3,
  "config_path": "/tmp/envoyconfig288523076/config.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "ignore_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%l][%Y-%m-%d %T.%e][%t][%n] %v",
  "log_format_escaped": false,
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "drain_strategy": "Gradual",
  "mode": "Serve",
  "disable_hot_restart": true,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "disabled_extensions": [],
  "bootstrap_version": 0,
  "enable_fine_grain_logging": false,
  "socket_path": "@envoy_domain_socket",
  "socket_mode": 0,
  "enable_core_dump": false,
  "hidden_envoy_deprecated_max_stats": "0",
  "hidden_envoy_deprecated_max_obj_name_len": "0",
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "node": {
  "id": "removed",
  "cluster": "removed",
  "metadata": {
     "removed": "removed"
  },
  "dynamic_parameters": {},
  "user_agent_name": "envoy",
  "user_agent_build_version": {
   "version": {
    "major_number": 1,
    "minor_number": 18,
    "patch": 3
   },
   "metadata": {
    "build.type": "RELEASE",
    "revision.sha": "98c1c9e9a40804b93b074badad1cdf284b47d58b",
    "ssl.version": "BoringSSL",
    "revision.status": "Clean"
   }
  },
  "extensions": [
   {
    "name": "envoy.extensions.http.cache.simple",
    "category": "envoy.http.cache",
    "type_descriptor": "",
    "disabled": false
   },
   {
    "name": "preserve_case",
    "category": "envoy.http.stateful_header_formatters",
    "type_descriptor": "",
    "disabled": false
   },
...
   {
    "name": "envoy.watchdog.profile_action",
    "category": "envoy.guarddog_actions",
    "type_descriptor": "",
    "disabled": false
   }
  ],
  "client_features": [],
  "listening_addresses": [],
  "hidden_envoy_deprecated_build_version": "98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/Clean/RELEASE/BoringSSL"
 },
 "uptime_current_epoch": "3608s",
 "uptime_all_epochs": "3608s"
}
```

/clusters (partial):
```
grpc-mesh-reference-service::observability_name::grpc-mesh-reference-service
grpc-mesh-reference-service::outlier::success_rate_average::-1
grpc-mesh-reference-service::outlier::success_rate_ejection_threshold::-1
grpc-mesh-reference-service::outlier::local_origin_success_rate_average::-1
grpc-mesh-reference-service::outlier::local_origin_success_rate_ejection_threshold::-1
grpc-mesh-reference-service::default_priority::max_connections::1024
grpc-mesh-reference-service::default_priority::max_pending_requests::1024
grpc-mesh-reference-service::default_priority::max_requests::1024
grpc-mesh-reference-service::default_priority::max_retries::3
grpc-mesh-reference-service::high_priority::max_connections::1024
grpc-mesh-reference-service::high_priority::max_pending_requests::1024
grpc-mesh-reference-service::high_priority::max_requests::1024
grpc-mesh-reference-service::high_priority::max_retries::3
grpc-mesh-reference-service::added_via_api::true
grpc-mesh-reference-service::10.6.43.168:8085::cx_active::1
grpc-mesh-reference-service::10.6.43.168:8085::cx_connect_fail::0
grpc-mesh-reference-service::10.6.43.168:8085::cx_total::1
grpc-mesh-reference-service::10.6.43.168:8085::rq_active::0
grpc-mesh-reference-service::10.6.43.168:8085::rq_error::0
grpc-mesh-reference-service::10.6.43.168:8085::rq_success::15966
grpc-mesh-reference-service::10.6.43.168:8085::rq_timeout::0
grpc-mesh-reference-service::10.6.43.168:8085::rq_total::15966
grpc-mesh-reference-service::10.6.43.168:8085::hostname::
grpc-mesh-reference-service::10.6.43.168:8085::health_flags::healthy
grpc-mesh-reference-service::10.6.43.168:8085::weight::1
grpc-mesh-reference-service::10.6.43.168:8085::region::inf
grpc-mesh-reference-service::10.6.43.168:8085::zone::
grpc-mesh-reference-service::10.6.43.168:8085::sub_zone::
grpc-mesh-reference-service::10.6.43.168:8085::canary::false
grpc-mesh-reference-service::10.6.43.168:8085::priority::0
grpc-mesh-reference-service::10.6.43.168:8085::success_rate::-1.0
grpc-mesh-reference-service::10.6.43.168:8085::local_origin_success_rate::-1.0
```

**Comment by zuercher** [comment] 2021-06-10 17:49
Duplicate of #15879, being worked on in #15908

**Closed** 2021-06-10 17:49 UTC
Labels: bug, duplicate
