### ISSUE TITLE
envoy proxy validation context match OID (x509) ?

### ISSUE THREAD

**Issue by alnhk** [envoyproxy/envoy#30068] opened 2023-10-10 16:19 UTC
Team : similar to this below information, is there a way to check "OID" X509 number ?
 https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/securing#use-mutual-tls-mtls-to-enforce-client-certificate-authentication
for example, in nginx, we have this way using [subject alternative](https://github.com/nginx/njs-examples#reading-subject-alternative-from-client-certificate-httpcertssubject_alternative)
```
import x509 from 'x509.js';

function san(r) {
    var pem_cert = r.variables.ssl_client_raw_cert;
    if (!pem_cert) {
        return '{"error": "no client certificate"}';
    }

    var cert = x509.parse_pem_cert(pem_cert);

    // subjectAltName oid 2.5.29.17
    return JSON.stringify(x509.get_oid_value(cert, "2.5.29.17")[0]);
}

export default {san};
```

**Comment by kyessenov** [comment] 2023-10-10 17:47
Duplicate of https://github.com/envoyproxy/envoy/issues/14801?

**Closed** 2023-10-17 17:11 UTC
Labels: triage
