### ISSUE TITLE
upstream timeout during envoy start

### ISSUE THREAD

**Issue by jinuxstyle** [envoyproxy/envoy#2460] opened 2018-01-26 13:59 UTC
Hi

I am using rds/cds/sds for service discovery, and got a annoying issue that envoy took too much time to get all services discovered. The time is usually between the refresh_delay_ms and 2 * refresh_delay_ms set for sds cluster. For example, if it's set to 30s, the time will be in the range 30 ~ 60s. I looked at the stats of envoy and found the rq_timeout was not zero, and then i looked into the logs, and noticed a strange log that is "upstream timeout". What does it mean by "upstream timeout"? And if we look at the timestamp of the logs, it's strange why envoy printed out the timeout logs so shortly after starting sds refresh for a cluster?

I tried both v1.4 and v1.5, and got the same result. Below are the logs and stats I extracted from my testing.

### logs
```
[2018-01-26 13:38:33.812][3090][debug][upstream] source/common/upstream/sds_subscription.cc:93] starting sds refresh for cluster:  greeter                                                          
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:239] [C0][S18078983924612550549] cluster 'sds_cluster' match for URL '/v1/registration/greeter'                        
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   ':method':'GET'                                                                                    
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   ':path':'/v1/registration/greeter'                                                  
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   ':authority':'sds_cluster'                                                                         
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   'x-envoy-internal':'true'                                                                          
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   'x-forwarded-for':'172.17.0.6'                                                                     
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   'x-envoy-expected-rq-timeout-ms':'1000'                                                            
[2018-01-26 13:38:33.812][3090][debug][router] source/common/router/router.cc:284] [C0][S18078983924612550549]   ':scheme':'http'  

...


[2018-01-26 13:38:33.819][3090][debug][router] source/common/router/router.cc:424] [C0][S18078983924612550549] upstream timeout                                                                                     
[2018-01-26 13:38:33.819][3090][debug][router] source/common/router/router.cc:850] [C0][S18078983924612550549] cancelling pool request                                                                              
[2018-01-26 13:38:33.819][3090][debug][pool] source/common/http/http1/conn_pool.cc:193] cancelling pending request 

```

### envoy stats:
```
sds_cluster::192.168.26.244:1949::cx_active::63
sds_cluster::192.168.26.244:1949::cx_connect_fail::0
sds_cluster::192.168.26.244:1949::cx_total::95
sds_cluster::192.168.26.244:1949::rq_active::0
sds_cluster::192.168.26.244:1949::rq_error::32
sds_cluster::192.168.26.244:1949::rq_success::96
sds_cluster::192.168.26.244:1949::rq_timeout::32               <<<< notice the number
sds_cluster::192.168.26.244:1949::rq_total::128
```

**Comment by mattklein123** [comment] 2018-01-26 16:18
It means the request timed out. See https://github.com/envoyproxy/envoy/issues/1833

**Comment by jinuxstyle** [comment] 2018-01-29 02:36
Thanks. The information is helpful. It looks reasonable that it's possible to get request timeout when envoy needs to refresh hundreds of clusters via sds concurrently in 1 second. I will look into it further to figure out why the timeout happens exactly.

**Comment by jinuxstyle** [comment] 2018-01-29 09:55
Another question, during envoy starting, how long would it take to send the first sds request after getting the clusters from cds server? In our case, it takes 8 ~ 9 seconds and we have 150 clusters in total. I don't know what envoy is doing during that period.

**Comment by jinuxstyle** [comment] 2018-01-29 12:36
The following logs shows the time interval (here 8 seconds) that was taken by the envoy between getting the cds result and starting first sds refreshing.
```
[2018-01-29 12:24:36.424][1024][debug][upstream] source/common/upstream/cds_subscription.cc:43] cds: parsing response 
...
[2018-01-29 12:24:44.821][1024][debug][upstream] source/common/upstream/sds_subscription.cc:93] starting sds refresh for cluster: greeter
```

So my question is why envoy would take such a long time for parsing and handling cds result? And is there anyway to reduce the time?

**Comment by mattklein123** [comment] 2018-01-29 18:25
@jinuxstyle can't say, can you provide the intermediate logs. Perhaps DNS resolution in between or something else?

**Comment by jinuxstyle** [comment] 2018-01-30 02:09
The intermediate logs are all about adding/updating clusters like following:
```
[2018-01-29 12:24:36.424][1024][debug][upstream] source/common/upstream/cds_subscription.cc:43] cds: parsing response 
[2018-01-29 12:24:36.983][1024][info][upstream] source/common/upstream/cluster_manager_impl.cc:357] add/update cluster alpha.xlsoa.core.portal@__default                     
[2018-01-29 12:24:36.983][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:370] adding TLS cluster alpha.xlsoa.core.portal@__default 
[2018-01-29 12:24:36.984][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:60] cm init: adding: cluster=alpha.xlsoa.core.portal@__default primary=0 secondary=1
1-29 12:24:37.075][1024][info][upstream] source/common/upstream/cluster_manager_impl.cc:357] add/update cluster alpha.xlsoa.core.portal                                      
1-29 12:24:37.075][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:370] adding TLS cluster alpha.xlsoa.core.portal                                     
1-29 12:24:37.075][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:60] cm init: adding: cluster=alpha.xlsoa.core.portal primary=0 secondary=2          
1-29 12:24:37.075][1024][debug][upstream] source/common/upstream/cds_api_impl.cc:56] cds: add/update cluster 'alpha.xlsoa.core.portal' 

...
...

[2018-01-29 12:24:44.773][1024][debug][upstream] source/common/upstream/cds_api_impl.cc:56] cds: add/update cluster 'xllive.service.coinnew@v5.2.1'                          
[2018-01-29 12:24:44.821][1024][info][upstream] source/common/upstream/cluster_manager_impl.cc:357] add/update cluster xllive.service.coinnew                                
[2018-01-29 12:24:44.821][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:370] adding TLS cluster xllive.service.coinnew                               
[2018-01-29 12:24:44.821][1024][debug][upstream] source/common/upstream/cluster_manager_impl.cc:60] cm init: adding: cluster=xllive.service.coinnew primary=0 secondary=149  
[2018-01-29 12:24:44.821][1024][debug][upstream] source/common/upstream/cds_api_impl.cc:56] cds: add/update cluster 'xllive.service.coinnew'                                 
[2018-01-29 12:24:44.821][1024][info][upstream] source/common/upstream/cluster_manager_impl.cc:109] cm init: initializing secondary clusters                                 
[2018-01-29 12:24:44.821][1024][debug][upstream] source/common/upstream/sds_subscription.cc:93] starting sds refresh for cluster: alpha.xlsoa.core.portal@__default
```

**Comment by jinuxstyle** [comment] 2018-01-30 06:29
And DNS resolution should not be the cause because I already changed the service discovery type for resolving the sds and cds clusters to be static in my test. 

```
   "sds" :                                                                                                                                                                  
    {                                                                                                                                                                        
            "cluster":                                                                                                                                                       
            {                                                                                                                                                                
                    "name": "sds_cluster",                                                                                                                                   
                    "type": "static",                                                                                                                                        
                    "connect_timeout_ms": 10000,                                                                                                                             
                    "lb_type": "round_robin",                                                                                                                                
                    "hosts": [{"url": "tcp://192.168.26.244:1950"}]                                                                                                          
            },                                                                                                                                                               
            "refresh_delay_ms": 30000                                                                                                                                        
    },                                                                                                                                                                       
    "cds" :                                                                                                                                                                  
    {                                                                                                                                                                        
            "cluster":                                                                                                                                                       
            {                                                                                                                                                                
                    "name": "cds_cluster",                                                                                                                                   
                    "type": "static",                                                                                                                                        
                    "connect_timeout_ms": 10000,                                                                                                                             
                    "lb_type": "round_robin",                                                                                                                                
                    "hosts": [{"url": "tcp://192.168.26.244:1950"}]                                                                                                          
            },                                                                                                                                                               
            "refresh_delay_ms": 30000                                                                                                                                        
    }      

```

**Comment by mattklein123** [comment] 2018-01-30 16:07
This is very likely related to startup speed. What version of Envoy are you using? If 1.5.0 please try master as it has one major thing fixed (stat allocation speed). @jmarantz is also working on the other big one (tag extraction via regex).

**Comment by jmarantz** [comment] 2018-01-30 17:41
Would it be possible to include the entire config file so I can repro?  I'd like to see if there's a real-world repro to the slow-regex problem described in https://github.com/envoyproxy/envoy/issues/2373

**Comment by jinuxstyle** [comment] 2018-02-01 07:32
I tried a newer version with envoy docker image envoyproxy/envoy:61b38528d7e46ced9d749d278ba185332310ca95, it still takes 6 seconds to parsing the cds clusters before sending out the first sds request.
```
envoy  version: 61b38528d7e46ced9d749d278ba185332310ca95/1.6.0-dev/Clean/RELEASE
```

**Comment by jinuxstyle** [comment] 2018-02-01 07:35
Here is the entire configure file:
```
{
  "listeners": [
    {
      "address": "tcp://0.0.0.0:9102",
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "egress_http",
            "tracing": {
                "operation_name": "egress"
            },
            "rds" :
            {
                "cluster" : "rds_cluster",
                "route_config_name" : "egress_route",
                "refresh_delay_ms" : 30000
            },
            "filters": [
              {
                "type": "decoder",
                "name": "router",
                "config": {}
              }
            ],
            "access_log" :
            [
                {"path" : "/dev/stdout"}
            ]
          }
        }
      ]
    }
  ],
 "admin":
  {
    "access_log_path": "/dev/null",
    "address": "tcp://0.0.0.0:9103"
  },
  "cluster_manager": {
    "clusters":
    [
          {
            "name": "rds_cluster",
            "type": "static",
            "connect_timeout_ms": 10000,
            "lb_type": "round_robin",
            "hosts": [{"url": "tcp://192.168.26.244:1950"}]
          }
    ],
    "sds" :
    {
            "cluster":
            {
                    "name": "sds_cluster",
                    "type": "static",
                    "connect_timeout_ms": 10000,
                    "lb_type": "round_robin",
                    "hosts": [{"url": "tcp://192.168.26.244:1950"}]
            },
            "refresh_delay_ms": 30000
    },
  "cds" :
    {
            "cluster":
            {
                    "name": "cds_cluster",
                    "type": "static",
                    "connect_timeout_ms": 10000,
                    "lb_type": "round_robin",
                    "hosts": [{"url": "tcp://192.168.26.244:1950"}]
            },
            "refresh_delay_ms": 30000
    }
  }
}
```

**Comment by jmarantz** [comment] 2018-02-01 12:43
Thanks for the config.  Looks like I need to invoke Envoy with --service-cluster and --service-node to repro.  Do you have recommendations for those values? 

Sorry if this is obvious; I'm kind of learning Envoy from the inside out.  Thanks!

**Comment by mattklein123** [comment] 2018-02-02 18:13
@jinuxstyle how many clusters are you returning from CDS? @jmarantz I'm not sure the raw config is config to be that useful. The issue is when processing the CDS response, which is basically the same as starting up with a bunch of static clusters. I'm still a little unsure if this is definitely the same issue, as unless there are thousands of clusters 6-8 seconds seems pretty long.

**Comment by jmarantz** [comment] 2018-02-02 18:52
Yes I think you're right, Matt.  My startup time on this input was very fast; I think to repro I'd need to mock out the CDS context to repro this.

**Comment by mattklein123** [comment] 2018-03-13 19:29
I believe this is being covered by all of the perf work that @jmarantz is doing and other tickets. I'm going to close this out and we can revisit if that work when it lands does not fix the issues.

**Closed by mattklein123** 2018-03-13 19:29 UTC
Labels: question

**Comment by jmarantz** [comment] 2018-03-13 22:36
@jinuxstyle would you be able to re-run with the current 'master'?  Since Feb 1 there have been a number of speedups deployed.  It would be good to confirm whether they address your startup flow, as I was not able to repro.

**Comment by jinuxstyle** [comment] 2018-03-14 02:57
It worked perfectly now with the latest image I tried, which is envoyproxy/envoy:fd44fd6051f5d1de3b020d0e03685c24075ba388.

Now, the rds/cds/sds data can be fetched and processed within milliseconds rather than seconds required before. And the request timeout no longer appeared during my test. The improvement looks amazing. Thanks.

Some logs
```
...
[2018-03-14 02:39:56.323][48][debug][upstream] source/common/upstream/cds_subscription.cc:33] cds: starting request 
...
[2018-03-14 02:39:56.447][48][debug][upstream] source/common/upstream/sds_subscription.cc:94] starting sds refresh for cluster
...
```

```
sds_cluster::10.10.133.102:1949::cx_active::147
sds_cluster::10.10.133.102:1949::cx_connect_fail::0
sds_cluster::10.10.133.102:1949::cx_total::147
sds_cluster::10.10.133.102:1949::rq_active::0
sds_cluster::10.10.133.102:1949::rq_error::0
sds_cluster::10.10.133.102:1949::rq_success::147
sds_cluster::10.10.133.102:1949::rq_timeout::0
sds_cluster::10.10.133.102:1949::rq_total::147
sds_cluster::10.10.133.102:1949::health_flags::healthy
```
