### ISSUE TITLE
Custom headers are all converted to lowercase

### ISSUE THREAD

**Issue by sunnoy** [envoyproxy/envoy#15477] opened 2021-03-13 04:22 UTC
*Title*: *Custom headers are all converted to lowercase*

*Description*:
https://github.com/istio/istio/issues/31360

Does envoy support this ？

**Comment by wbpcode** [comment] 2021-03-15 03:24
Nope. And as @howardjohn said, at this point, fixing the application to ensure that it is case insensitive would be a little better.

**Comment by jmarantz** [comment] 2021-03-15 18:25
Duplicate of https://github.com/envoyproxy/envoy/issues/14363

**Closed by jmarantz** 2021-03-15 18:25 UTC
Labels: enhancement, triage
