### ISSUE TITLE
Retry on mid-stream resets result in 503 but no retry

### ISSUE THREAD

**Issue by liviu-cristea** [envoyproxy/envoy#5876] opened 2019-02-07 19:44 UTC
*Title*: *One line description*

*Description*:
>I have a fleet on Envoy running in Docker calling into upstream which is a Google Cloud hosted service, via h2.
Envoy periodically (very hard to repro) gets 503 with upstream_cx_destroy_remote_with_active_rq  being bumped up.
I tried using https://www.envoyproxy.io/docs/envoy/v1.9.0/configuration/http_filters/router_filter#config-http-filters-router-x-envoy-retry-on retriable-status-codes, made 503 a retryable error code, however the retry does not take place.
The retry does take place only if I explicitly make upstream send the 503 (without bumping upstream_cx_destroy_remote_with_active_rq)

Is this expected? How can I make Envoy retry in this case? 

This only happens once every 24-36 hours for a 200 QPS load. But when it does hundreds of requests fail at a time, causing a big damage. Turning out debug logs might slow everything down. Should I not be concerned about the IO/CPU increase and the effect of Envoy overhead on redirecting those requests?
Also, 5xx as a retry policy does not work. I explicitly want 503 to be retried on, so in 1.9 I am doing this but no effect for Envoy generated 503s as a result of upstream_cx_destroy_remote_with_active_rq. How do I proceed to give you meaningful info?

                          prefix: "/"
                        route:
                          timeout: 120s
                          cluster: test_cluster
                          host_rewrite: "x.y.com"
                          retry_policy:
                            retry_on: connect-failure,refused-stream,retriable-status-codes
                            num_retries: 2
                            retriable_status_codes: [503]

From Harvey Tuch:

Looking at RetryStateImpl::wouldRetryFromReset() and RetryStateImpl::wouldRetry() I'm not sure if they're handling the case of a mid-stream reset. Please file a GH issue and we can discuss further there.

[optional *Relevant Links*:]
> https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/envoy-users/fV87_K4cMks/LvGkWbSZGgAJ
> is it same as https://github.com/envoyproxy/envoy/issues/5023 ?

**Comment by htuch** [comment] 2019-02-08 00:04
I think this is a bug, @mattklein123?

**Comment by ramaraochavali** [comment] 2019-02-08 04:46
We have similar situation recently. We get `upstream connect error or disconnect/reset before headers` from the Client Envoy - But I am 100% certain that it is not a connect error because 5xx stat is not incremented but `rx_reset` stat is incremented in the upstream cluster. Would this fix cover that as well or do we need a separate retry policy for that?

**Comment by mattklein123** [comment] 2019-02-08 05:32
It is by design that we don't support mid stream retry. Once response headers have been sent there is nothing we can do that makes sense other than reset.

**Comment by htuch** [comment] 2019-02-08 05:35
@mattklein123 I think my use "mid-stream" above was a mislead; the OP describes a situation in which they see `upstream_cx_destroy_remote_with_active_rq` bumped and a 503 returned to client, but no ability to retry.  By mid-stream, I meant that we had an active request open with the upstream, not that we had started to stream back to client.

**Comment by liviu-cristea** [comment] 2019-02-08 05:35
How can we workaround this? upstream_cx_destroy_remote_with_active_rq causes requests to fail with 503 in Envoy and there is no way to retry. 
Does the reset that happen mean that the connection is re-established? 
If yes, that explains why this is always transient.

**Comment by mattklein123** [comment] 2019-02-08 05:38
Assuming the response has not been started, we should be able to retry. We would need to look at the existing retry policies and see why they don't cover this case and potentially add a new one. I'm not sure if this is a bug or an enhancement request without understanding more details.

**Comment by liviu-cristea** [comment] 2019-02-08 05:45
@ramaraochavali I don't think it's the same because for me 5xx counter and 503 does get bumped up.

@mattklein123 happy to provide more details. 
- upstream_rq_pending_failure_eject gets bumped
- upstream_cx_destroy_remote_with_active_rq gets bumped
- 5xx and 503 get bumped
- no other correlations that i can tell so far. upstream_cx_close_notify is happening quite often, and sometimes at the same time with this. I suspect the connection is restablished but those requests are gone forever :( 

I can only retry on 503, and the way I mentioned earlier was introduced in 1.9 and is the only way, but the issue still reproduces.

We consider this a pretty important bug because we use h2 to a Google system that cuts our connections quite often looks like, so it'd be nice to have Envoy retry as we can't control the behavior of that system.

**Comment by liviu-cristea** [comment] 2019-02-08 05:46
I don't think the response has been started. It seems to me Envoy has the opportunity to retry. It handles this by just returning a 503 for all those requests that got affected by that connection upstream_cx_destroy_remote_with_active_rq

**Comment by liviu-cristea** [comment] 2019-02-08 05:50
Once we have a fix we can confirm it works as this reproes every 1-2 days. So I can offer that.
But when it does repro, we get paged because of all the request failures.

**Comment by ramaraochavali** [comment] 2019-02-08 09:29
@liviu-cristea  yeah. Thank you. It is not the same as what we are seeing.

@mattklein123  In our case we do see retries happening - `upstream_rq_retry` is incremented but `retry_success` is not incremented. The server side Envoy shows 503 and resets to local service instance. However client is not seeing 503s at the end of retry cycle which is kind of surprising to me. 
Looking at the code when we get the `upstream connect error - disconnect/reset before headers` log line, we should get the 503 as per 
https://github.com/envoyproxy/envoy/blob/8c6bf40042543713eb7493e0d4ff29b312c78772/source/common/router/router.cc#L596

Any pointers on what is causing the 503s not being shown on the client?

**Comment by liviu-cristea** [comment] 2019-02-08 17:28
@ramaraochavali please cut a new issue for this.

I don't want to discuss 2 separate bugs/behaviors on the same issue.

**Comment by ramaraochavali** [comment] 2019-02-09 03:10
@liviu-cristea Yeah. Makes sense, was thinking of doing the same.

**Comment by mattklein123** [comment] 2019-02-09 21:35
I'm switching this over from bug to enhancement request. I'm pretty sure if you retried on `5xx` you would see a retry (https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L278), but you are only retrying on `connect-failure,refused-stream,retriable-status-codes`, which does not generically include this case, and I don't think we have a retry policy which retries on the reset status code you are seeing (I'm guessing `ConnectionTermination`).

This might need a bit more debugging but I think we probably need a new retry type here to cover this case.

**Comment by liviu-cristea** [comment] 2019-02-10 03:27
@mattklein123 please keep this open for a few more days. I will do the retry on 5xx to confirm. If it still doesn't work, then this can continue to stay a bug, correct?

**Comment by mattklein123** [comment] 2019-02-10 16:32
> If it still doesn't work, then this can continue to stay a bug, correct?

No, it's not a bug. We would need a new retry policy option to cover the type of error you are seeing if for some reason you cannot use the 5xx policy or another policy that covers it.

**Comment by liviu-cristea** [comment] 2019-02-10 17:17
I see. @mattklein123 how come does 503 as a retriable status code not cover this? In my mind, 5xx is a superset of retriable-status-code where you put 503,502,504 in it, etc.

**Comment by liviu-cristea** [comment] 2019-02-10 18:26
Looking at the comment, I assume this is what you were refering to @mattklein123 ? https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L279

Basically the retry on reset which is baked into 5xx or gateway error. So I can try one or the other, until the policy in the comments gets added.

I might be jumping to conclusions to quickly, but the reason why retry from status codes doesn't work here is because envoy resets the headers when upstream reset happens, so that code path doesn't get hit? https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L210

**Comment by mattklein123** [comment] 2019-02-11 02:26
> @mattklein123 how come does 503 as a retriable status code not cover this? In my mind, 5xx is a superset of retriable-status-code where you put 503,502,504 in it, etc. In other words, shouldn't 503 cover this case since that's what Envoy returns? If no then why not? Is it because this only applies for 503 upstream returns?

I think it should cover this case, agreed. PRs appreciated. Should be a very simple change.

> I might be jumping to conclusions to quickly, but the reason why retry from status codes doesn't work here is because envoy resets the headers when upstream reset happens, so that code path doesn't get hit? https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L210

Correct. I would just retry on 5xx or gateway error if you can, otherwise getting this to work for you will require some type of code change.

**Comment by liviu-cristea** [comment] 2019-02-11 18:25
I am testing gateway-error right now. Results in 24 hours. If it works, then that tells me what code paths we need to hit in order for retriable-status-codes to work.
If we make the retriable-status-codes work, it might become a breaking change for the ones who already took a dependnecy on the fact that retries are made *only when* upstream explicitly returns that status code. If I make the PR change, then we also include the cases when ConnectionTerminated and other conditions that 5xx and gateway-error already cover. Hope that's ok. Let's have these discussions once I yank out the PR.

**Comment by liviu-cristea** [comment] 2019-02-11 21:31
I can confirm gateway-error fixes it. 

Thinking out loud:

I will look into making the PR that makes sure retriable-status-codes also covers this case.
I'm on the fence to be honest because then retriable-status-codes of 502,503,504 would become identical with gateway-error. Why have both options then? Why not deprecate gateway-error?

I'm thinking of reset-error to be explicit (finer grained controls rather than one option that does a lot and documents little)

**Comment by mattklein123** [comment] 2019-02-11 21:44
> I'm on the fence to be honest because then retriable-status-codes of 502,503,504 would become identical with gateway-error. Why have both options then? Why not deprecate gateway-error?

I agree it's redundant, but TBH I don't think it's worth the deprecation churn in this case.

**Comment by htuch** [comment] 2019-04-15 15:56
Reopened based on https://github.com/envoyproxy/envoy/issues/6575

**Comment by jaygorrell** [comment] 2019-04-15 22:50
@mattklein123 does https://github.com/envoyproxy/envoy/pull/6578 make this a non-issue?

**Comment by mattklein123** [comment] 2019-04-16 17:48
@jaygorrell not sure would have to page back in this issue which I don't have time for right now. Is it possible for someone to test against master and see if this is now resolved or do the analysis?

**Comment by mattklein123** [comment] 2019-04-27 19:49
Closing in favor of https://github.com/envoyproxy/envoy/issues/6726

**Closed by mattklein123** 2019-04-27 19:49 UTC
Labels: enhancement
