### ISSUE TITLE
multi-value support in header match

### ISSUE THREAD

**Issue by yogeshkrbhat** [envoyproxy/envoy#29317] opened 2023-08-29 11:29 UTC
my header is as follows:

```console
curl --header "x-custom-route-svc:abcxyz:demo-service1.ns1.cluster.local" --header "x-custom-route-svc:mnop:demo-service2.ns2.cluster.local"  URL
```
Format - x-custom-route-svc:[token1:service1,token2:service2]

And envoy route config:
```yaml
                 routes:
                  - match: 
                      prefix: "/"
                      headers:
                        - name: "x-custom-route-svc"
                          contains_match: "demo-service2.ns2.cluster.local"
```
                          
here the header    "x-custom-route-svc" is a multi-value with different service names and user-token. Since user-token is varying in every request, I would like to do substring match as above.

Unfortunately, contains_match does substring match with only first value. 

any suggestions for this?

_Originally posted by @yogeshkrbhat in https://github.com/envoyproxy/envoy/issues/13751#issuecomment-1694217102_

**Comment by phlax** [comment] 2023-08-29 11:33
@yogeshkrbhat is this just a duplicate of #13571 - if so i think focus attention/questions there

**Comment by phlax** [comment] 2023-08-29 13:59
updated/fixed comment link/ref

**Comment by yogeshkrbhat** [comment] 2023-08-29 14:07
sorry, i didn't find anything related to multi-value matching

**Comment by phlax** [comment] 2023-08-29 14:10
![image](https://github.com/envoyproxy/envoy/assets/454682/dfa632f6-f840-4921-bfb8-73ca769c7d84)


can we close this please - and direct further comments to above ticket, which includes history and already has the attention of interested parties

**Comment by phlax** [comment] 2023-08-29 14:11
unless im not understanding correctly some nuance - in which case we can track this separately - but it would be good to clarify why

**Comment by yogeshkrbhat** [comment] 2023-08-29 14:14
ok, now i see the correct duplicate link you have edited in the comment. In fact, i added my first query there although i was not sure if #13751 is the correct one. 
if you think it can be discussed further there, you may close this

**Closed** 2023-08-29 14:18 UTC
Labels: duplicate, triage
