### ISSUE TITLE
problem about Compiling envoy by bazel

### ISSUE THREAD

**Issue by zfdu** [envoyproxy/envoy#4011] opened 2018-08-01 06:47 UTC
**Issue Template**

*Title*: *error about compiling envoy by bazel*

*Description*:
>when i compile the envoy using"bazel build",it appears an error:

Error: failed to load skylark extension ‘//bazel:repositories.bzl’.

anybody know what is the reason why this load error happened?
please help me !!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by julia-stripe** [comment] 2018-08-01 14:31
We're running into the same issue. This is caused by this commit: https://github.com/envoyproxy/envoy/commit/e89c9d6f23371971120e4c91119cdafe65d3a8df -- before that commit, Envoy built correctly with Bazel. That commit introduces an invalid `repositories.bzl` file.

Here are steps to reproduce + the output I see on my laptop. 

```
$ docker run --rm -it --volume=$PWD:/src envoyproxy/envoy-build
root@78719111a551:/# cd /src
root@78719111a551:/src# bazel build -c dbg //source/exe:envoy-static.stamped
.......................................
ERROR: /src/bazel/repositories.bzl:10:1: file '@bazel_tools//tools/cpp:windows_cc_configure.bzl' does not contain symbol 'setup_vc_env_vars'
ERROR: error loading package '': Extension file 'bazel/repositories.bzl' has errors
ERROR: error loading package '': Extension file 'bazel/repositories.bzl' has errors
INFO: Elapsed time: 1.680s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by dio** [comment] 2018-08-01 14:38
@julia-stripe do you think upgrading bazel to >= 0.13 will fix that? 

Since https://blog.bazel.build/2018/05/02/bazel-0.13.html has `setup_vc_env_vars`.

**Comment by julia-stripe** [comment] 2018-08-01 16:27
@dio I imagine that'll fix it. Thanks!

**Comment by julia-stripe** [comment] 2018-08-31 17:06
Can confirm that upgrading Bazel fixed this.

**Comment by lizan** [comment] 2018-08-31 19:47
closing as answered.

**Closed** 2018-08-31 19:47 UTC
Labels: question
