### ISSUE TITLE
tools/vscode/refresh_compdb.sh  failed

### ISSUE THREAD

**Issue by jason9015** [envoyproxy/envoy#28971] opened 2023-08-11 07:13 UTC
version:release/v1.27

tools/vscode/refresh_compdb.sh failed

ERROR: Analysis of target '//contrib/cryptomb/private_key_providers/source:config_envoy_extension' failed; build aborted:

logs：
INFO: Build options --//tools/api_proto_plugin:default_type_db_target, --build_runfile_links, and --compilation_mode have changed, discarding analysis cache.
ERROR: /build/.cache/bazel/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: in cc_toolchain_suite rule @envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain: cc_toolchain_suite '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' does not contain a toolchain for cpu 'aarch64'
ERROR: /build/.cache/bazel/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: Analysis of target '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' failed
ERROR: Analysis of target '//tools/proto_format:proto_sync' failed; build aborted: 
INFO: Elapsed time: 0.217s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 951 targets configured)
ERROR: Build failed. Not running target
$TEST_TMPDIR defined: output root default is '/build/envoy-compdb' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
ERROR: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: in cc_toolchain_suite rule @envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain: cc_toolchain_suite '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' does not contain a toolchain for cpu 'aarch64'
ERROR: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: Analysis of target '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' failed
INFO: Repository kafka_server_binary instantiated at:
  /workspaces/envoy/WORKSPACE:13:19: in <toplevel>
  /workspaces/envoy/bazel/repositories.bzl:336:16: in envoy_dependencies
  /workspaces/envoy/bazel/repositories.bzl:1337:26: in _kafka_deps
  /workspaces/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository org_boost instantiated at:
  /workspaces/envoy/WORKSPACE:13:19: in <toplevel>
  /workspaces/envoy/bazel/repositories.bzl:302:15: in envoy_dependencies
  /workspaces/envoy/bazel/repositories.bzl:575:26: in _org_boost
  /workspaces/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository go_linux_amd64 instantiated at:
  /workspaces/envoy/WORKSPACE:25:25: in <toplevel>
  /workspaces/envoy/bazel/dependency_imports.bzl:30:27: in envoy_dependency_imports
  /workspaces/envoy/bazel/dependency_imports.bzl:153:20: in envoy_download_go_sdks
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/io_bazel_rules_go/go/private/sdk.bzl:303:25: in go_download_sdk
Repository rule go_download_sdk_rule defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/io_bazel_rules_go/go/private/sdk.bzl:133:39: in <toplevel>
ERROR: Analysis of target '//contrib/cryptomb/private_key_providers/source:config_envoy_extension' failed; build aborted: 
INFO: Elapsed time: 10.167s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (946 packages loaded, 4861 targets configured)
    currently loading: @base_pip3_ply// ... (7 packages)
    Fetching repository @com_github_cncf_xds_go; running Gazelle 4s
    Fetching https://archive.apache.org/dist/kafka/3.4.0/kafka_2.13-3.4.0.tgz; 976.4 KiB (999,882B)
    Fetching https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz
    Fetching https://dl.google.com/go/go1.18.linux-amd64.tar.gz
Traceback (most recent call last):
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 129, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 25, in generate_compilation_database
    subprocess.check_call([args.bazel, *bazel_startup_options, "build"] + bazel_options + [
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//contrib/...']' returned non-zero exit status 1.

**Comment by jason9015** [comment] 2023-08-11 07:14
<img width="1376" alt="image" src="https://github.com/envoyproxy/envoy/assets/22276078/70249950-2c06-4f23-8ada-04507a8e84bf">

**Comment by phlax** [comment] 2023-08-11 10:10
closing this as a duplicate of #28895

**Closed by phlax** 2023-08-11 10:10 UTC
Labels: triage
