### ISSUE TITLE
flake in GetAndCloseStreamWithTracing

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#36467] opened 2024-10-07 13:57 UTC
test touched in https://github.com/envoyproxy/envoy/pull/33665 so @cainelli can you take a look?

https://github.com/envoyproxy/envoy/actions/runs/11193737190/job/31119411411

[ RUN      ] IpVersionsClientTypeDeferredProcessing/ExtProcIntegrationTest.GetAndCloseStreamWithTracing/IPv4_EnvoyGrpc_WithDeferredProcessing
test/extensions/filters/http/ext_proc/tracer_test_filter.cc:52: Failure
Expected equality of these values:
  want
    Which is: "0"
  got
    Which is: ""
grpc.status_code: 0 not found in tags:
component: proxy
status: canceled
upstream_address: ext_proc_server_0
upstream_cluster: ext_proc_server_0

Stack trace:
  0x7f21ffe377ce: Envoy::Extensions::HttpFilters::ExternalProcessing::Span::~Span()
  0x7f21ffe379a9: Envoy::Extensions::HttpFilters::ExternalProcessing::Span::~Span()
  0x7f21954c5a7e: (unknown)
  0x7f21954c59d0: (unknown)
  0x7f219543405b: (unknown)
  0x7f2195436300: Envoy::Grpc::AsyncStreamImpl::~AsyncStreamImpl()
  0x7f2195436379: Envoy::Grpc::AsyncStreamImpl::~AsyncStreamImpl()
  0x7f210c9e692e: (unknown)
  0x7f210c969a60: (unknown)
  0x7f210c957dfb: Envoy::Event::DispatcherImpl::clearDeferredDeleteList()
  0x7f210c95f5fb: (unknown)
  0x7f210c95f5a7: (unknown)
  0x7f210c95f53f: (unknown)
  0x7f210c95f4ff: (unknown)
  0x7f210c95e12b: (unknown)
  0x16b7ef6: (unknown)
  0x16b7407: std::__1::function<>::operator()()
  0x7f20ed6c5bd4: (unknown)
  0x7f20ed6c5b89: (unknown)
  0x1a0390c: (unknown)
  0x19ff468: (unknown)
  0x19fe56c: event_base_loop
  0x7f20eda94b7e: Envoy::Event::LibeventScheduler::run()
  0x7f210c9592fb: Envoy::Event::DispatcherImpl::run()
  0x7f21bf8006f7: Envoy::Server::WorkerImpl::threadRoutine()
  0x7f21bf808f2a: (unknown)
  0x7f21bf808ec7: (unknown)
  0x7f21bf808e5f: (unknown)
  0x7f21bf808e1f: (unknown)
  0x7f21bf807b7b: (unknown)
  0x16b7ef6: (unknown)
  0x16b7407: std::__1::function<>::operator()()
  0x7f20d147df8a: (unknown)
  0x7f20d147dee5: (unknown)
  0x7f20c2988609: start_thread

test/integration/fake_upstream.cc:795: Failure
Failed
Please don't waitForHttpConnection with a 5s timeout if failure is expected

Stack trace:
  0x7f21deab35c2: Envoy::FakeUpstream::waitForHttpConnection()
  0x15cfc1b: (unknown)
  0x140f139: (unknown)
  0x7f20c338ea4d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f20c337522e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f20c335cb1d: testing::Test::Run()
  0x7f20c335d60e: testing::TestInfo::Run()
... Google Test internal frames ...

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc:281: Failure
Value of: fake_upstreams_[0]->waitForHttpConnection(*dispatcher_, fake_upstream_connection_)
  Actual: false (Timed out waiting for new connection.)
Expected: true
Stack trace:
  0x15cfcb5: (unknown)
  0x140f139: (unknown)
  0x7f20c338ea4d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f20c337522e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f20c335cb1d: testing::Test::Run()
  0x7f20c335d60e: testing::TestInfo::Run()
... Google Test internal frames ...

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc:277: Failure
Expected equality of these values:
  std::to_string(status_code)
    Which is: "200"
  response.headers().getStatusValue()
    Which is: "504"
Stack trace:
  0x15d08a8: (unknown)
  0x140f17c: (unknown)
  0x7f20c338ea4d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f20c337522e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f20c335cb1d: testing::Test::Run()
  0x7f20c335d60e: testing::TestInfo::Run()
... Google Test internal frames ...

[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_no_extension_lookup_by_name to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_defer_processing_backedup_streams to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_quic_always_support_server_preferred_address to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_runtime_initialized to: false
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_no_extension_lookup_by_name to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_defer_processing_backedup_streams to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_quic_always_support_server_preferred_address to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_runtime_initialized to: false
[  FAILED  ] IpVersionsClientTypeDeferredProcessing/ExtProcIntegrationTest.GetAndCloseStreamWithTracing/IPv4_EnvoyGrpc_WithDeferredProcessing, where GetParam() = ((4-byte object <00-00 00-00>, 4-byte object <00-00 00-00>), true) (31694 ms)

**Comment by cainelli** [comment] 2024-10-07 20:02
@alyssawilk this is a duplicate of https://github.com/envoyproxy/envoy/issues/36041 which I need to dig into.

**Closed** 2024-10-08 13:29 UTC
Labels: area/test flakes
