### ISSUE TITLE
Zipkin tracer always sets http schema for the http.url 

### ISSUE THREAD

**Issue by lmolkova** [envoyproxy/envoy#1904] opened 2017-10-19 18:36 UTC
https://github.com/envoyproxy/envoy/blob/22495511076a0904d5465413e706d73d82fe79f6/test/common/tracing/http_tracer_impl_test.cc#L239

For https urls, envoy reports 'http'.

While it pretty minor, it could be misleading

**Comment by mattklein123** [comment] 2017-10-19 20:25
@objectiser @rshriram ^

**Comment by objectiser** [comment] 2017-10-20 07:41
Not sure I see the issue - this is just a test which happens to use the `http` protocol value. The protocol used in the `path_prefix` matches the `x-forwarded-proto` header used in the test.

The protocol used in building the actual `http.url` tag is obtained from the [request headers](https://github.com/envoyproxy/envoy/blob/master/source/common/tracing/http_tracer_impl.cc#L38), so could be `https`.

Do you have a reproducer demonstrating that this is not actually working as expected?

**Comment by mattklein123** [comment] 2017-10-20 16:16
Ah thanks @objectiser. Sorry did not look at this in detail.

**Comment by mattklein123** [comment] 2017-10-24 00:14
Closing as answered. Please reopen if it looks like there is an issue here.

**Closed by mattklein123** 2017-10-24 00:14 UTC
Labels: question, tracing
