### ISSUE TITLE
Dynamically route prefix_rewrite

### ISSUE THREAD

**Issue by Bhawna4tech** [envoyproxy/envoy#4274] opened 2018-08-28 06:23 UTC
**How to dynamically route prefix_rewrite**

*Description*:
>I want to redirect an incoming request to envoy to one of my services. 
For example: I have two services bookings and orders. I want to route to orders/{valueGiven}/sometask when the system gets the request for bookings/{valueGiven}/sometask. I tried doing below solution. It's not working as expected.

                        {
                            "match": {
                              "regex": "/bookings/(.*)/sometask"
                            },
                            "route": {
                              "prefix_rewrite": "/orders/$1/sometask",
                              "cluster": "order_service"
                            }
                          }

When I  send request bookings/1234/sometask, system should route to orders/1234/sometask
**In the logs I am getting : method=GET path="/orders/$1/sometask", order not found. The expected behavior should get path with the path parameters passed.**

**Comment by zyfjeff** [comment] 2018-08-28 06:36
@Bhawna4tech  the variable is not currently supported, there is no way to use $1 to refer to regular matching to the content

**Comment by techygarg** [comment] 2018-08-28 07:59
@zyfjeff: Thanks for prompt response.  As we have limited knowledge with Envoy so far, do you see any other feasible way, we can achieve it.

**Comment by zyfjeff** [comment] 2018-08-28 09:33
@techygarg #3977 This problem is very similar with you

**Comment by Bhawna4tech** [comment] 2018-08-28 10:50
@zyfjeff: Thanks for sharing the link. Yeah, it is same scenario. As no one has responded yet, it looks like it is not feasible currently in envoy, correct ?

**Comment by dio** [comment] 2018-08-28 22:53
It seems it is useful to have captured params to be used for subsequent `prefix_rewrite`-ing.

**Comment by Ofinka** [comment] 2019-05-14 12:49
Did you find any solution on how to perform this kind of routing?

**Comment by BailyTroyer** [comment] 2019-10-23 18:29
Has this been addressed? I am trying to do the same and have found no documentation regarding capture groups in envoy.

**Comment by zuercher** [comment] 2019-10-23 21:16
I'm closing this as a duplicate of #2092, which I believe is being worked on.

**Closed as completed by zuercher** 2019-10-23 21:16 UTC
Labels: enhancement, help wanted
