### ISSUE TITLE
Switch to simulated time system in integration tests

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#20996] opened 2022-04-25 19:37 UTC
HttpIntegrationTest would benefit from switching to using SimulatedTimeSystem to avoid flakiness caused by unpredictable delay of timers in real time. Per-discussion in https://github.com/envoyproxy/envoy/pull/20931#pullrequestreview-950002388, we should use simulated time whenever possible in new integration tests and possibly making the switch in the existing ones  as well.

**Comment by zhxie** [comment] 2022-04-26 01:17
I think this is a duplicate of #4160.

**Closed** 2022-04-26 12:29 UTC
Labels: triage
