### ISSUE TITLE
SSL Error : Handshake Error 2

### ISSUE THREAD

**Issue by justancoder** [envoyproxy/envoy#6246] opened 2019-03-11 14:32 UTC
I am getting error in TLS handshake when I am using envoy as proxy to reach my service.
Service is running in a pod in a kubernetes cluster and envoy is deployed on master. I am reaching to service through NodePort. 

Following are the logs for the handshake error:

^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.547][14][debug][connection] [source/common/network/connection_impl.cc:653] [C1] connection in progress
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.547][14][debug][pool] [source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.548][14][debug][connection] [source/common/network/connection_impl.cc:517] [C1] connected
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.548][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:142] [C1] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.557][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:142] [C1] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.557][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:142] [C1] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.571][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:142] [C1] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.571][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:142] [C1] handshake error: 2
[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:131] [C1] handshake complete
[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][client] [source/common/http/codec_client.cc:64] [C1] connected
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][pool] [source/common/http/http1/conn_pool.cc:245] [C1] attaching to next request
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][router] [source/common/router/router.cc:1165] [C0][S7238602018727543655] pool ready
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][connection] [source/common/network/connection_impl.cc:502] [C1] remote close
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][connection] [source/common/network/connection_impl.cc:183] [C1] closing socket: 0
^[[36mfront-envoy_1  |^[[0m [2019-03-11 11:38:57.572][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:244] [C1] SSL shutdown: rc=1

Following is the YAML I am using to deploy envoy.

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
           name: local_route
           virtual_hosts:
           - name: backend
             domains:
             - "local"
             routes:
             - match:
                 prefix: "/"
               route:
                 cluster: httpbin_https
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: httpbin_https
    connect_timeout: 2.5s
    type: static
    lb_policy: round_robin
    load_assignment:
     cluster_name: httpbin_https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.178.254.183
                port_value: 31167
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename":"/etc/clientcert.pem" }
          private_key: { "filename": "/etc/clientprivatekey.pem" }
        validation_context:
          trusted_ca:
            filename: /etc/servercert.crt
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

I am trying to reach a service which is basically a server which accepts request after mutual TLS handshake with the curl.
The command I am using to reach my server is: 
curl -vk http://127.0.0.1:443/headers -H "Host: local"          

And docker-compose ps output is 
front-proxy_front-envoy_1   /docker-entrypoint.sh /bin ...   Up      10000/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8001->8001/tcp

I could not understand the error which I am getting in envoy logs. It is showing Handshake error and handshake complete. I am guessing that my service is not responding here but when I reach servive 
directly with the curl command, it works perfectly fine. So is this the issue with envoy?

I am using https://www.learnenvoy.io/articles/on-your-laptop.html to deploy envoy.

**Comment by ipuustin** [comment] 2019-03-11 15:21
See if this is a duplicate of https://github.com/envoyproxy/envoy/issues/5683.

**Comment by justancoder** [comment] 2019-03-12 05:57
@ipuustin Looks similar but there are some doubts.
1. If I comment validation context , still the handshake passes after few handshake errors with 2 , see below :
     tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename":"/etc/clientcert.pem" }
          private_key: { "filename": "/etc/clientprivatekey.pem" }
       # validation_context:
        #  trusted_ca:
         #   filename: /etc/servercert.crt
  2. Wireshark trace does not show certificate exchange : 
      With curl (no envoy in path) we see the following SSL handshake logs : 
      * TLSv1.2 (OUT), TLS handshake, Client hello (1):
      * TLSv1.2 (IN), TLS handshake, Server hello (2):
      * TLSv1.2 (IN), TLS handshake, Certificate (11):
      * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
      * TLSv1.2 (IN), TLS handshake, Request CERT (13):
      * TLSv1.2 (IN), TLS handshake, Server finished (14):
      * TLSv1.2 (OUT), TLS handshake, Certificate (11):
      * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
      * TLSv1.2 (OUT), TLS handshake, CERT verify (15):
      * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
      * TLSv1.2 (OUT), TLS handshake, Finished (20):
      * TLSv1.2 (IN), TLS handshake, Finished (20):

 With Envoy, I see only following messages in handshake in wireshark
      * Client hello -> 
      * Server Hello <- 
      * Change Cipher Spec <- 
      * Encrypted handshale message <- 
      * Change Cipher Spec -> 
      * Encrypted handshale message ->
      * Application Data -> 
      * Encrypted Alert <- 
      * Encrypted Alert ->
      * FIN  packet <- (Connection tear down)

Logs : 
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.877][13][debug][pool] [source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.877][13][debug][http] [source/common/http/conn_manager_impl.cc:1025] [C2][S4133372670968259647] request end stream
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.877][13][debug][connection] [source/common/network/connection_impl.cc:517] [C3] connected
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.877][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:138] [C3] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.879][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:138] [C3] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.879][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:138] [C3] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:138] [C3] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:138] [C3] handshake error: 2
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:127] [C3] handshake complete
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][client] [source/common/http/codec_client.cc:64] [C3] connected
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][pool] [source/common/http/http2/conn_pool.cc:95] [C3] creating stream
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.880][13][debug][router] [source/common/router/router.cc:1132] [C2][S4133372670968259647] pool ready
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][connection] [source/common/network/connection_impl.cc:502] [C3] remote close
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][connection] [source/common/network/connection_impl.cc:183] [C3] closing socket: 0
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:236] [C3] SSL shutdown: rc=1
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][client] [source/common/http/codec_client.cc:82] [C3] disconnect. resetting 1 pending requests
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][client] [source/common/http/codec_client.cc:105] [C3] request reset
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][pool] [source/common/http/http2/conn_pool.cc:234] [C3] destroying stream: 0 remaining
^[[36mfront-envoy_1  |^[[0m [2019-03-12 05:31:05.881][13][debug][router] [source/common/router/router.cc:539] [C2][S4133372670968259647] upstream reset: reset reason connection termination

Wanted to understand why certificate exchange not happening here , and how come ssl handshake is completing without validation context. 

Is it possible that in this case mutual TLS not happening , one side TLS only taking place ?

**Comment by davidnarayan** [comment] 2019-03-18 13:59
Are you passing a client certificate with your `curl` command? It appears that your initial `curl` command did not specify one. In this case, mutual TLS would fail the handshake.

**Closed** 2019-04-09 09:47 UTC
Labels: question
