### ISSUE TITLE
Error message for broken upstream connections is too technical

### ISSUE THREAD

**Issue by misterwilliam** [envoyproxy/envoy#4453] opened 2018-09-18 18:15 UTC
*Broken upstream connections is too technical*

*Description*:
The current error message in the HTTP response body that Envoy returns when the network connection to the upstream host is broken is "upstream connect error or disconnect/reset before headers".

This is implemented [here](https://github.com/envoyproxy/envoy/blob/fcafc2d87760a6aa01b1d898e568a80cfb568a44/source/common/router/router.cc#L511).

The error message is correct, but in my opinion it is confusing because is getting unnecessarily technical about the nature of the error. How about we switch the error message to "Upstream connection error. Likely cause is upstream host breaking network connection."?

I would like an error message that a typical application programmer would find more understandable, and make it more obvious that the likely cause is that the upstream host has a bug in how it handles connections.

**Comment by htuch** [comment] 2018-09-18 20:40
There are multiple ways we can fail when making an upstream connection. I think what you're asking for is more a dupe of https://github.com/envoyproxy/envoy/issues/4283. Do you think it makes sense to combine with that?

**Comment by misterwilliam** [comment] 2018-09-19 17:32
That sounds like a good way to move forward.

**Comment by mattklein123** [comment] 2018-09-19 21:50
Agreed this is a dup of the other richer info issue, so closing.

**Closed by mattklein123** 2018-09-19 21:50 UTC
Labels: question
