### ISSUE TITLE
Envoy is still checking program size of regex

### ISSUE THREAD

**Issue by gongcon** [envoyproxy/envoy#18633] opened 2021-10-14 22:14 UTC
We're using envoy 1.18.3. Based on the [doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/regex.proto#envoy-v3-api-msg-type-matcher-v3-regexmatcher), `max_program_size` is not supposed to be checked in envoy. However, we still see the error `RE2 program size of 139 > max program size of 100 set for the error level threshold. Increase configured max program size if necessary.` and envoy rejects the config delivered from control plane.

> This field is deprecated; regexp validation should be performed on the management server instead of being done by each individual client.

**Comment by howardjohn** [comment] 2021-11-18 16:37
'respectively. re2.max_program_size.error_level defaults to 100, and re2.max_program_size.warn_level has no default if unset (will not check/log a warning).'

Doesn't that imply it *should* check by default?

**Comment by ankatare** [comment] 2021-11-22 12:49
Seems line of code resposible. 
https://github.com/envoyproxy/envoy/blob/main/source/common/common/regex.cc#L39

**Comment by ankatare** [comment] 2021-11-22 12:50
@snowp please suggest if we need to remove this code as it is deprecated.

**Comment by ankatare** [comment] 2021-11-29 20:49
@gongcon Hi, just wanted to check ,  is the issue only occured at 1.18.3 ? Have you checked in latest code

**Comment by gongcon** [comment] 2021-12-03 19:42
@ankatare no, 1.18.3 was the latest version we used at that time. No sure what the latest is now.

**Comment by ankatare** [comment] 2021-12-07 06:31
@gongcon couple of finding: 

**i don't find  change in the logic in v1.18.3 wrt #11187, and as per comments in file api/envoy/type/matcher/regex.proto** 
```
Envoy supports program size checking via runtime. The runtime keys `re2.max_program_size.error_level`
and `re2.max_program_size.warn_level` can be set to integers as the maximum program size or
complexity that a compiled regex can have before an exception is thrown or a warning is
logged, respectively. `re2.max_program_size.error_level` defaults to 100, and
`re2.max_program_size.warn_level` has no default if unset (will not check/log a warning). 
```
So, if the deprecated field is not present then Envoy check max_program_size via runtime and thats why code is executing to through exception ? 

**also if max_program_size is present then only old logic apply as below**

```
  // Check if the deprecated field max_program_size is set first, and follow the old logic if so.
    if (config.google_re2().has_max_program_size()) {
      const uint32_t max_program_size =
          PROTOBUF_GET_WRAPPED_OR_DEFAULT(config.google_re2(), max_program_size, 100);
      if (regex_program_size > max_program_size) {
        throw EnvoyException(fmt::format("regex '{}' RE2 program size of {} > max program size of "
                                         "{}. Increase configured max program size if necessary.",
                                         config.regex(), regex_program_size, max_program_size));
      }
      return;
    }
```

**Comment by ankatare** [comment] 2021-12-07 06:33
@gongcon one quick thing seeing your comments above, are you want to increase the default value of max_program_size (currently 100) ?

**Comment by ankatare** [comment] 2021-12-07 06:34
> cc @snowp
> 
> Looks like since #11187 Envoy hadn't been checking `max_program_size` until #17096. Perhaps there was a typo in the PR.

@rojkov Sorry, i did not understand typo here in PR  #17096?

**Comment by gongcon** [comment] 2021-12-08 23:18
@ankatare `max_program_size` is deprecated from the doc and there's no replacement. Question is why it's still being checked. Think either to set the default to a big enough value like MAX_INT or re-intro the setting will be good.

**Comment by ankatare** [comment] 2021-12-10 12:16
@gongcon humm. not sure why it is like that **design wise** as it seems still checking with runtime if NOT set.

**Comment by ankatare** [comment] 2021-12-10 12:17
@snowp @rojkov any suggetions on how to proceed here, should we increase it's default value ?

**Comment by snowp** [comment] 2021-12-10 13:55
If there was a regression here we should track that down, I don't think we should be arbitrarily bumping the default value.

@rojkov did you verify that we're not seeing size enforcement for commits between the one that supposedly removed the check and mine? This code existed before my change
```
        if (regex_program_size > max_program_size_error_level) {
        throw EnvoyException(fmt::format("regex '{}' RE2 program size of {} > max program size of "
                                         "{} set for the error level threshold. Increase "
                                         "configured max program size if necessary.",
                                         regex, regex_program_size, max_program_size_error_level));
      }
```
, so I'd have expected the check to always be there?

I wonder if this never changed and the right thing to do is to bump the runtime values?

**Comment by snowp** [comment] 2021-12-10 15:18
Yeah revisiting that code I thought it was a typo too, but turns out the semantics are: if program size is specified, validate directly, if not, do a program size check based on runtime values. I think this is the same semantics as previously?

I might get a PR up to make this clearer from code, it's a bit confusing right now.

**Comment by rojkov** [comment] 2021-12-10 16:41
Right, makes sense. But only after a bit of thinking :)

@gongcon So, it seems `max_program_size` isn't checked indeed if not present. What's checked is the runtime values.

**Comment by gongcon** [comment] 2021-12-11 00:52
A bit confuse, is the runtime value configurable? Also, is this message coming from runtime value checker?
```
RE2 program size of 139 > max program size of 100 set for the error level threshold. Increase configured max program size if necessary.
```

**Comment by rojkov** [comment] 2021-12-13 09:43
Yes, the threshold is set by the runtime value `re2.max_program_size.error_level`. I think you can increase it with something like
```yaml
layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      re2:
        max_program_size:
          error_level: 10000
```
added to your config.

And, I guess, the matcher doc needs to updated to mention the program size is still checked against the runtime value.

**Comment by ankatare** [comment] 2021-12-13 10:05
@rojkov +1 on doc.

**Comment by ankatare** [comment] 2021-12-13 10:08
> Sorry for delay... @snowp I didn't verify. I just quickly glanced and noticed that the constructor with one param calls the second constructor with `do_program_size_check` set to true in case there's no `max_program_size` in the config. This negation of `config.google_re2().has_max_program_size()` looks like a typo:
> 
> https://github.com/envoyproxy/envoy/blob/c68cf0dddfcea6c9ccf6346ff47b518837b0ca0d/source/common/common/regex.cc#L62

@rojkov Howvever, seems you are refering Latest code and @gongcon experiencing issue in v1.18.3. there is no such case of `"do_program_sixe_check" `in `1.18.3`

**Comment by ankatare** [comment] 2021-12-13 10:25
> Yes, the threshold is set by the runtime value `re2.max_program_size.error_level`. I think you can increase it with something like
> 
> ```yaml
> layered_runtime:
>   layers:
>   - name: static_layer_0
>     static_layer:
>       re2:
>         max_program_size:
>           error_level: 10000
> ```
> 
> added to your config.
> 
> And, I guess, the matcher doc needs to updated to mention the program size is still checked against the runtime value.

@rojkov @snowp plese suggest if i push doc PR on latest code for more clarity for users ?

**Comment by rojkov** [comment] 2021-12-13 10:39
> @rojkov @snowp plese suggest if i push doc PR on latest code for more clarity for users ?

Yes, please go for it.

**Comment by rojkov** [comment] 2021-12-13 10:43
v1.18.3 does the check as well. The reported error message `RE2 program size of 139 > max program size of 100 set for the error level threshold. Increase configured max program size if necessary` suggests that. If it checked against RegexMatcher's config the message would be different.

**Comment by ankatare** [comment] 2021-12-13 10:56
@rojkov Sorry, i think i could make it clear.My point is keyword "`do_program_size_check`" as a high level check does not exist in code of v1.18.3. Can you double check please .

**Comment by ankatare** [comment] 2021-12-13 10:56
> > @rojkov @snowp plese suggest if i push doc PR on latest code for more clarity for users ?
> 
> Yes, please go for it.

Thanks.. will push PR ASAP

**Comment by ankatare** [comment] 2021-12-14 01:50
@gongcon I think this issue now can be closed as per DOC changes #19260 and also suggestions to reconfigure `runtime` values by `"re2.max_program_size.error_level`" ?
cc @rojkov @snowp

**Comment by ankatare** [comment] 2021-12-16 10:25
@rojkov pls suggest on closure

**Comment by gongcon** [comment] 2021-12-21 18:58
Looks good to me. I have a couple questions.
* How do we check program size in the control plane (Java)?
* Do you have plan to make `in` operator (opposed to `contains`) in [string matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto#envoy-v3-api-msg-type-matcher-v3-stringmatcher)? Shall I open a feature request?

**Comment by ankatare** [comment] 2021-12-22 02:04
> Looks good to me. I have a couple questions.
> 
> * How do we check program size in the control plane (Java)?
> * Do you have plan to make `in` operator (opposed to `contains`) in [string matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto#envoy-v3-api-msg-type-matcher-v3-stringmatcher)? Shall I open a feature request?

@gongcon Thanks. On queries i am not much aware of the control planes.
cc @snowp @rojkov please help.

**Comment by ankatare** [comment] 2021-12-22 04:11
@gongcon @rojkov  can you close this issue now ?

**Closed** 2022-01-03 19:03 UTC
Labels: bug, area/configuration, area/matching
