### ISSUE TITLE
xds v3 regression: spammy EDS/RDS requests only on v3

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#11512] opened 2020-06-09 00:40 UTC
After migrating to XDS v3, we see very spammy EDS/RDS requests from Envoy.

When envoy requests v3:

```
2020-06-09T00:37:51.839088Z     info    ads     ADS:CDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 version:
2020-06-09T00:37:51.840568Z     info    ads     CDS: PUSH for node:. clusters:10 services:5 version:2020-06-08T17:37:48-07:00/1
2020-06-09T00:37:51.850987Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:1
2020-06-09T00:37:51.851157Z     info    ads     EDS: PUSH for node:. clusters:1 endpoints:0 empty:1
2020-06-09T00:37:51.851179Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:2
2020-06-09T00:37:51.851269Z     info    ads     EDS: PUSH for node:. clusters:2 endpoints:0 empty:2
2020-06-09T00:37:51.851398Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:3
2020-06-09T00:37:51.851677Z     info    ads     EDS: PUSH for node:. clusters:3 endpoints:1 empty:2
2020-06-09T00:37:51.851701Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:4
2020-06-09T00:37:51.851840Z     info    ads     EDS: PUSH for node:. clusters:4 endpoints:2 empty:2
2020-06-09T00:37:51.851859Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:5
2020-06-09T00:37:51.852024Z     info    ads     EDS: PUSH for node:. clusters:5 endpoints:3 empty:2
2020-06-09T00:37:51.852047Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 clusters:6
2020-06-09T00:37:51.852223Z     info    ads     EDS: PUSH for node:. clusters:6 endpoints:4 empty:2
2020-06-09T00:37:51.860634Z     info    ads     ADS:LDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1
2020-06-09T00:37:51.861662Z     info    ads     LDS: PUSH for node:. listeners:8
2020-06-09T00:37:51.882242Z     info    ads     ADS:RDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 routes:1
2020-06-09T00:37:51.882431Z     info    ads     RDS: PUSH for node:. routes:1
2020-06-09T00:37:51.882446Z     info    ads     ADS:RDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 routes:2
2020-06-09T00:37:51.882523Z     info    ads     RDS: PUSH for node:. routes:2
2020-06-09T00:37:51.882532Z     info    ads     ADS:RDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 routes:3
2020-06-09T00:37:51.882601Z     info    ads     RDS: PUSH for node:. routes:3
2020-06-09T00:37:51.882609Z     info    ads     ADS:RDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-1 routes:4
2020-06-09T00:37:51.882724Z     info    ads     RDS: PUSH for node:. routes:4
```

(logs are from control plane)

When a client requests v2:

```
2020-06-09T00:38:16.140960Z     info    ads     ADS:CDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-2 version:
2020-06-09T00:38:16.141765Z     info    ads     CDS: PUSH for node:. clusters:10 services:5 version:2020-06-08T17:37:48-07:00/1
2020-06-09T00:38:16.160530Z     info    ads     ADS:EDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-2 clusters:6
2020-06-09T00:38:16.160776Z     info    ads     EDS: PUSH for node:. clusters:6 endpoints:4 empty:2
2020-06-09T00:38:16.171977Z     info    ads     ADS:LDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-2
2020-06-09T00:38:16.172397Z     info    ads     LDS: PUSH for node:. listeners:8
2020-06-09T00:38:16.190366Z     info    ads     ADS:RDS: REQ sidecar~10.0.0.14~.~.svc.cluster.local-2 routes:4
2020-06-09T00:38:16.190501Z     info    ads     RDS: PUSH for node:. routes:4
```

I am pretty sure this issue was present in v2 at some point as well and was fixed, so maybe it somehow isn't on the v3 codepath - not exactly sure though

cc @ramaraochavali @htuch

**Comment by mattklein123** [comment] 2020-06-09 04:09
I think this is https://github.com/envoyproxy/envoy/pull/11300

**Comment by htuch** [comment] 2020-06-09 14:12
Yes, this is a dupe of #11300, closing.

**Comment by htuch** [comment] 2020-06-09 14:12
Or, rather https://github.com/envoyproxy/envoy/issues/11267.

**Closed by htuch** 2020-06-09 14:12 UTC
Labels: area/xds
