### ISSUE TITLE
Tracing Sampling Configuration Ignored

### ISSUE THREAD

**Issue by joshuarubin** [envoyproxy/envoy#3105] opened 2018-04-17 17:40 UTC
We would like to be able to bootstrap a different sampling configuration than the runtime default, but it doesn't appear that updating our config as follows changes anything as all requests still seem to be sampled at the default 100%

```yaml
static_resources:
  listeners:
    - filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                tracing:
                  random_sampling:
                    value: 0.1
```

I'm not too familiar with the codebase, but it looks like the [this](https://github.com/envoyproxy/envoy/blob/master/source/common/tracing/http_tracer_impl.cc#L63) may be the culprit

**Comment by mattklein123** [comment] 2018-04-17 18:03
This is a duplicate of https://github.com/envoyproxy/envoy/issues/1813. The config was added but IIRC I don't think the Envoy side changes were made?

**Comment by mattklein123** [comment] 2018-04-19 17:48
Closing as answered. Let's track in the related issue.

**Closed by mattklein123** 2018-04-19 17:48 UTC
Labels: question
