### ISSUE TITLE
Build a local image of an envoy repository

### ISSUE THREAD

**Issue by Jacobien1** [envoyproxy/envoy#21915] opened 2022-06-28 06:35 UTC
I have a non-official repository that I'm interested in testing, so I thought of making a local docker image but the documentation that I found is a bit vague so can someone explain please how can I have a local docker image of a repo

**Comment by wbpcode** [comment] 2022-06-28 13:10
May be you can build you binary locally first and then build the image with `https://github.com/envoyproxy/envoy/blob/main/ci/Dockerfile-envoy`.

**Comment by phlax** [comment] 2022-06-28 13:17
this seems to be a duplicate of https://github.com/envoyproxy/envoy/issues/21899

@Jacobien1 can we focus the conversation there - i am following up and will post more shortly

**Closed by phlax** 2022-06-28 13:17 UTC
Labels: question, area/build
