### ISSUE TITLE
Check format is taking a long time

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#11411] opened 2020-06-02 23:53 UTC
The runtime of `> ./ci/run_envoy_docker.sh 'ci/check_and_fix_format.sh'` seems to be increasing over time. Now it takes 5-10 minutes and validates every proto on top of doing bazel builds. Is there any way to just access the code linting part of this script?

**Comment by auni53** [comment] 2020-06-03 13:18
Oh while I'm complaining, it also seems to not work on worktrees.

**Comment by htuch** [comment] 2020-06-03 14:00
This is a dupe of https://github.com/envoyproxy/envoy/issues/11365

**Closed by htuch** 2020-06-03 14:00 UTC
