### ISSUE TITLE
Hi, I test the performace of v1.3 and v1.7 and the result is the performance of v1.3 is 20% better than v1.7.

### ISSUE THREAD

**Issue by jiangdongzi** [envoyproxy/envoy#19356] opened 2021-12-28 13:05 UTC
Is the result reasonable? I use the docker hub image to test.  I use the client and server of nighthawk to test the latency and wrk test the throughput.  Both the performance of latency and throughtput of v1.3 is 20% better than 1.7.
I also test v2.0, the latency performance  between v1.7 and v2.0 is nearly the same.
I only use the 
I don't think it should be this result.
I only use the http_connection_manager filter and only use router http_filter

**Comment by Shikugawa** [comment] 2021-12-31 01:32
This issue may be a duplicate of https://github.com/envoyproxy/envoy/issues/19103.

**Comment by alyssawilk** [comment] 2022-01-10 15:18
Yeah I think @wbpcode is working on it there so I'm closing this off as a duplicate.

**Closed by alyssawilk** 2022-01-10 15:18 UTC
Labels: triage
