### ISSUE TITLE
Get thread annotations to actually work

### ISSUE THREAD

**Issue by dnoe** [envoyproxy/envoy#2647] opened 2018-02-20 15:10 UTC
*Description*:
We have some data structures which have been annotated with the Clang thread annotations GUARDED_BY, etc. But they aren't actually enforced, since we don't compile with `-Wthread-safety-analysis`. When this option is turned on there are bigger problems. It appears that `std::mutex` is not compatible and thus the annotations don't detect that the lock is properly held.

It may be required to convert use of `std::mutex` to absl mutexes, which should also gain us some free contention tracking.

*Relevant Links*:
https://github.com/abseil/abseil-cpp/blob/master/absl/base/thread_annotations.h

**Comment by htuch** [comment] 2018-02-20 16:21
This is kind of a dupe of (but contains more recent information than)  https://github.com/envoyproxy/envoy/issues/2571.

**Comment by jmarantz** [comment] 2018-05-04 18:34
For the record, it's not strictly necessary to adopt absl mutexes in order to get thread annotations; you can just add a simple wrapper around std;:mutex with these annotations, similar to this: https://github.com/apache/incubator-pagespeed-mod/blob/becf61ae23afcfa6abc8259cb01131a9ad4bd213/pagespeed/kernel/base/abstract_mutex.h#L36

Moreoever, absl mutexes brings in absl/base malloc-hooks, for reasons I do not understand.  And those malloc hooks conflict with tcmalloc which we are using in Envoy, causing link errors about 6 multiply defined symbols including mmap.  However, for reasons I do not understand, some combination of bazel clean and updating to a new rev of absl seemed to help.


So I think we shouldn't necessarily consider this exactly a dup or dependent of #2571.  However at the moment I'm working on a PR which does do them both at the same time.

**Comment by jmarantz** [comment] 2018-05-08 18:15
They work now.  Assign to me & close?

**Closed** 2018-05-08 19:40 UTC
Labels: tech debt
