### ISSUE TITLE
Thrift connection manager crash on remote close during active request

### ISSUE THREAD

**Issue by fishcakez** [envoyproxy/envoy#9037] opened 2019-11-15 02:03 UTC
*Description*:
With a non-Envoy downstream service sending Thrift requests to Envoy using the THeader transport/TBinary protocol. If the downstream service closes the connection (e.g. close on timeout) while the request is pending, Envoy can crash.

*Repro steps*:
Send THeader/TBinary Thrift request with Xms timeout and it times out. Can provide a full repro if required as used proprietary code to produce the below output.

*Config*:
```
[
  {
    "@type": "type.googleapis.com/envoy.api.v2.Listener",
    "address": {
      "socket_address": {
        "address": "0.0.0.0",
        "port_value": 9000
      }
    },
    "filter_chains": [
      {
        "filters": [
          {
            "name": "envoy.filters.network.thrift_proxy",
            "typed_config": {
              "@type": "type.googleapis.com/envoy.config.filter.network.thrift_proxy.v2alpha1.ThriftProxy",
              "route_config": {
                "name": "routes",
                "routes": [
                  {
                    "match": {
                      "method_name": ""
                    },
                    "route": {
                      "cluster": "local_cluster"
                    }
                  }
                ]
              },
              "stat_prefix": "ingress",
              "thrift_filters": [
                {
                  "name": "envoy.filters.thrift.router",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.config.filter.thrift.router.v2alpha1.Router"
                  }
                }
              ]
            }
          }
        ],
        "tls_context": {
          "common_tls_context": {
...
          },
          "require_client_certificate": true
        }
      }
    ],
    "name": "ingress"
  },
  {
    "@type": "type.googleapis.com/envoy.api.v2.Cluster",
    "circuit_breakers": {
      "thresholds": [
        {
          "max_connections": 16384,
          "max_pending_requests": 16384,
          "max_requests": 16384,
          "priority": "DEFAULT"
        }
      ]
    },
    "connect_timeout": "0.25s",
    "lb_policy": "LEAST_REQUEST",
    "load_assignment": {
      "cluster_name": "local_cluster",
      "endpoints": [
        {
          "lb_endpoints": [
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "127.0.0.1",
                    "port_value": 9200
                  }
                }
              }
            },
...
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "127.0.0.1",
                    "port_value": 9239
                  }
                }
              }
            }
          ]
        }
      ]
    },
    "name": "local_cluster",
    "type": "STATIC"
  }
]
```

*Logs*:
```
[2019-11-15 01:16:20.152][91][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:335] [C8] new connection
[2019-11-15 01:16:20.152][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C8] handshake expecting read
[2019-11-15 01:16:20.152][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C8] handshake expecting read
[2019-11-15 01:16:20.153][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:176] [C8] handshake complete
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 254 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:388] thrift: header(auto) transport started
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:394] thrift: header(auto) transport forced binary(auto) protocol
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:422] thrift: protocol binary(auto), state MessageBegin, 120 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/router/router_impl.cc:226] [C8][S4833533741472223023] cluster 'local_cluster' match for method 'thrift_method'
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/router/router_impl.cc:259] [C8][S4833533741472223023] router decoding request
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:83] creating a new connection
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:364] [C9] connecting
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C9] connecting to 127.0.0.1:9210
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:716] [C9] connection in progress
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:109] queueing request due to no available connections
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:430] thrift: wait for continuation
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:555] [C9] connected
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:285] [C9] assigning connection
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:128] [C8] thrift filter continued
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 82 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:422] thrift: protocol binary(auto), state StructBegin, 82 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:446] thrift: header(auto) transport ended
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:523] [C9] remote close
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:189] [C9] closing socket: 0
[2019-11-15 01:16:20.169][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:124] [C9] client disconnected
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:100] [C8] closing data_to_write=226 type=0
[2019-11-15 01:16:20.170][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:238] [C9] connection destroyed
[2019-11-15 01:16:20.170][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:298] [C8] SSL shutdown: rc=0
[2019-11-15 01:16:20.170][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C8]
[2019-11-15 01:16:20.170][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:585] [C8] write flush complete
[2019-11-15 01:16:20.170][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:189] [C8] closing socket: 1
[2019-11-15 01:16:20.170][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:147] [C8] local close with active request
[2019-11-15 01:16:20.170][91][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:88] [C8] adding to cleanup list
```

*Call Stack*:
```
[2019-11-15 01:16:20.170][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
[2019-11-15 01:16:20.170][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-11-15 01:16:20.170][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 0/1.13.0-dev//RELEASE/BoringSSL
[2019-11-15 01:16:20.170][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f15eb357890] ??:0
[2019-11-15 01:16:20.172][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Extensions::NetworkFilters::ThriftProxy::ConnectionManager::ActiveRpc::~ActiveRpc() [0x556162c51d89] ??:0
[2019-11-15 01:16:20.174][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Extensions::NetworkFilters::ThriftProxy::ConnectionManager::ActiveRpc::~ActiveRpc() [0x556162c5209e] ??:0
[2019-11-15 01:16:20.177][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x556162d1a8f7] ??:0
[2019-11-15 01:16:20.179][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: event_process_active_single_queue [0x55616303be06] ??:0
[2019-11-15 01:16:20.181][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: event_base_loop [0x55616303a9be] ??:0
[2019-11-15 01:16:20.183][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Server::WorkerImpl::threadRoutine() [0x556162d139b6] ??:0
[2019-11-15 01:16:20.185][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x5561631c44b5] ??:0
[2019-11-15 01:16:20.185][91][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: start_thread [0x7f15eb34c6db] ??:0
```

cc @rgs1

**Comment by htuch** [comment] 2019-11-15 14:52
@zuercher can you triage this one? Thanks.

**Comment by rgs1** [comment] 2019-11-17 15:10
Possibly a path that was missed in #6549.

**Comment by zuercher** [comment] 2019-11-18 22:38
@fishcakez can you confirm if this is new post #6549?

If so, @rgs1 can you work on a fix? If not we should revert #6549 until someone has time to look at it.

**Comment by rgs1** [comment] 2019-11-18 22:53
@zuercher still looking, I think reverting #6549 is possibly worse (it'll cause crashes on stuff we have in prod). I'll check-in a bit later with my discoveries, if any.

**Comment by rgs1** [comment] 2019-11-18 23:52
Hmm, per the debug logs it's not the downstream closing the connection -- it's the upstream. Given that `[C8]` is the downstream connection (note: TLS is used for the downstream):

```
[2019-11-15 01:16:20.152][91][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:335] [C8] new connection
[2019-11-15 01:16:20.152][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C8] handshake expecting read
[2019-11-15 01:16:20.152][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C8] handshake expecting read
[2019-11-15 01:16:20.153][91][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:176] [C8] handshake complete
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 254 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:388] thrift: header(auto) transport started
```

And `[C9]` is the upstream connection (note: no TLS, given it's over the loopback):

```
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:83] creating a new connection
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:364] [C9] connecting
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C9] connecting to 127.0.0.1:9210
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:716] [C9] connection in progress
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:109] queueing request due to no available connections
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:430] thrift: wait for continuation
[2019-11-15 01:16:20.154][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:555] [C9] connected
[2019-11-15 01:16:20.154][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:285] [C9] assigning connection
```

And then we see `[C9]` -- the upstream connection -- being closed:

```
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:128] [C8] thrift filter continued
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 82 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:422] thrift: protocol binary(auto), state StructBegin, 82 bytes available
[2019-11-15 01:16:20.154][91][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:446] thrift: header(auto) transport ended
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:523] [C9] remote close
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:189] [C9] closing socket: 0
[2019-11-15 01:16:20.169][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:124] [C9] client disconnected
```

which finally triggers the destruction of `[C8]` -- the downstream connection -- here:

```
[2019-11-15 01:16:20.169][91][debug][connection] [external/envoy/source/common/network/connection_impl.cc:100] [C8] closing data_to_write=226 type=0
[2019-11-15 01:16:20.170][91][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:238] [C9] connection destroyed
....
```

**Comment by rgs1** [comment] 2019-11-19 13:04
So I've set the log level to trace and I am starting to think this might be decoder related and not connection management related:

```
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 254 bytes available                                                     
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:388] thrift: header(auto) transport started                                          
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:394] thrift: header(auto) transport forced binary(auto) protocol                     
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:170] new decoder filter                                                         
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:422] thrift: protocol binary(auto), state MessageBegin, 120 bytes available          
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state MessageBegin, 120 bytes available                                 
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/router/router_impl.cc:240] [C31][S6170852784500393344] cluster 'local_cluster' match for method 'process_foo'
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/router/router_impl.cc:273] [C31][S6170852784500393344] router decoding request                  
[2019-11-19 12:57:12.466][99][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:83] creating a new connection                                                                                    
[2019-11-19 12:57:12.466][99][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:364] [C32] connecting                                                                                            
[2019-11-19 12:57:12.466][99][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C32] connecting to 127.0.0.1:9225                                                          
[2019-11-19 12:57:12.466][99][debug][connection] [external/envoy/source/common/network/connection_impl.cc:716] [C32] connection in progress                                                                
[2019-11-19 12:57:12.466][99][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:109] queueing request due to no available connections                                                            
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:430] thrift: wait for continuation                                                  
[2019-11-19 12:57:12.466][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:458] [C32] socket event: 2                                                                       
[2019-11-19 12:57:12.466][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:546] [C32] write ready                                                                           
[2019-11-19 12:57:12.466][99][debug][connection] [external/envoy/source/common/network/connection_impl.cc:555] [C32] connected                                                                             
[2019-11-19 12:57:12.466][99][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:285] [C32] assigning connection                                                                                  
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:128] [C31] thrift filter continued                                             
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:367] thrift: 82 bytes available                                                     
[2019-11-19 12:57:12.466][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:422] thrift: protocol binary(auto), state StructBegin, 82 bytes available           
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state StructBegin, 82 bytes available                                  
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 82 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 79 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state ListBegin, 79 bytes available                                    
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state ListValue, 74 bytes available                                    
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state StructBegin, 74 bytes available                                  
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 74 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 71 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 70 bytes available                                     
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 70 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 67 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 63 bytes available                                     
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 63 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 60 bytes available                                   
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 24 bytes available                                     
[2019-11-19 12:57:12.466][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 24 bytes available                                   
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 21 bytes available                                   
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 17 bytes available                                     
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 17 bytes available                                   
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldValue, 14 bytes available                                   
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 2 bytes available                                      
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 2 bytes available                                    
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state StructEnd, 1 bytes available                                     
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state ListValue, 1 bytes available                                     
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state ListEnd, 1 bytes available                                       
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldEnd, 1 bytes available                                      
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state FieldBegin, 1 bytes available                                    
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state StructEnd, 0 bytes available                                     
[2019-11-19 12:57:12.467][99][trace][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:338] thrift: state MessageEnd, 0 bytes available                                    
[2019-11-19 12:57:12.467][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:394] [C32] writing 258 bytes, end_stream false                                                   
[2019-11-19 12:57:12.467][99][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/decoder.cc:446] thrift: header(auto) transport ended                                           
[2019-11-19 12:57:12.467][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:546] [C32] write ready                                                                           
[2019-11-19 12:57:12.467][99][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:67] [C32] write returns: 258                                                                   
[2019-11-19 12:57:12.467][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:458] [C32] socket event: 2                                                                       
[2019-11-19 12:57:12.467][99][trace][connection] [external/envoy/source/common/network/connection_impl.cc:546] [C32] write ready                                                                           
[2019-11-19 12:57:12.469][96][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Extensions::NetworkFilters::ThriftP$oxy::ConnectionManager::ActiveRpc::~ActiveRpc() [0x559057b4162e] ??:0

```

The crash happens immediately after the decoder calls `reset()` on the `ActiveRpc` unique_ptr:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/thrift_proxy/decoder.cc#L452

**Comment by rgs1** [comment] 2019-11-19 15:04
Maybe the decoder is OK. Another interesting thing is that when the deferred deletion list is of size 1, there is no crash:

```
[2019-11-19 14:50:19.060][23][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=1)                                                             
[2019-11-19 14:50:24.032][23][debug][main] [external/envoy/source/server/server.cc:175] flushing stats                                                                                                     
[2019-11-19 14:50:24.053][23][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C187] connecting to 127.0.0.1:10080
...
all good
...        
```

Another example:

```
[2019-11-19 14:50:27.941][97][trace][connection] [external/envoy/source/common/network/connection_impl.cc:394] [C188] writing 226 bytes, end_stream true                                                   
[2019-11-19 14:50:27.941][97][debug][connection] [external/envoy/source/common/network/connection_impl.cc:100] [C188] closing data_to_write=226 type=0                                                     
[2019-11-19 14:50:27.941][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=1)                                                             
[2019-11-19 14:50:27.941][97][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:238] [C189] connection destroyed                                                                                 
[2019-11-19 14:50:27.941][97][trace][connection] [external/envoy/source/common/network/connection_impl.cc:458] [C188] socket event: 2                                                                      
[2019-11-19 14:50:27.941][97][trace][connection] [external/envoy/source/common/network/connection_impl.cc:546] [C188] write ready                                                                          
[2019-11-19 14:50:27.941][97][trace][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:259] [C188] ssl write returns: 226                                                  
[2019-11-19 14:50:27.941][97][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:298] [C188] SSL shutdown: rc=0           
...
```

But when it's size > 1:

```
[2019-11-19 14:50:27.941][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:160] item added to deferred deletion list (size=1)                                                       
[2019-11-19 14:50:27.941][97][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:86] [C188] adding to cleanup list                                                              
[2019-11-19 14:50:27.941][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:160] item added to deferred deletion list (size=2)                                                       
[2019-11-19 14:50:27.941][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=2)                                                             
[2019-11-19 14:50:27.941][97][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0                                                             
[2019-11-19 14:50:27.941][97][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):                       
[2019-11-19 14:50:27.941][97][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 0/1.13.0-dev//RELEASE/BoringSSL [2019-11-19 14:50:27.941][97][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f7d70678890] ??:0
```

**Comment by rgs1** [comment] 2019-11-19 15:07
I take that back too, got a case of no crash with size=2:

```
[2019-11-19 15:06:11.142][97][debug][thrift] [external/envoy/source/extensions/filters/network/thrift_proxy/conn_manager.cc:150] [C277] remote close with active request                                   
[2019-11-19 15:06:11.142][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:160] item added to deferred deletion list (size=1)                                                       
[2019-11-19 15:06:11.142][97][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:86] [C277] adding to cleanup list                                                              
[2019-11-19 15:06:11.142][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:160] item added to deferred deletion list (size=2)                                                       
[2019-11-19 15:06:11.142][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=2)                                                             
[2019-11-19 15:06:11.142][97][debug][connection] [external/envoy/source/common/network/connection_impl.cc:100] [C278] closing data_to_write=0 type=1                                                       
[2019-11-19 15:06:11.142][97][debug][connection] [external/envoy/source/common/network/connection_impl.cc:189] [C278] closing socket: 1
[2019-11-19 15:06:11.142][97][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:124] [C278] client disconnected                                                                                  
[2019-11-19 15:06:11.142][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:160] item added to deferred deletion list (size=1)                                                       
[2019-11-19 15:06:11.143][97][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=1)                                                             
[2019-11-19 15:06:11.143][97][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:238] [C278] connection destroyed               
```

**Comment by rgs1** [comment] 2019-11-19 16:26
Hmm, maybe we are calling `doDeferredRpcDestroy()` twice on the same `ActiveRpc` instance (added a quick cout call to inspect what's going on, assuming addresses aren't reused):

```
doDeferredRpcDestroy: 0x556d4eca3c00
doDeferredRpcDestroy: 0x556d4ef28400
doDeferredRpcDestroy: 0x556d4f1e4800
doDeferredRpcDestroy: 0x556d4f1e4400
doDeferredRpcDestroy: 0x556d4f1e4800
doDeferredRpcDestroy: 0x556d4f1e4400
doDeferredRpcDestroy: 0x556d4f1e4800
doDeferredRpcDestroy: 0x556d4f1e4400
doDeferredRpcDestroy: 0x556d4f1e4800
doDeferredRpcDestroy: 0x556d4f1e4c00
doDeferredRpcDestroy: 0x556d4f1e4400
```

**Comment by rgs1** [comment] 2019-11-19 18:42
The problem is in:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/thrift_proxy/conn_manager.h#L173

Commenting that out, makes the crash go away. Will dig into `onDestroy()` and send a PR... guessing we are referencing a connection object that's gone from there (or something similar).

**Comment by rgs1** [comment] 2019-11-20 01:25
@fishcakez @zuercher Ok, I am positive that this lines generates the crash:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/thrift_proxy/router/router_impl.cc#L417

When commented out, no crash (of course, that's not the fix).

I tried `close()` with `FlushWrite` or `FlushWriteAndDelay`; it still crashes. Not sure what the right solution is -- checking if the connection is already closed and avoiding the call if so? I'll keep looking at this tomorrow.

**Comment by zuercher** [comment] 2019-11-20 02:02
So I think this may be a case where Router::onEvent gets called twice? Once because of an upstream remote reset, which triggers a downstream reset (probably because a partial response has been sent already), then we close it again in resetStream and it crashes because upstream_request_ is nullptr? (I'm assuming this isn't in a debug build which would assert). If that's correct, then it may be enough to ignore the event in Router::onEvent if upstream_reset_ == nullptr.

**Comment by rgs1** [comment] 2019-11-20 16:41
@zuercher not quite, because `upstream_request_` will only be set to `nullptr` _after_ `resetStream()` is called, from where I think the other `onEvent()` call is happening. So we need something that isn't `upstream_request_` to do the check, I think.

**Comment by rgs1** [comment] 2019-11-20 18:24
Unclear if #9086 is the right approach; but checking the HTTP router we don't seem to close connections there on reset and it seems triggering a close from `~ActiveRpc()` is hard to get right given it can trigger other events.

**Comment by rgs1** [comment] 2019-11-20 21:23
So #9086 isn't right, sending a hopefully proper fix -- with the reasoning -- in a bit.

**Closed** 2019-11-22 17:00 UTC
Labels: bug
