### ISSUE TITLE
Envoy v1.29.0 build fails on Mac OS

### ISSUE THREAD

**Issue by lukidzi** [envoyproxy/envoy#31932] opened 2024-01-22 15:34 UTC
*Title*: *Envoy v1.29.0 build fails on Mac OS*

*Description*:
When I am building Envoy v1.29.0 on MacOS 12.7.1 with clang 14.0.0 I noticed an error

```
ec2-user@Mac-mini envoy-builds % gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Envoy build error

```
Undefined symbols for architecture x86_64:
  "cel::interop_internal::ProtoStructValueToMessageWrapper(cel::Value const&)", referenced from:
      cel::interop_internal::ToLegacyValue(google::protobuf::Arena*, cel::Handle<cel::Value> const&, bool) in libinterop.a(interop.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //contrib/exe:envoy-static failed to build
INFO: Elapsed time: 136.522s, Critical Path: 46.32s
```

I've tried both conrtib and not contrib build but I have the same issue.

*Repro steps*:

1. Use mac 12.7.1 or 11.7.10 (on aws ami-06bf601fad285cc69 or ami-0da052d2225304b8f)
2. Setup CI tools
3. run bazel build -c opt envoy
4. Notice error at the last step

```
Undefined symbols for architecture x86_64:
  "cel::interop_internal::ProtoStructValueToMessageWrapper(cel::Value const&)", referenced from:
      cel::interop_internal::ToLegacyValue(google::protobuf::Arena*, cel::Handle<cel::Value> const&, bool) in libinterop.a(interop.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //contrib/exe:envoy-static failed to build
INFO: Elapsed time: 136.522s, Critical Path: 46.32s
```

I've noticed that more people have the same issue https://github.com/Homebrew/homebrew-core/pull/160068

**Comment by phlax** [comment] 2024-01-22 15:59
cc @kyessenov @moderation

**Comment by moderation** [comment] 2024-01-22 16:08
I think it was likely I was just the first to hit this. If this is WONTFIX, we should update documentation to say building on MacOS no longer possible after relevant commit.  Wondering how many people are running MacOS instances in the cloud.

**Comment by phlax** [comment] 2024-01-22 16:21
i think it should be resolvable one way or other

to clarify - macos does build, as we are building/testing in ci still (macos12 github runners)

i believe the constraint is to use the correct versions of compiler - it may be that our ci just builds less and excludes cel - not sure and no way to test

the setup for the macos12 images is here https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md - i dont see any setup for this on our end (here https://github.com/envoyproxy/envoy/blob/main/ci/mac_ci_setup.sh) so assume that we are just using whatever is default in the macos12 image

> update documentation to say building on MacOS no longer possible after relevant commit

perhaps we can (figure out and) specify what does work

**Comment by ggreenway** [comment] 2024-02-01 00:26
`git bisect` says this is caused by bd1dca3cf366bc5287295de73e4354d2f5d1f1d9

**Comment by ggreenway** [comment] 2024-02-01 01:01
@phlax that's a fairly old version of macOS for CI. Is there a runner based on macOS version 14 we can use?

**Comment by moderation** [comment] 2024-02-01 03:26
Related https://github.com/envoyproxy/envoy/pull/31456#issuecomment-1894768173

**Comment by ggreenway** [comment] 2024-02-01 03:54
> Related [#31456 (comment)](https://github.com/envoyproxy/envoy/pull/31456#issuecomment-1894768173)

Thanks for the extra context; I hadn't seen that.

**Closed** 2024-02-07 23:24 UTC
Labels: bug, area/build, area/macos
