### ISSUE TITLE
HTTP request with special X-Request-Id can NOT be traced

### ISSUE THREAD

**Issue by idouba** [envoyproxy/envoy#8542] opened 2019-10-09 01:37 UTC
curl a service with following two ways:

curl http://svc:20888/path  -H 'X-Request-Id: 8cda17a5-eb41-4ced-9843-acc826f95c8c'
curl http://svc:20888/path -H 'X-Request-Id: 27290d28d5c38da315a78399d71fc20b'
The former request with a valid uuid as x-request-id can be traced successfully,
while the latter with a invalid uuid does not be traced, thex-request-id is generated by some old app.

My question is why the formation of x-request-id affects the tracing.

And by checking the  [code](https://github.com/envoyproxy/envoy/blob/9c682f815ec70da374c4c5d2e24fd7a46f868bfb/source/common/http/conn_manager_utility.cc#L241-L286) ,not understand why user’s original x_request_id be checked and modified here.

**Comment by idouba** [comment] 2019-10-09 02:33
Since x-b3-sampled is set in envoy and app propagate it across one request, which decide weather the trace should be collected,  why x_request_id has to be checked  modified here like thisL
```
  if (UuidTraceStatus::NoTrace == UuidUtils::isTraceableUuid(x_request_id)) {
    if (request_headers.ClientTraceId() &&
        runtime.snapshot().featureEnabled("tracing.client_enabled", *client_sampling)) {
      UuidUtils::setTraceableUuid(x_request_id, UuidTraceStatus::Client);
    } else if (request_headers.EnvoyForceTrace()) {
      UuidUtils::setTraceableUuid(x_request_id, UuidTraceStatus::Forced);
    } else if (runtime.snapshot().featureEnabled("tracing.random_sampling", *random_sampling,
                                                 result)) {
      UuidUtils::setTraceableUuid(x_request_id, UuidTraceStatus::Sampled);
    }
  }
```

**Comment by mattklein123** [comment] 2019-10-09 03:43
This is a duplicate of https://github.com/envoyproxy/envoy/issues/7624. Let's track there.

**Closed by mattklein123** 2019-10-09 03:43 UTC
