### ISSUE TITLE
MacOS Monterey + Intel + Brew - Segmentation fault

### ISSUE THREAD

**Issue by marcosrmendezthd** [envoyproxy/envoy#19053] opened 2021-11-18 20:38 UTC
*Description*:
>Envoy 1.20.0 installed via brew crashes after a clean install on MacOS Monterey on an intel laptop.

MacBook Pro (Retina, 15-inch, Mid-2015)
Processor: 2.5 GHz Quad-Core Intel Core i7

$ uname -av
Darwin ... 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

$ brew --version
Homebrew 3.3.4
Homebrew/homebrew-core (git revision feddfd3b28b; last commit 2021-11-18)
Homebrew/homebrew-cask (git revision b5b59d947c; last commit 2021-11-19)

$ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

*Repro steps*:

$ brew install envoy
==> Downloading https://ghcr.io/v2/homebrew/core/envoy/manifests/1.20.0
==> Downloading https://ghcr.io/v2/homebrew/core/envoy/blobs/sha256:5d3c90329a1c
==> Pouring envoy--1.20.0.big_sur.bottle.tar.gz

$ envoy --help
Segmentation fault: 11

**Comment by ggreenway** [comment] 2021-11-18 21:04
I think this is a duplicate of #17535. Note that this is fixed in `main` and in the 1.20 release branch, but no point release has happened on 1.20 since the fix.

**Closed by ggreenway** 2021-11-18 21:04 UTC
Labels: bug, triage

**Comment by marcosrmendezthd** [comment] 2021-11-18 21:09
great. thank you!
