### ISSUE TITLE
Printing structural JSON logs in Envoy 

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25959] opened 2023-03-07 16:40 UTC
I am using fluentd to tail the Envoy process and collect logs. The fluentd is parsing lines as structural JSON strings. I have two related questions:
1. Is it possible to print each log message in JSON format natively, without writing the JSON structure in --log-format?
2. Assume I have the following custom code to write a log message: `ENVOY_LOG(info, "my message param1: {}, param2: {}", param1_value, param2_value);`, the log message would have the rendered message. I would like to have the provided parameters as additional JSON fields in my structured message, is this something that can be supported?
3. In general, are there any best practice guides for how to log with Envoy and collect using fluentd or in general, when seeking JSON structured logs?
Thanks

**Comment by mattklein123** [comment] 2023-03-08 15:55
I don't think this is supported today. It sounds possible to implement but would require a bunch of thinking on how to accomplish.

**Comment by derekargueta** [comment] 2023-03-27 18:27
I think this issue is a dupe of https://github.com/envoyproxy/envoy/issues/11610

**Comment by ohadvano** [comment] 2023-04-02 16:23
@mattklein123 I can propose the following change:

1. A new macro ENVOY_LOG definition, say ``ENVOY_TAGGED_LOG``, that would expect a map of tags, before the message format variables
2. Similar to how ``stats_config:stats_tags`` can define a global tag list that would add to any stat, we can add a bootstrap config to define a list of global ``envoy_log_tags``, that would be added to any log that was recorded using ``ENVOY_TAGGED_LOG``.
3. By default, ``ENVOY_TAGGED_LOG`` will be printed in the default envoy log format, but additional bootstrap config ``envoy_log_format`` would be able to set to JSON, and if it is, any envoy log will be printed in JSON format (overriding cli option of --log-format)

Not sure if this is a perfect plan yet, but WDYT?

**Comment by mattklein123** [comment] 2023-04-04 01:36
At a high level this sounds fine to me. It would be nice if there was no extra overhead from using the tagged stuff if JSON/tags are not enabled, but we can see how that looks when you prototype it. Thank you.

**Closed** 2023-06-15 17:26 UTC
Labels: help wanted, area/envoy_log
