### ISSUE TITLE
stats by URL path

### ISSUE THREAD

**Issue by jwfang** [envoyproxy/envoy#1585] opened 2017-09-01 13:25 UTC
currently there are HTTP connection manager level stats but no URL path level stats AFAIK.
it would be nice to have by path stats out of the box

**Comment by mattklein123** [comment] 2017-09-01 17:59
The is no reasonable way to have generic path stats, since Envoy doesn't know what a path is exactly with prefix routing.

Currently, we have the virtual cluster feature: https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/vcluster.html

This might be enough. Another thing I would be open to is having dynamic stats on a per route basis, which the user opts in to.

**Comment by jwfang** [comment] 2017-09-04 04:34
thanks for help.

we're proxying gRPC via envoy, and would like to have some generic per method stats from envoy.

i looked at *virtual cluster* and it seems have to be configured for every method, and the suggested *dynamic stats on a per route* may also need to do this.

i am a bit confused by the 

> Envoy doesn't know what a path is exactly with prefix routing

not familiar with Envoy internals, but i thought the HTTP URL path (only base path without query string) is already in the request ?

also, support for *grpc-status* from Trailer would be a bonus for gRPC.

**Comment by mattklein123** [comment] 2017-09-04 17:43
Regarding per path stats, the issue is basically that the stats can become unbounded so we can't do it by default (even if we strip the query string). I'm open to an optional feature here that is off by default if you want to do a design proposal and PR. 

BTW, as a short term workaround, the HTTP/1.1 bridge filter will collect gRPC per method stats: https://github.com/lyft/envoy/blob/master/source/common/grpc/http1_bridge_filter.cc#L19. It will do this even when not bridging for HTTP/2. This might be good enough for what you need for now.

I know that @fengli79 and @lizan have some thoughts on what we want to do medium term with better gRPC stats and whether to put them in the router directly of have them be in a different filter. Perhaps they can weigh in here.

**Comment by jwfang** [comment] 2017-09-05 10:36
thanks, you saved my day.

wonder if it's possible to add *Timer*  to the existing stats. if this doesn't involve too much Envoy internals, i may find some time to do it.

**Comment by mattklein123** [comment] 2017-09-05 16:36
@jwfang it should be pretty easy to do timers also. See https://github.com/lyft/envoy/blob/master/source/common/http/codes.cc#L83 for how this might work.

**Comment by fengli79** [comment] 2017-09-05 16:58
gRPC-Web filter also do method level stats.
About http2 proxying for gRPC payload, I think envoy probably need to know more about the payload than just treat it as normal http2, as the status of gRPC is in the grpc-status header/trailer instead of the http2 status. A filter may help.

**Comment by mattklein123** [comment] 2017-09-30 02:01
Closing for now. Let's make a new issue if there is a particular feature request.

**Closed by mattklein123** 2017-09-30 02:01 UTC
Labels: question
