### ISSUE TITLE
I want to use my dns server in /etc/resolv.conf when I use forward proxy on envoy.

### ISSUE THREAD

**Issue by malza321** [envoyproxy/envoy#16026] opened 2021-04-16 02:03 UTC
Hi all,

I need to configure a transparent forward proxy, which does no operation on the coming request just route it on the basis of domain, I don't want envoy to make any changes(L3/L4 to L7) to the input request. I've already used envoy for reverse prxoy with loadblancing but I also want to use envoy with outbound forward proxy.

With solution [#10756] we cannot specify a dns_resolver for the cluster. I have some constraints due to which cannot add the dns server in /etc/reslov.conf. We can't use external dns server.. 

Is this achievable with envoy?
if yes a config sample(envoy.yaml) will be a great help.

Thanks

**Comment by htuch** [comment] 2021-04-18 17:48
@malza321 not sure I fully understand the question; it sounds like you are familiar with Envoy dynamic forward proxy capability. It seems the main issue is around where the DNS resolver is specified; in the title you say you want to use the DNS server in /etc/resolve.conf, but in the text above you say you can't place it in /etc/resolv.conf, can you clarify?

**Comment by malza321** [comment] 2021-04-18 23:08
> @malza321 not sure I fully understand the question; it sounds like you are familiar with Envoy dynamic forward proxy capability. It seems the main issue is around where the DNS resolver is specified; in the title you say you want to use the DNS server in /etc/resolve.conf, but in the text above you say you can't place it in /etc/resolv.conf, can you clarify?

Simply I want to use my own dns server, not the 8.8.8.8

my dns server adress in resolv.conf, but It's not a matter. I just want to put my dns server address on envoy.yaml and use it.

I've tried everyting but can't find out. plz help...

**Comment by htuch** [comment] 2021-04-19 18:23
Are you saying that, following #10756, the issue is that dynamic forward just doesn't support `dns_resolver` specification?

**Comment by malza321** [comment] 2021-04-19 23:03
is that true?
I just want like #10990

We can't use other dns server. should use our own dns server.

**Comment by malza321** [comment] 2021-04-19 23:05
> Are you saying that, following #10756, the issue is that dynamic forward just doesn't support `dns_resolver` specification?

is that true?
I just want like #10990

We can't use other dns server like a 8.8.8.8. We should use our own dns server and that is not in local server.

**Comment by junpengl** [comment] 2021-04-27 21:23
@htuch It would be nice for us if dynamic forward support dns_resolver specification? Based on the doc it seems like it doesn't support it.
Our use case is that we override the DNS resolver in a K8s pod for some addresses but we would like the sidecar Envoy running in the same Pod to use a different DNS resolver for those addresses and forward the requests.

**Comment by ntgsx92** [comment] 2021-04-28 22:04
This seems like a duplicate of https://github.com/envoyproxy/envoy/issues/15657

I have a working branch locally that adds `dns_resolvers` to the [DnsCacheConfig](https://github.com/envoyproxy/envoy/blob/d86bd1140a53a32d7d5558af5be4ed778eaae179/api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto#L31) which DynamicForwardProxy filter uses to fetch DNS results.

This should allow users to set a list custom DNS servers beyond the default resolvers from `/etc/resolv.conf`

**Comment by htuch** [comment] 2021-04-29 00:58
Agreed, thanks @ntgsx92, closing this as a dupe of #15657.

**Closed by htuch** 2021-04-29 00:58 UTC
Labels: area/dns, question

**Comment by malza321** [comment] 2021-04-30 03:36
> This seems like a duplicate of https://github.com/envoyproxy/envoy/issues/15657
> 
> 
> 
> I have a working branch locally that adds `dns_resolvers` to the [DnsCacheConfig](https://github.com/envoyproxy/envoy/blob/d86bd1140a53a32d7d5558af5be4ed778eaae179/api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto#L31) which DynamicForwardProxy filter uses to fetch DNS results.
> 
> 
> 
> This should allow users to set a list custom DNS servers beyond the default resolvers from `/etc/resolv.conf`

thanks mite!!

when can I try that?

I'm really looking forward to it!!

I'm using envoy for reverse proxy, nginx for forward proxy. It,s so awkward.. I want to use envoy only!
