### ISSUE TITLE
type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute disabled option not working in version 1.19.0

### ISSUE THREAD

**Issue by shamigor** [envoyproxy/envoy#17798] opened 2021-08-21 19:04 UTC
*Title*: *type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute disabled option not working in version 1.19.0*

*Description*:
**type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute** doesn't apply per route.
The problem reproduces in version 1.19.0.  In 1.18.3 works.

*Config*:
```
              - match:
                  path: "/health/"
                  headers:
                    - name: ":method"
                      exact_match: "GET"
                direct_response:
                  status: 200
                  body:
                    inline_string: "ok"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    disabled: true
```

**Comment by dio** [comment] 2021-09-06 01:51
@shamigor sorry I couldn't reproduce this. I apply the following [patch](https://gist.githubusercontent.com/dio/f365269c7d3aa5f7b2b71d2e28185abb/raw/00686910ec823a119fc425965edb70a8969adb02/lua-per-route.diff
)[1] to Envoy `/examples` directory:

```
$ git clone git@github.com:envoyproxy/envoy.git
$ cd envoy
$ wget https://gist.githubusercontent.com/dio/f365269c7d3aa5f7b2b71d2e28185abb/raw/00686910ec823a119fc425965edb70a8969adb02/lua-per-route.diff
$ git apply lua-per-route.diff
$ cd examples/lua
$ docker-compose up --build -d
$ # wait for it
$ curl localhost:8000/health
curl localhost:8000/health --verbose
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /health HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< response-body-size: 2
< date: Mon, 06 Sep 2021 01:42:39 GMT
< server: envoy
< 
* Connection #0 to host localhost left intact
ok
```

[1] Patch for you case:
```
diff --git a/examples/lua/Dockerfile-proxy b/examples/lua/Dockerfile-proxy
index a2ea90d434..2ae88ee47e 100644
--- a/examples/lua/Dockerfile-proxy
+++ b/examples/lua/Dockerfile-proxy
@@ -1,4 +1,4 @@
-FROM envoyproxy/envoy-dev:latest
+FROM envoyproxy/envoy:v1.19.0
 ADD ./lib/mylibrary.lua /lib/mylibrary.lua
 COPY ./envoy.yaml /etc/envoy.yaml
 RUN chmod go+r /etc/envoy.yaml /lib/mylibrary.lua
diff --git a/examples/lua/envoy.yaml b/examples/lua/envoy.yaml
index e287dac120..20f6d9190c 100644
--- a/examples/lua/envoy.yaml
+++ b/examples/lua/envoy.yaml
@@ -19,6 +19,19 @@ static_resources:
               domains:
               - "*"
               routes:
+              - match:
+                  prefix: "/health"
+                  headers:
+                  - name: ":method"
+                    exact_match: "GET"
+                typed_per_filter_config:
+                  envoy.filters.http.lua:
+                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
+                    disabled: true
+                direct_response:
+                  status: 200
+                  body:
+                    inline_string: "ok"
               - match:
                   prefix: "/"
                 route:
```

**Comment by shamigor** [comment] 2021-09-07 14:08
Hi @dio, 

We can  change the function `envoy_on_request` in your patch, like this:

```
function envoy_on_request(request_handle)
    request_handle:respond({[":status"] = "401", ["content-type"] = "application/json; charset=utf-8"}, '{"error": "access denied"}')
end
```

We got 401 on request `curl localhost:8000/health` in versions 1.19.0 

In version 1.18.3 it works, returned "ok".

**Comment by dio** [comment] 2021-09-07 22:47
@shamigor I updated the patch here: https://gist.github.com/dio/048ee4daf7d5dcf5d8d44989aa1998d2

As you can see in this line https://gist.github.com/dio/048ee4daf7d5dcf5d8d44989aa1998d2#file-lua-per-route-401-diff-L38 I changed to:

```diff
                 function envoy_on_request(request_handle)
-                  request_handle:headers():add("foo", mylibrary.foobar())
+                  response_handle.respond({[":status"] = "401", ["content-type"] = "application/json"}, '{"error": "error"}')
                 end
```

Running it on my local:

```
$ docker-compose pull && docker-compose down && docker-compose up --build -d
$ curl -i localhost:8000
HTTP/1.1 200 OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 499
etag: W/"1f3-kwzFRRzUEsgOTXQIb7ZfV9ivhIE"
date: Tue, 07 Sep 2021 22:47:20 GMT
x-envoy-upstream-service-time: 2
server: envoy

{
  "path": "/",
  "headers": {
    "host": "localhost:8000",
    "user-agent": "curl/7.68.0",
    "accept": "*/*",
    "x-forwarded-proto": "http",
    "x-request-id": "73a369d9-e276-48e7-83f5-6f1325f59eb4",
    "x-envoy-expected-rq-timeout-ms": "15000"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "localhost",
  "ip": "::ffff:172.24.0.3",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "35915979e5c5"
  }
}  
```

**Comment by dio** [comment] 2021-09-07 22:59
@shamigor Ah ok, I'll take a look.

**Comment by dio** [comment] 2021-09-08 04:50
Ah, sorry. It is fixed. I think by https://github.com/envoyproxy/envoy/pull/17602. It is part of the v1.19.1 release.

```
$ docker pull envoyproxy/envoy:v1.19.1
```

**Comment by dio** [comment] 2021-09-08 05:09
I'm closing this. Let me know if upgrading to `envoyproxy/envoy:v1.19.1` doesn't solve your issue!

**Closed by dio** 2021-09-08 05:09 UTC
Labels: bug, area/lua
