### ISSUE TITLE
Envoy docker images on ECR

### ISSUE THREAD

**Issue by mdeggies** [envoyproxy/envoy#17047] opened 2021-06-18 18:57 UTC
*Title*: Public envoy docker images on ECR 

*Description*:
Now that [dockerhub is enforcing rate limits for unauthenticated pulls](https://www.docker.com/increase-rate-limits), pulling envoy images from dockerhub can cause issues for downstream projects. It would be great to have official envoy images published on [AWS ECR](https://gallery.ecr.aws/) as an alternative. This would let us (and probably others) avoid creating a dockerhub -> ECR mirror under our own namespace.

**Comment by david-yu** [comment] 2021-06-18 20:11
Hi there, I'm a Consul PM here (one of a few). We have found it a bit challenging to support AWS ECS for our use case with Envoy, and would love to see if the same Envoy image could be mirrored on the ECR repository. I just wanted to provide a bit more color here around this ask: 

Currently external users of Envoy Proxy within a Service Mesh will be rate limited quickly by Docker Hub when pulling Envoy images (resulting in errors during deployment) because docker pulls from AWS Fargate share the same IP. In addition, ECR provides the ability for Amazon customers to pull images from [private subnets without a NAT Gateway](https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html), which can bring down the cost of deploying a Service Mesh on ECS since NAT Gateways can be prohibitively expensive.

**Comment by alyssawilk** [comment] 2021-06-21 17:27
I don't think any projects here would object, but I suspect it's an issue of 1) doing the work and 2) making sure there's funding (I assume anything with unlimited downloads isn't free but correct me if I'm wrong).  If you folks are up for doing (1) and can confirm if (2) is  thing I can reach out to CNCF folks about budgeting.

**Comment by mdeggies** [comment] 2021-06-22 15:59
Hey @alyssawilk, we are up for doing the work! We'd just need to set up a new AWS account to host the images in ECR, claim the namespace, setup the repo, and update the CI pipeline to tag and push to the repo. 

As for pricing, ECR offers "50 GB-month of always-free storage for your public repositories. You can transfer 500 GB of data to the internet for free from a public repository each month anonymously (without using an AWS account.) If you sign up for an AWS account, or authenticate to ECR with an existing AWS Account, you can transfer 5 TB of data to the internet for free from a public repository each month..." Beyond that, storage is "$0.10 per GB-month for data stored in private/public repos." [[1](https://aws.amazon.com/ecr/pricing/)]

**Comment by alyssawilk** [comment] 2021-06-23 14:13
I checked with our awesome CNCF folks and they told me that docker has ratelimit exceptions for OSS projects.  He said they'll look into getting this sorted out, so hopefully we can fix without a bunch of work and switching download platforms.  I'll update here when I hear back from them, but feel free to ping back if you haven't heard in a week or so.

**Comment by mattklein123** [comment] 2021-06-28 03:44
cc @phlax

**Comment by alyssawilk** [comment] 2021-07-07 14:59
FWIW just head back from the dockerhub folks - while we haven't had the project reassessed yet we're making progress :-)

**Comment by alyssawilk** [comment] 2021-07-12 15:27
From docker: Welcome to the Docker Open Source Program!  We are very excited to have you as a part of our great community.  We have whitelisted your namespace "envoyproxy" and this should come into effect in the next week or so. With this whitelisting, the Docker data pull rate policies that went into effect last November, will not apply to the users pulling images from your namespace.  

@mdeggies let us know if you have problems after a week or so, otherwise we'll let this stale out as "fixed"

**Comment by david-yu** [comment] 2021-07-12 16:04
Thank you @alyssawilk I will sync with @mdeggies on this and our internal team! This is very exciting!

**Comment by david-yu** [comment] 2021-07-12 16:42
@alyssawilk you can go ahead and close this issue! I've confirmed that this works for our team!

**Comment by alyssawilk** [comment] 2021-07-12 16:44
Oh nice!  I guess their week or two is more like a day or two :-)

**Closed by alyssawilk** 2021-07-12 16:44 UTC
Labels: area/docker

**Comment by mdeggies** [comment] 2021-07-26 16:35
Thanks very much @alyssawilk ! :)

**Comment by lawliet89** [comment] 2024-02-16 08:53
Sorry to dig up an ancient issue. Is the envoy namespace no longer in the allowlist for open source? I got this error:

![image](https://github.com/envoyproxy/envoy/assets/983101/11085018-c0c5-4003-9761-f0e41b15672e)

**Comment by phlax** [comment] 2024-02-16 09:08
>  Is the envoy namespace no longer in the allowlist for open source?

i think that may be the case. I will follow up, but it might take a bit of time.

**Comment by lawliet89** [comment] 2024-02-16 09:18
Thanks. It seems like the allowlist is decided every 12 months based on their documentation.

**Comment by phlax** [comment] 2024-02-21 15:17
this should be resolved (again) - we have been accepted back onto the OS program

**Comment by phlax** [comment] 2024-09-05 13:15
thanks for the heads up @aykutersoyrmn - ill take a look at our Docker acc and see if there is any obvious reason

**Comment by phlax** [comment] 2024-09-05 13:19
doesnt appear to be any issue with our account - still showing as Docker-sponsored OSS

ill follow up and see if i can find out more

**Comment by aykutersoyrmn** [comment] 2024-09-05 13:24
@phlax Thanks for looking into this super fast 🙌 

We're not block on this as our workaround works pretty well, we might actually keep it forever 😄

**Comment by phlax** [comment] 2024-09-09 08:51
not sure if related - we are migrating some CI and likely increased our usage of the docker image (i started seeing the rate limit issue in ci) - ive opened a PR to resolve that here #36032
