### ISSUE TITLE
http connections on tls ports : could use better logging/troubleshooting

### ISSUE THREAD

**Issue by ldemailly** [envoyproxy/envoy#1472] opened 2017-08-15 21:51 UTC
Context: I spent a lot of time trying to figure out a misconfiguration:
I had an http client making a connection to envoy which was expecting TLS connection

when running with debug logging, one does get the quite clear:
[2017-08-15 17:37:44.057][300][debug][connection] external/envoy/source/common/ssl/connection_impl.cc:151] [C21] SSL error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST
in the log, unfortunately without debug I saw nothing - and on the client side the only thing one sees is a read error/connection closed (with no data)

Ideally as the ssl library correctly identified the request was HTTP it would be nice to return an http error to the client, but... 

At least in the default logging level it would be good to surface those bad connections
(with some flood protection so repeated port scanning/bad requests don't fill up the disk/logging system)

Including in the accesslog when the listener is an https one but in general in log as a tcp/tls error

So a first/easy fix would be to just raise the level of the existing logging from debug

Thanks!

ps: more (istio specific) context in https://github.com/istio/pilot/issues/1015

**Comment by ldemailly** [comment] 2017-11-27 00:43
this happened again today, @craigbox and I spent several hours debugging what turned out to be a ASN mismatch in certificate that rejected the connection silently

**Comment by ldemailly** [comment] 2018-02-11 04:33
this continues to bite customers, users, developers...

**Comment by PiotrSikora** [comment] 2018-02-14 00:47
@ldemailly what would be your ideal solution here? Bumping log level to `info`, so that's visible in the error logs (but I don't think there is a precedent for that) or added as a new flag to %RESPONSE_FLAG% in [access logs]?

[access logs]: https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log

**Comment by ldemailly** [comment] 2018-02-14 01:49
have it in the access/errror log with some useful / minimal code/message
it's not a "logging" event (though some detailed logging would help) it's a regular failed request

**Comment by ldemailly** [comment] 2018-02-14 01:50
ie somesort of 5xx code

**Comment by ldemailly** [comment] 2018-03-08 22:24
just got another 14 emails back and forth over a day with a user and it turned out to be this issue again... with still nothing in the logs to make a guess that was the issue

**Comment by srinandan** [comment] 2018-03-10 20:22
+1 @ldemailly - that user was me :(

I was using Envoy with Istio and assumed I had auto-sidecar injection turned on. There was nothing in the logs that give me this clue.

**Comment by ldemailly** [comment] 2018-03-10 21:05
@srinandan : click there:
<img width="533" alt="screen shot 2018-03-10 at 1 04 57 pm" src="https://user-images.githubusercontent.com/3664595/37246716-b12331d8-2463-11e8-8d4b-2da16f115ba5.png">
;)

**Comment by craigbox** [comment] 2018-09-01 13:15
This remains an issue.  (/activity)

**Comment by cmluciano** [comment] 2018-09-10 15:52
I can work on this but I’m unsure what we settled on. Do we want to just bump the log level or do we want to expose this in the access log?

cc @htuch for feedback

**Comment by ldemailly** [comment] 2018-09-10 18:56
it should be imo a 400s or 500s type error clearly indicated in error log and/or access log
ps: it would be sensational to also have the default log include the transport and protocol (tls vs not)

**Comment by htuch** [comment] 2018-09-12 17:18
Is this a dupe of https://github.com/envoyproxy/envoy/issues/4283 essentially?

**Comment by cmluciano** [comment] 2018-09-12 17:40
On the surface it sounds related, I requested access to that design proposal to clarify. Can someone assign this issue to me?

**Comment by mattklein123** [comment] 2018-09-19 18:40
IMO this issue has no concrete ideas on what to actually change. I don't have any high level objection on having better debugging, but I think someone needs to propose an actual change. I will remark this design proposal.

**Comment by htuch** [comment] 2018-09-20 16:56
@mattklein123 AFAICT, we want to mark this dupe of #4283 and leave a note there that we should also make sure any design correctly captures SSL failure details.

**Comment by mattklein123** [comment] 2018-09-20 17:34
@htuch sure that's fine with me, though I'm not sure that is what @ldemailly was originally after here.

**Comment by ldemailly** [comment] 2018-09-20 17:42
well as long as you can tell with the default config that an incoming connection was rejected and why, it will be fantastic, how that happens doesn't matter to me.

**Comment by htuch** [comment] 2018-09-20 19:53
OK, continuing tracking at https://github.com/envoyproxy/envoy/issues/4283.

**Closed by htuch** 2018-09-20 19:53 UTC
Labels: design proposal

**Comment by vilobhmm** [comment] 2018-09-20 20:49
@mattklein123 @htuch @ldemailly : The doc is shared here https://docs.google.com/document/d/1fMEK80KlpHcL4CwhniOupgQu4MDsxK4y4dKhthjjCMA/edit and also shared with Envoy community. I will amend the doc to add the scenario that @ldemailly is describing. Thanks!
