### ISSUE TITLE
How can I make envoy send an authentication header stored in an httpOnly cookie to gRPC?

### ISSUE THREAD

**Issue by kurnal-volt** [envoyproxy/envoy#14699] opened 2021-01-14 07:36 UTC
*Title*: How can I make envoy send a cookie stored as an httpOnly to gRPC?

*Description*:
If I have a token stored in a cookie, how can I send that to gRPC as metadata? How would I configure envoy to do this?

**Comment by htuch** [comment] 2021-01-14 18:52
This seems a dupe of #14698

**Closed by htuch** 2021-01-14 18:52 UTC
Labels: triage
