### ISSUE TITLE
stats: prometheus scrape failed

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#27173] opened 2023-05-04 07:32 UTC
the following golang code:
```golang
package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/prometheus/common/expfmt"
)

func main() {
	_, body, err := HTTPGet(fmt.Sprintf("http://127.0.0.1:%d/stats/prometheus", 9901))
	if err != nil {
		fmt.Println("get metric error: %v", err)
		return
	}
	reader := strings.NewReader(body)
	_, err = (&expfmt.TextParser{}).TextToMetricFamilies(reader)
	if err != nil {
		fmt.Println("parse metric error: %v body: %s", err, body)
	}
}

func HTTPGet(url string) (code int, respBody string, err error) {
	log.Println("HTTP GET", url)
	client := &http.Client{Timeout: time.Minute}
	resp, err := client.Get(url)
	if err != nil {
		log.Println(err)
		return 0, "", err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Println(err)
		return 0, "", err
	}
	respBody = string(body)
	code = resp.StatusCode
	return code, respBody, nil
}
```
will pass with `envoyproxy/envoy:dev-01aed8aa302d707a5598dbfd063dcfe3b31655f8` and fail with `envoy:dev-6301fefe405d5c9bade12658034f17f5ad4cdd3c`

[after.txt](https://github.com/envoyproxy/envoy/files/11395339/after.txt)
[before.txt](https://github.com/envoyproxy/envoy/files/11395340/before.txt)

seems related to https://github.com/envoyproxy/envoy/pull/24998

cc @kyessenov @rulex123 @jmarantz

**Comment by rulex123** [comment] 2023-05-04 09:22
Looks like there's extra # TYPE lines for some of the metrics

**Comment by yanavlasov** [comment] 2023-05-04 13:34
@ggreenway for any ideas

**Comment by jmarantz** [comment] 2023-05-04 13:44
Scanning the issue description, it seems like the issue is that previously `# TYPE envoy_cluster_assignment_stale counter` would only be issued once for all the tags under that name, and now the `# TYPE` line is issued for every tag.

It should be easy to repro in a unit test. I'm hoping we can fix forward quickly.

**Comment by rulex123** [comment] 2023-05-05 12:52
I am afraid is not a simple issue with the way a metric is rendered, something seems amiss on a more fundamental level.

I can easily observe the same issue if I run Envoy locally with a few clusters configured; when I curl the prometheus stats admin endpoint I can see that the output is completely jumbled up. Here's an excerpt of the output:

```
# TYPE envoy_cluster_assignment_stale counter
envoy_cluster_assignment_stale{envoy_cluster_name="authz_cluster"} 0
# TYPE envoy_cluster_assignment_timeout_received counter
envoy_cluster_assignment_timeout_received{envoy_cluster_name="authz_cluster"} 0
# TYPE envoy_cluster_bind_errors counter
envoy_cluster_bind_errors{envoy_cluster_name="authz_cluster"} 0
# TYPE envoy_cluster_default_total_match_count counter
envoy_cluster_default_total_match_count{envoy_cluster_name="authz_cluster"} 1
# TYPE envoy_cluster_assignment_stale counter
envoy_cluster_assignment_stale{envoy_cluster_name="health_cluster"} 0
# TYPE envoy_cluster_assignment_timeout_received counter
envoy_cluster_assignment_timeout_received{envoy_cluster_name="health_cluster"} 0
# TYPE envoy_cluster_bind_errors counter
envoy_cluster_bind_errors{envoy_cluster_name="health_cluster"} 0
# TYPE envoy_cluster_default_total_match_count counter
envoy_cluster_default_total_match_count{envoy_cluster_name="health_cluster"} 1
```   

The expected result is that metrics with the same name (e.g. envoy_cluster_assignment_stale) but different tags (e.g. envoy_cluster_name) are grouped together and rendered as one "block" (with one "# TYPE" line preceding each group), e.g

```
# TYPE envoy_cluster_assignment_stale counter
envoy_cluster_assignment_stale{envoy_cluster_name="authz_cluster"} 0
envoy_cluster_bind_errors{envoy_cluster_name="health_cluster"} 0
```

I tried briefly to reproduce this issue in a test but didn't manage so far. I don't have any leads yet so we might need to revert the changes in https://github.com/envoyproxy/envoy/pull/24998 unless @jmarantz or @ggreenway have any ideas or pointers on what might be going on?

**Comment by jmarantz** [comment] 2023-05-05 17:22
@zirain would you be able to provide a bootstrap config to help repro? Thanks!

**Comment by ggreenway** [comment] 2023-05-05 18:27
@jmarantz it looks like @rulex123 said it was trivial to reproduce above, just not in a test.

I think unless we have a solid idea of how to fix it quickly we should revert. This is a major regression.

**Comment by kyessenov** [comment] 2023-05-05 18:28
You can take configs/envoy-demo and duplicate the cluster.

**Comment by jmarantz** [comment] 2023-05-05 21:44
I see. I'm thinking the problem is that tag-extracted names that need to be grouped together are coming from different Stats::Scope objects, and we are streaming them out from the first scope before examining the second scope.

This is going to require some thought on how to fix without compromising the speed/memory benefit offered by the new algo @rulex123 deployed.

**Comment by jmarantz** [comment] 2023-05-05 21:57
repro here:

I'm pretty sure we can fix this by considering all the scopes named the same thing at the same time. E.g. don't stream out the results from a scope named "foo" if until we encounter (in our alphabetic iter thru scopes) a scope named something *other* than "foo".

**Comment by jmarantz** [comment] 2023-05-06 00:54
I thought I had a theory and a repro in a unit test but I don't. In fact I can't repro at all; it seems to be working for me. I was expecting it to fail due to the problem of aliasing two different counters from different scopes that wind up with the same tag-extracted name. But I couldn't get it to fail as expected; I'll have to come back to it or maybe @rulex123 can pick it up.

Right now it feels to me like the reason I couldn't get it to fail is that the streaming behavior of stats_request.cc is not working as expected, and the buffering that's going on is enabling the mechanism to coalesce all the common tag-extracted-names. It might be that with a few more clusters there's some flushing going on but I haven't sorted it out.

I think I'll write a revert PR if no one else has yet.

https://github.com/envoyproxy/envoy/pull/27224 is my attempt at a repro in a unit test. Note I used ThreadLocalStore in the unit test because I was thinking multiple distinct scopes were needed to repro this issue and that really doesn't happen with the TestStore instances based on IsolatedStoreImpl.

**Comment by jmarantz** [comment] 2023-05-06 01:12
It would be helpful if someone could post a complete repro; e.g. attach a file; maybe an altered version of configs/envoy-demo.yaml.

**Comment by zirain** [comment] 2023-05-06 01:14
@jmarantz I test locally with this docker-compose https://github.com/zirain/playground/blob/master/envoy/docker-compose.yml

**Comment by jmarantz** [comment] 2023-05-06 01:16
All I need is the yaml config file; I don't think it matters if it's in docker or not.

**Comment by zirain** [comment] 2023-05-06 01:17
https://github.com/zirain/playground/blob/master/envoy/envoy.yaml

**Comment by jmarantz** [comment] 2023-05-06 01:23
Thanks @zirain; that does it:
```
      4 # TYPE envoy_cluster_default_total_match_count counter
      4 # TYPE envoy_cluster_circuit_breakers_high_rq_retry_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_high_rq_pending_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_high_rq_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_high_cx_pool_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_high_cx_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_default_rq_retry_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_default_rq_pending_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_default_rq_open gauge
      4 # TYPE envoy_cluster_circuit_breakers_default_cx_pool_open gauge
```

**Comment by jmarantz** [comment] 2023-05-06 12:36
Closing this issue as the PR was reverted. Following up in #16139 with further notes on why the algorithm didn't work as expected.

**Closed** 2023-05-06 23:14 UTC
Labels: bug, area/stats
