### ISSUE TITLE
Does Envoy Redis proxy support RESP3?

### ISSUE THREAD

**Issue by muvelus** [envoyproxy/envoy#30804] opened 2023-11-09 11:21 UTC
*Title*: *Need support for RESP3 protocol for Redis proxy*

*Description*:
>We encountered an issue where RESP3 protocol was not supported by the envoy proxy. Can you suggest a workaround to have the support for the same until the feature is added? 
If the support is already there, can you mention the Envoy version from which it is available? Thanks

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by htuch** [comment] 2023-11-14 05:35
This seems a dupe of https://github.com/envoyproxy/envoy/issues/17571, please followup there.

**Closed by htuch** 2023-11-14 05:35 UTC
Labels: enhancement, triage
