### ISSUE TITLE
Please let me know the process of creating a shared library of set of management API's

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#32461] opened 2024-02-19 08:13 UTC
https://blog.envoyproxy.io/the-universal-data-plane-api-d15cec7a
In this link, I have read that 

API configurability: Perhaps most importantly, Envoy provides a set of [management APIs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/dynamic_configuration) that can be implemented by control plane services. If a control plane implements all of the APIs, it becomes possible to run Envoy across an entire infrastructure using a generic common bootstrap configuration. All further configuration changes are delivered seamlessly and dynamically via the management server in such a way that Envoy never needs to be restarted. This makes Envoy a universal data plane that, when coupled with a sophisticated enough control plane, vastly reduces overall operational complexity.

Please let know the steps to create the shared library of set if management API's

**Comment by phlax** [comment] 2024-02-19 14:02
closing this is a duplicate of https://github.com/envoyproxy/envoy/issues/31216 where you have already been provided with as much assistance and explanation as we can offer (this was itself a duplicate of https://github.com/envoyproxy/envoy/issues/30637

**Closed by phlax** 2024-02-19 14:02 UTC
Labels: enhancement, triage
